- src/app/auth/auth.guard.spec.ts
- src/app/auth/auth.guard.ts
- src/app/components/layout/header/header.component.spec.ts
- src/app/components/layout/header/header.component.ts
- src/app/components/login/login.component.spec.ts
- src/app/components/login/login.component.ts
- src/app/services/auth/auth.service.spec.ts
- src/app/services/auth/auth.service.ts
n/a
- avoid calling `/is-authenticated` lots of times
- only doing it on the auth guard
- everywhere else just checks a stored value
```
[ ] Yes
[x] No
```
> More authentication fixes

- server/controllers/auth.ts
- server/views/azuread-b2c-login.html
A condition has been added which targets the outro text on the bottom of the page. If the URL contains the query parameter 'screenName=loginScreen', then the text is visible. If this parameter does not exist in the URL, then the text will not display.
```
[ ] Yes
[x] No
```
> dmp-625 : feat : add display condition to outro text

- src/app/components/search/search.component.css
- src/app/components/search/search.component.html
- src/styles.scss
Previously, the mouse pointer didn't change to a 'pointing hand' when hovering over the 'clear search' button. It now does.
```
[ ] Yes
[ x ] No
```
> dmp-507 : patch : mouse cursor change on the clear search link

- src/app/components/search/search.component.html
Fixes the issue where the clear search link was being missed when the web pages elements were tabbed through.
```
[ ] Yes
[ x ] No
```
> dmp-507 : patch : fix missing tabbed link

- src/app/components/search/search.component.spec.ts
- src/app/components/search/search.component.ts
https://tools.hmcts.net/jira/browse/DMP-909
Sets date_to form control when specific date picker is used. This prevents DB returning everything after date_from when date_to is null.
```
[ ] Yes
[ X] No
```
> Portal - Advanced Search - Specific date picker not setting date_to

- src/app/components/hearing/hearing.component.scss
Remove whitespace at the top of hearing screen
> Fix whitespace on hearing screen

- src/app/components/app.component.html
- src/app/components/case/case-file/case-file.component.html
N/A
[Removing phase banner](https://github.com/hmcts/darts-portal/commit/f0cf9ff841b6780fd479a5ad07ea29c9a655b231) 
- it's not on the designs
[Removing "Change" link on case screen when "Retained until" is not present](https://github.com/hmcts/darts-portal/commit/6ec3340240fd18c84664e0912542ff2ff5e4c348) 
- the action is redundant and it looks bad
```
[ ] Yes
[x] No
```
> Demo tweaks

- src/app/components/search/results/results.component.html
- src/styles.scss
https://tools.hmcts.net/jira/browse/DMP-890
- Removed 'Hearing Date' column from search results
- Set global table header style to UK gov blue
> DMP-890: Table column headers

- darts-api-stub/authentication/external.js
- server/controllers/index.ts
- server/controllers/user.ts
- server/routes.ts
- server/types/classes/securityToken.ts
- server/types/classes/userState.ts
- src/app/components/search/search.component.ts
- src/app/services/app-config/app-config.service.ts
- src/app/services/user/user.service.spec.ts
- src/app/services/user/user.service.ts
- src/app/types/user-state.ts
N/A
- via /user/profile endpoint on the node server
- `userService.getUserProfile` can be used in angular component, must be an async call
```
[ ] Yes
[x] No
```
> Exposing user profile to angular

- src/app/components/common/loading/loading.component.html
- src/app/components/common/loading/loading.component.scss
- src/app/components/common/loading/loading.component.spec.ts
- src/app/components/common/loading/loading.component.ts
- src/app/components/hearing/hearing.component.html
- src/app/components/hearing/hearing.component.ts
N/A
I know it's not in the design (yet), but I thought the "Loading..." text we display when loading hearing could do with being a bit more stylish.
<p align="center">
</p>
> Adding loading component

- src/app/components/audios/audios.component.ts
- src/app/components/hearing/order-confirmation/order-confirmation.component.html
- src/app/components/hearing/request-playback-audio/request-playback-audio.component.ts
- src/app/services/audio/audio.service.spec.ts
- src/app/services/audio/audio.service.ts
- src/app/services/case/case.service.spec.ts
- src/app/services/case/case.service.ts
Hearing dates are displaying a day behind on the the portal. This is due to date format 'yyyy-mm-dd' on hearing dates being returned from the API.
This is inconsistent with other date / time responses. The fix is to append 'Z' to dates so the Datepipe in Angular understands this date to be UTC and not BST and therefore not subtract an hour from the day before.
> Map hearing date responses to UTC format

- src/app/services/app-insights/app-insights.service.ts
N/A
Setting up "Cloud role name" for application insights.
> Setting app-insights cloud role name

- pa11y/pa11y.ts
This change hides known issues flagged in pa11y by default. Log output changed to show count of unknown issues, and also show detail of these issues.
There is still problem accessing pages which require UserState when pa11y runs in non auth mode, to be covered in separate ticket.
> pa11y updates to show only new issues, flag to ignore known

- server/assets/javascripts/errors.js
- server/assets/javascripts/reset-password.js
DMP-1245
Moved logic out of addItemLevelErrorClasses for 'reset' into addVerificationControlErrors. Updated logic to be referenced by new input and click events for email input and send code button
> DMP-1245 b2c change password email address validation

- src/app/components/hearing/request-playback-audio/request-playback-audio.component.ts
- src/app/services/audio-request/audio-request.service.spec.ts
- src/app/services/audio-request/audio-request.service.ts
- src/app/services/case/case.service.spec.ts
- src/app/services/case/case.service.ts
https://tools.hmcts.net/jira/browse/DMP-1277
Turns out that appending just 'Z' to dates to get a UTC date only works in Chrome.
The fix is to append the full 'T00:00:00Z' for the time portion of the DateTime.
> DMP:1277: Fix date bug for Safari and Firefox

- config/custom-environment-variables.json
- config/default.json
- server/controllers/authentication.ts
- server/utils/base64.ts
N/A
- this means passing a base64 encoded SecurityToken object to a special endpoint
- this endpoint adds it to the session allowing authentication without going through the AD flow
- the access token is still checked on the API so it must be valid
- this can be used to test when authentication through the AD is not possible, possibly due to callback URLs
> Adding option to allow auth bootstrap

- config/custom-environment-variables.json
- config/default.json
- config/development.json
- server/middleware/session.ts
N/A
We need to be able to disable using of secure cookies in the staging environment. This is to enable a test which does not go through SSL.
- default to on if NODE_ENV is "production"
- override development env to false
> Allow secure cookies to be disabled

- cypress/e2e/functional/case-search-spec.cy.js
- cypress/e2e/functional/error-spec.cy.js
- darts-api-stub/cases/case.js
- pa11y/pa11y.ts
- src/app/app.routes.ts
- src/app/components/error/internal-server/internal-error.component.html
- src/app/components/error/internal-server/internal-error.component.spec.ts
- src/app/components/error/internal-server/internal-error.component.ts
- src/app/components/hearing/events-and-audio/events-and-audio.component.ts
- src/app/components/search/search-error/search-error.component.html
- src/app/components/search/search-error/search-error.component.spec.ts
- src/app/components/search/search-error/search-error.component.ts
- src/app/components/search/search.component.spec.ts
- src/app/components/search/search.component.ts
- src/app/interceptors/error/error.interceptor.spec.ts
- src/app/interceptors/error/error.interceptor.ts
- src/app/services/audio-request/audio-request.service.spec.ts
- src/app/services/error/error-handler.service.spec.ts
- src/app/services/error/error-handler.service.ts
- src/app/services/error/error-message.service.spec.ts
- src/app/services/error/error-message.service.ts
- src/app/types/error-message.interface.ts
DMP-1323 Generic internal server error page, unit tests, functional tests, stub updated
Now handles both page and component style errors, errors not handled in component i.e. generic 500 errors will default to page redirect.
To test against local stub, enter "INTERNAL_SERVER_ERROR" in case number search for component error.
> DMP-1323 Generic internal server error page, unit tests, functional tests

- cypress/e2e/functional/your-audio-spec.cy.js
Intermittent failure with the following statement in functional test
```
cy.get('audio').then(([audioEl]) => {
expect(audioEl.paused).to.equal(true);
});
```
> Temporary ignore failing FT statements

- server/controllers/api.ts
- src/app/services/audio-request/audio-request.service.ts
[DMP-1383](https://tools.hmcts.net/jira/browse/DMP-1383)
- Set header in proxyReq to include **user__id** from **securityToken.userState.userId**
- Removed user_id header being set in **getUnreadCount** and **getAudioRequests**  from userState
> DMP-1383 - Inject user_id header for all DARTS API requests

- cypress/e2e/functional/hearing-transcripts-spec.cy.js
- cypress/e2e/functional/view-transcript.cy.js
- darts-api-stub/hearings/hearings.js
- darts-api-stub/transcriptions/transcriptions.js
- src/app/services/transcription/transcription.service.ts
DMP-1610
Default name added for transcription file to fix breadcrumb on staging due to correlating data not existing in transcription_document
Cypress updated
> DMP-1610 Default name for transcription file, cypress updated

- src/app/components/audios/audios.component.ts
- src/app/services/audio-request/audio-request.service.ts
N/A
The endpoint: `/audio-requests?expired=false` was being called twice on, on load, on 'Your Audio' screen.
This was due to multiple subscribes in the template causing multiple/duplicate HTTP requests.
This PR fixes the issue by using shareReplay() to cache the data at the component level so that any extra async pipes / subscriptions get the previously fetched data.
This works with existing polling functionality.
Wrapped the service call inside a refresh$ observable allows us to manually refresh the data when necessary such as after a delete operation to get the latest data from the server.
Removed some redundant code from the AudioRequestService
> Your Audio - Prevent extra network call on load

- src/app/components/transcriptions/approve-transcript/approve-transcript-buttons/approve-transcript-buttons.component.spec.ts
- src/app/components/transcriptions/approve-transcript/approve-transcript-buttons/approve-transcript-buttons.component.ts
[DMP-1815](https://tools.hmcts.net/jira/browse/DMP-1815)
Amended wording for error message when attempting to submit without selecting Approve or Reject first
> DMP-1815 - Error message - Neither Approve/Reject selected on request approval

- server/assets/javascripts/errors.js
- server/assets/javascripts/login.js
(https://tools.hmcts.net/jira/browse/DMP-1773)
Jquery js updates to hide required input errors from showing on login page load
Not fully tested yet as unable to fire event on page load remotely
> DMP-1773 Bug - Login b2c screen input errors

- src/app/components/transcriptions/transcription-requests/transcription-requests.component.html
- src/app/components/transcriptions/transcription-requests/transcription-requests.component.ts
- src/app/components/transcriptions/transcriptions.component.html
- src/app/components/transcriptions/transcriptions.component.spec.ts
- src/app/components/transcriptions/transcriptions.component.ts
- src/app/components/your-work/your-work.component.html
- src/app/components/your-work/your-work.component.spec.ts
- src/app/components/your-work/your-work.component.ts
- src/app/constants/transcription-columns.ts
- src/app/services/sort/sort.service.spec.ts
- src/app/services/sort/sort.service.ts
- src/app/services/transcription/transcription.service.spec.ts
- src/app/services/transcription/transcription.service.ts
- src/app/types/user-transcription-request.interface.ts
- src/app/types/work-request.interface.ts
[1746](https://tools.hmcts.net/jira/browse/DMP-1746)
- Move urgency mapping to the service layer to be re-usable
- Add urgency sorting to required tables
- Decoupled DTO interface from VM where needed
- Rename `TableCustomSortFunctionsService` to `SortService`
- Return a default urgency if one can't be found
- Fix tests
> DMP-1746: Add urgency sort to required tables

- server/assets/javascripts/errors.js
DMP-1773 
Only off click/keydown/input event if email/password contains values to allow actions like autocomplete to not fire early on the click
> DMP-1773 B2C login errors

- src/app/components/search/search.component.spec.ts
- src/app/components/search/search.component.ts
- src/app/services/case/case.service.ts
DMP-1925
I believe the previous code which was assigning searchErrors$ in the onSubmit function was causing the issue. I moved the required code to prevent caching error states in the searchResults$ catchError instead
> DMP-1925 Infinite loading bug

- src/app/components/search/search.component.ts
DMP-1925
Bug can be re-created with;
1. Enter the courtroom 
2. Click the Search button
3. The warning "You must also enter a courthouse" is displayed
4. Now just enter the Courthouse, No Error message infinite loading spinner
Fix involved setting isSubmitted to false on courthouse select to prevent infinite spinner
> DMP-1925 Loading bug

- cypress/e2e/functional/case-file-spec.cy.js
- cypress/e2e/functional/case-retention-spec.cy.js
- darts-api-stub/cases/case.js
- darts-api-stub/index.js
- darts-api-stub/retentions/retention.js
- src/app/app.routes.ts
- src/app/components/case/case-file/case-file.component.html
- src/app/components/case/case-file/case-file.component.spec.ts
- src/app/components/case/case-file/case-file.component.ts
- src/app/components/case/case-retention-date/case-retention-date.component.html
- src/app/components/case/case-retention-date/case-retention-date.component.scss
- src/app/components/case/case-retention-date/case-retention-date.component.spec.ts
- src/app/components/case/case-retention-date/case-retention-date.component.ts
- src/app/components/common/details-table/details-table.component.html
- src/app/components/common/notification-banner/notification-banner.component.html
- src/app/components/common/notification-banner/notification-banner.component.scss
- src/app/components/common/notification-banner/notification-banner.component.spec.ts
- src/app/components/common/notification-banner/notification-banner.component.ts
- src/app/components/hearing/request-transcript/request-transcript-confirmation/request-transcript-confirmation.component.html
- src/app/components/transcriptions/view-transcript/view-transcript.component.html
- src/app/services/case/case.service.spec.ts
- src/app/services/case/case.service.ts
- src/app/types/case-retention-history.interface.ts
- src/app/types/case.interface.ts
DMP-1406
- New case retention screen
- Notification banner into own component
- Updated stubs for GET /cases/{id} endpoint, and new GET /retentions?id=1
- Unit tests / FT 
To test;
See /case/1 & /case/2 for same page, different visible elements. 
Logic is;
Info banner: "if that array is empty OR latest record is PENDING then show banner, else hide it"
Button group: "if latest record is COMPLETE then show button group, else hide it"
> DMP-1406 Case Retention

- src/app/services/error/error-message.service.spec.ts
- src/app/services/error/error-message.service.ts
https://tools.hmcts.net/jira/browse/DMP-2051
Created ignored endpoints array, and isIgnored function to ensure page redirect does not occur on not-accessed-count endpoint for specific responses.
> DMP-2051 Ignore Audio count API errors

- src/app/components/common/data-table/data-table.component.html
- src/app/components/common/data-table/data-table.component.spec.ts
- src/app/components/common/data-table/data-table.component.ts
- src/app/components/search/results/results.component.html
- src/app/services/transcription/transcription.service.spec.ts
- src/app/services/transcription/transcription.service.ts
https://tools.hmcts.net/jira/browse/DMP-1924
- Fixed bug as per JIRA ticket
- Urgencies are now cached in the TranscriptionService to avoid duplicate calls
> DMP-1924: Data table bugfix - maintain sorting and paging state on data refresh

- cypress/e2e/functional/your-transcripts-spec.cy.js
- src/app/components/transcriptions/approve-transcript/approve-transcript-buttons/approve-transcript-buttons.component.html
- src/app/components/transcriptions/approve-transcript/approve-transcript-buttons/approve-transcript-buttons.component.ts
[DMP-1926](https://tools.hmcts.net/jira/browse/DMP-1926)
Fix an issue where clicking the "No" button when it's already selected would make the error messages disappear.
> DMP-1926 - UI Bug: Reject transcript validation unexpected behaviour

- src/app/components/common/data-table/data-table.component.spec.ts
- src/app/components/common/data-table/data-table.component.ts
https://tools.hmcts.net/jira/browse/DMP-2188
- it was only showing the first page of rows
- if pagination is set to false then load all rows into the first page
> DP-2188 Data table with no pagination fix

- cypress/e2e/functional/case-retention-spec.cy.js
- src/app/core/components/common/datepicker/datepicker.component.scss
- src/app/core/components/common/validation-error-summary/validation-error-summary.component.scss
- src/app/portal/components/case/case-retention-date/case-retention-change/case-retention-change.component.spec.ts
- src/app/portal/components/case/case-retention-date/case-retention-change/case-retention-change.component.ts
[DMP-2161](https://tools.hmcts.net/jira/browse/DMP-2161)
Adds `white-space: pre-line;` to datepicker and validation-error components so that error messages can span across multiple lines:
> DMP-2161 [UPDATE] - Render new line characters in error messages

- cypress/e2e/functional/request-transcript-spec.cy.js
- darts-api-stub/transcriptions/transcriptions.js
- src/app/portal/components/hearing/request-transcript/request-transcript-exists/request-transcript-exists.component.html
[DMP-1756](https://tools.hmcts.net/jira/browse/DMP-1756)
Minor screen updates
When a transcript request is still in progress, the "Go to transcript" link will not be visible. To test this, remove duplicate_transcription_id from body in stub. Body should not be completely empty.
> DMP 1756 - Dupe transcript page updates

- package.json
https://tools.hmcts.net/jira/browse/DMP-1614
- the downloads directory must be copied into dist during the build
> DMP-1614 Fixing annotation document download for production builds

- src/app/portal/components/hearing/add-annotation/add-annotation.component.html
[DMP-2455](https://tools.hmcts.net/jira/browse/DMP-2455)
- Add label for annotation comments on _Add annotation_ screen
- Stub link: http://localhost:3000/case/1/hearing/1/add-annotation
> DMP-2455: Add label for annotation comments

- src/app/core/components/common/govuk-heading/govuk-heading.component.html
- src/app/core/components/common/govuk-heading/govuk-heading.component.ts
- src/app/core/components/error/conflict/conflict.component.html
- src/app/core/components/error/forbidden/forbidden.component.html
- src/app/core/components/error/internal-server/internal-error.component.html
- src/app/core/components/error/not-found/not-found.component.html
[DMP-2257](https://tools.hmcts.net/jira/browse/DMP-2257)
- Remove tabIndex from headings and use aria role alert instead for error pages
Ignore branch name, incorrect ticket number
> DMP-2257: Remove tabIndex from headings and use aria role alert instead

- cypress/e2e/functional/admin-portal/groups-spec.cy.js
- src/app/admin/admin.routes.ts
- src/app/admin/components/courthouses/courthouse-record/courthouse-record.component.spec.ts
- src/app/admin/components/courthouses/create-courthouse/create-update-courthouse-confirmation/create-update-courthouse-confirmation.component.spec.ts
- src/app/admin/components/courthouses/create-courthouse/create-update-courthouse-form/create-update-courthouse-form.component.spec.ts
- src/app/admin/components/groups/groups.component.html
- src/app/admin/components/groups/groups.component.scss
- src/app/admin/components/groups/groups.component.spec.ts
- src/app/admin/components/groups/groups.component.ts
- src/app/admin/components/users/user-groups/assign-groups/assign-groups.component.spec.ts
- src/app/admin/components/users/user-groups/assign-groups/assign-groups.component.ts
- src/app/admin/components/users/user-groups/remove-groups/remove-groups.component.spec.ts
- src/app/admin/components/users/user-groups/user-groups/user-groups.component.spec.ts
- src/app/admin/models/users/security-group.interface.ts
- src/app/admin/models/users/security-group.type.ts
- src/app/admin/services/courthouses/courthouses.service.ts
- src/app/admin/services/groups/groups.service.spec.ts
- src/app/admin/services/groups/groups.service.ts
- src/app/admin/services/user-admin/user-admin.service.spec.ts
- src/app/admin/services/user-admin/user-admin.service.ts
[DMP-2278](https://tools.hmcts.net/jira/browse/DMP-2278)
- Add groups admin screen
- Filter by group name or role
- Moved getGroups and getRoles from UserAdminService to GroupsService
- Created a getGroupsAndRoles call to retrieve both groups and roles and map them together
- Add description property to SecurityGroup type
> DMP-2278: Groups admin screen

- src/app/admin/components/groups/group-form/group-form.component.html
- src/app/admin/components/users/create-user/create-update-user-form/create-update-user-form.component.html
[DMP-2711](https://tools.hmcts.net/jira/browse/DMP-2711)
Validation error messages movin submit button down when clicking preventing the onSave() firing.
Add `(mousedown)="(false)"` to submit button on form to prevent the blur event from moving the button.
More info here:
https://stackoverflow.com/questions/48011167/click-handler-is-not-triggered-when-target-element-has-been-moved
> DMP-2711: Fix button event handler in group and user forms

- darts-api-stub/admin/courthouses/courthouses.js
- darts-api-stub/admin/regions/regions.js
- darts-api-stub/admin/retention-policies/retention-policies.js
- darts-api-stub/annotations/annotations.js
- darts-api-stub/authentication/userstate.js
- darts-api-stub/index.js
- darts-api-stub/retentions/retention.js
- darts-api-stub/users.js
- server/controllers/user.ts
- src/app/core/components/app/app.component.spec.ts
- src/app/core/components/app/app.component.ts
- src/app/core/services/user/user.service.spec.ts
- src/app/core/services/user/user.service.ts
https://tools.hmcts.net/jira/browse/DMP-2638
- adding API stub for GET /userstate
- adding node server endpoint for POST /user/refresh-profile
- calling the refresh profile endpoint on navigation end, if signed in
- increasing test coverage of user.service
- renaming some functions in the users file in the stub
> DMP-2638 Refresh UserState on each route change

- src/app/admin/components/retention-policies/create-edit-retention-policy/create-edit-retention-policy.component.ts
- src/app/admin/components/retention-policies/retention-policy-form/retention-policy-form.component.ts
[DMP-2886](https://tools.hmcts.net/jira/browse/DMP-2886)
Subsequent server-side errors are not reflected in the UI. This fix sets the error to null before a new request is made.
> DMP-2886: Emit error summary and clear error on save

- src/app/portal/components/search/search.component.ts
[DMP-2905](https://tools.hmcts.net/jira/browse/DMP-2905)
Marking form control as touched allows requests to be made to the server.
Steps to replicate failure not in the ticket:
1. Perform search
2. Clear search
3. Select a date from datepicker without touching the form
4. No network call made
Adding `.markAsTouched()` fixes this
> DMP-2905: Mark form as touched when setting input value

- src/app/admin/components/file-deletion/file-deletion.component.html
N/A
It's now the same size as the "System configuration" heading
> Fixing the size of the admin "File deletion" heading

- src/app/core/components/cookies/cookies.component.html
[DMP-2864](https://tools.hmcts.net/jira/browse/DMP-2864)
- Fixes for missing form labels at bottom of cookies page
> DMP-2864: Missing/Orphaned form labels on cookies page

- server/server.ts
N/A
Due to the API stubbing, the directories in `dist` have changed. Updating the code to find the assets correctly in there.
The side-effect of this is that the azure login page (http://localhost:3000/auth/azuread-b2c-login) will not work locally, but when the stubbing is removed this can be reverted.
> Fixing path to assets

- src/app/admin/constants/transcript-search-form-error-messages.ts
- src/app/admin/services/transcription-admin/transcription-admin.service.spec.ts
- src/app/admin/services/transcription-admin/transcription-admin.service.ts
- src/app/core/components/common/specific-or-range-date-picker/specific-or-range-date-picker.component.spec.ts
- src/app/core/components/common/specific-or-range-date-picker/specific-or-range-date-picker.component.ts
[DMP-3085](https://tools.hmcts.net/jira/browse/DMP-3085)
- Remove optional required field for transcript search
- map specific date to both 'from' and 'to' to constrain search results
> DMP-3085 : Fix API call for transcript search by specific date and remove required validation

- src/app/admin/services/transcription-admin/transcription-admin.service.spec.ts
- src/app/admin/services/transcription-admin/transcription-admin.service.ts
[DMP-2525](https://tools.hmcts.net/jira/browse/DMP-2525)
Small bugfix to hide associated groups for awaiting authorisation and requested statuses
> DMP-2525: Hide groups on awaiting auth or requested status

- cypress/e2e/functional/admin-portal/transcript-requests-spec.cy.js
- darts-api-stub/admin/transcriptions/transcription-documents.js
- darts-api-stub/index.js
- src/app/admin/admin.routes.ts
- src/app/admin/components/transcripts/search-completed-transcripts-results/search-completed-transcripts-results.component.html
- src/app/admin/components/transcripts/search-completed-transcripts-results/search-completed-transcripts-results.component.spec.ts
- src/app/admin/components/transcripts/search-completed-transcripts-results/search-completed-transcripts-results.component.ts
- src/app/admin/components/transcripts/search-transcripts-form/search-transcripts-form.component.html
- src/app/admin/components/transcripts/search-transcripts-form/search-transcripts-form.component.ts
- src/app/admin/components/transcripts/search-transcripts-results/search-transcripts-results.component.ts
- src/app/admin/components/transcripts/transcripts.component.html
- src/app/admin/components/transcripts/transcripts.component.spec.ts
- src/app/admin/components/transcripts/transcripts.component.ts
- src/app/admin/components/transcripts/view-transcription-document/view-transcription-document.component.html
- src/app/admin/components/transcripts/view-transcription-document/view-transcription-document.component.spec.ts
- src/app/admin/components/transcripts/view-transcription-document/view-transcription-document.component.ts
- src/app/admin/models/transcription/index.ts
- src/app/admin/models/transcription/transcription-document-data.interface.ts
- src/app/admin/models/transcription/transcription-document.ts
- src/app/admin/services/transcription-admin/transcription-admin.service.spec.ts
- src/app/admin/services/transcription-admin/transcription-admin.service.ts
[DMP-3100](https://tools.hmcts.net/jira/browse/DMP-3100)
[DMP-3101](https://tools.hmcts.net/jira/browse/DMP-3101)
Re-used transcript search form passing in a flag to swap case id and request id.
Temporary placeholder screen for view transcript document
> DMP-3100 & DMP-3101: Add search for completed transcript documents

- darts-api-stub/transcriptions/transcriptions.js
- src/app/portal/services/case/case.service.spec.ts
- src/app/portal/services/case/case.service.ts
- src/app/portal/services/transcription/transcription.service.spec.ts
- src/app/portal/services/transcription/transcription.service.ts
https://tools.hmcts.net/jira/browse/DMP-3133
'Approved' status now shows as 'With Transcriber' on the following screens:
- Your Transcripts
- Case Transcripts Tab
- Hearing Transcripts Tab
Mapped in the service layer
> DMP-3133: Map 'Approved' status to 'With Transcriber' in portal

- cypress/e2e/functional/admin-portal/hide-or-delete-file-spec.cy.js
- darts-api-stub/admin/medias/medias.js
- darts-api-stub/admin/transcriptions/transcription-documents.js
[DMP-3526](https://tools.hmcts.net/jira/browse/DMP-3526)
Calling reset endpoint to restore stub state after a functional tests have run to not impact any other tests dependent on the same stub data
`after(() => {
cy.request('api/admin/transcription-documents/reset');
cy.request('api/admin/medias/reset');
});`
> DMP-3526: Make functional tests idempotent: hide-or-delete-file-spec.cy.js

- cypress/e2e/functional/admin-portal/transformed-media-spec.cy.js
- src/app/admin/components/transformed-media/search-transformed-media-form/search-transformed-media-form.component.html
- src/app/admin/components/transformed-media/search-transformed-media-form/search-transformed-media-form.component.spec.ts
- src/app/admin/components/transformed-media/search-transformed-media-form/search-transformed-media-form.component.ts
- src/app/admin/components/transformed-media/search-transformed-media/search-transformed-media.component.html
- src/app/admin/components/transformed-media/search-transformed-media/search-transformed-media.component.spec.ts
- src/app/admin/components/transformed-media/search-transformed-media/search-transformed-media.component.ts
- src/app/admin/services/transformed-media/transformed-media.service.spec.ts
- src/app/admin/services/transformed-media/transformed-media.service.ts
[DMP-3563](https://tools.hmcts.net/jira/browse/DMP-3563)
- Add clearSearch() to the form / service
- Moved state into a signal based service instead of component props to enable form and results persistence when navigating to and from screen
- Covered with functional test
- Ignore branch name, wrong ticket ref
> DMP-3563: Transformed media search - Persist form state and search results

- src/app/core/components/common/courthouse/courthouse.component.ts
https://tools.hmcts.net/jira/browse/DMP-3590
Checked usage of courthouse and all looks to be referencing display name
> DMP-3590 - Courthouse autocomplete uses display name now

- src/app/admin/components/transcripts/transcripts.component.html
- src/app/admin/components/transcripts/transcripts.component.spec.ts
- src/app/admin/components/transcripts/transcripts.component.ts
N/A
Admin Portal > Transcript search has two tabs, one tab to search for "transcript requests" and one tab for "completed transcripts".
There is a bug where both searches were being triggered for both tabs causing a race condition and redirecting the user to the wrong place in the event of a single result. This PR addresses this.
> Fix transcript search bug

- src/app/admin/components/courthouses/create-courthouse/create-courthouse.component.ts
- src/app/admin/services/courthouses/courthouse.service.spec.ts
- src/app/admin/services/courthouses/courthouses.service.ts
- src/app/portal/components/search/search.component.spec.ts
- src/app/portal/components/search/search.component.ts
- src/app/portal/services/case/case.service.spec.ts
- src/app/portal/services/case/case.service.ts
https://tools.hmcts.net/jira/browse/DMP-3596
getCourhouses now returns cached result if available. Cache is cleared upon creating new courthouse to enable up to date results. 
Cleaned up older false positive tests in courthouse service spec
> DMP-3596 - Courthouse caching

- src/app/admin/services/transcription-admin/transcription-admin.service.ts
- src/app/admin/services/transformed-media/transformed-media.service.ts
Double checking delete transcript would work. Confirmed it would speaking to Chris B, deletion/hidden is driven by the reason_id passed into the payload. That flag/logic is therefore made in the BE.
No FE changes needed
Removed some TBD comments for hiding/deleting audio/transcript
> Remove TBD comments

- src/app/portal/services/transcription/transcription.service.ts
[DMP-3761](https://tools.hmcts.net/jira/browse/DMP-3761)
Remove update to unassiged transcript count on unassigned request call as the response contains max of 500 therefore throwing off the count every time the Transcript request page was visited.
> DMP-3761: Remove update to unassiged transcript count on unassigned request call

- darts-api-stub/annotations/annotations.js
- src/app/core/validators/max-file-size.validator.ts
- src/app/portal/components/hearing/add-annotation/add-annotation.component.html
- src/app/portal/components/hearing/add-annotation/add-annotation.component.spec.ts
- src/app/portal/components/hearing/add-annotation/add-annotation.component.ts
https://tools.hmcts.net/jira/browse/DMP-3745
- Mark control as touched on submit so that validation fires on submitting empty form.
- Disallow .zip file upload as backend returns error.
- Adjust allowed file size to 1000 x 1000 instead of 1024 x 1024.
> DMP-3745: Fix error messages on add annotation

- src/app/admin/components/courthouses/courthouse-search-results/courthouse-search-results.component.html
- src/app/admin/components/courthouses/create-courthouse/create-courthouse.component.ts
- src/app/admin/services/courthouses/courthouses.service.ts
[DMP-3596](https://tools.hmcts.net/jira/browse/DMP-3596)
- Move `clearCourthouseCache()` into the service as a side effect of creating or updating a courthouse.
- Use `routerLink` directive instead of href attribute. This was causing a hard refresh when clicking on a courthouse search result and therefore losing the cached state.
> DMP-2596: Fix courthouse cache and routerLink

- src/app/admin/components/transcripts/search-transcripts-form/search-transcripts-form.component.html
https://tools.hmcts.net/jira/browse/DMP-3823
Call signal getter `()` as `isCompletedTranscriptSearch` is always truthy as it's a signal
> DMP-3823: Fix missing Case ID field on transcript form bug

- src/app/portal/components/hearing/request-playback-audio/request-playback-audio.component.spec.ts
- src/app/portal/components/hearing/request-playback-audio/request-playback-audio.component.ts
https://tools.hmcts.net/jira/browse/DMP-3845
Audio request time validation has been changed now so that, if at least one audio exists within the time range, it is valid.
This means if there is audio for 09:30-11:00 and the user enters 07:00 - 09:45, then this is a valid request.
06:00 - 06:30 would be invalid, as would 10:00 - 10:30.
But 09:44 - 15:00 would be valid.
> DMP-3845 Audio time request validation change

- src/app/portal/components/audios/audio-view/audio-view.component.ts
[DMP-3789](https://tools.hmcts.net/jira/browse/DMP-3789)
`getCurrentNavigation()` works when navigated via the angular router. Hard refresh or deeplinking removes toISO and other Luxon DateTime prototype functions due to the way the state is serliased / deserialised.
The changes ensure that navigation must come from the Your Audio screen.
> DMP-3789: Fix view audio hard refresh / deep link bug

- cypress/e2e/functional/admin-portal/transcript-requests-spec.cy.js
- src/app/admin/components/transcripts/change-transcript-status/change-transcript-status.component.html
- src/app/admin/components/transcripts/change-transcript-status/change-transcript-status.component.ts
- src/app/admin/components/transcripts/search-transcripts-results/search-transcripts-results.component.html
- src/app/admin/components/transcripts/view-transcript/view-transcript.component.html
- src/app/admin/components/transcripts/view-transcript/view-transcript.component.spec.ts
- src/app/admin/components/transcripts/view-transcript/view-transcript.component.ts
- src/app/admin/components/users/user-transcripts/user-transcripts.component.html
- src/app/admin/components/users/user-transcripts/user-transcripts.component.ts
- src/app/core/components/app/app.component.spec.ts
- src/app/core/components/app/app.component.ts
- src/app/core/services/history/history.service.spec.ts
- src/app/core/services/history/history.service.ts
- src/app/core/utils/index.ts
- src/app/core/utils/transform.utils.ts
[DMP-3927](https://tools.hmcts.net/jira/browse/DMP-3927)
[DMP-3721](https://tools.hmcts.net/jira/browse/DMP-3721)
Implemented History Service to track back Urls.
When linking to a specific screen that requires back button functionality, a queryparam (backUrl) should be passed from source to the target route.
For example, the 'view transcript screen' can be reached from the 'user record screen' and from the 'transcript search screen'.
http://localhost:3000/admin/transcripts/1?backUrl=%2Fadmin%2Ftranscripts 
http://localhost:3000/admin/transcripts/7?backUrl=%2Fadmin%2Fusers%2F1 
The app component listens for any url changes containing a backUrl parameter and stores it in history service
> DMP-3927: Fix view transcript back link

- src/app/portal/components/hearing/request-transcript/request-times/request-times.component.html
Found as part of DMP-3921
fixing duplicate labels for start/end-hour-input on request-transcript screen. Labels exist already in time-input component.
> DMP-3921 fixing duplicate labels for start/end-hour-input

- src/app/core/components/common/details-table/details-table.component.html
Conditionally tracking by item.value in details table
- change aim to fix console warnings appearing on;
- http://localhost:3000/case/1/transcripts/1
- http://localhost:3000/case/1/hearing/1/transcripts/1
> fixes console warnings on multiple pages

- cypress/e2e/functional/admin-portal/transcript-requests-spec.cy.js
- darts-api-stub/admin/transcriptions/transcription-documents.js
- src/app/admin/components/audio-file/audio-file.component.html
- src/app/admin/components/audio-file/audio-file.component.spec.ts
- src/app/admin/components/audio-file/audio-file.component.ts
- src/app/admin/components/common/hidden-file-banner/hidden-file-banner.component.html
- src/app/admin/components/common/hidden-file-banner/hidden-file-banner.component.spec.ts
- src/app/admin/components/common/hidden-file-banner/hidden-file-banner.component.ts
- src/app/admin/components/transcripts/view-transcription-document/view-transcription-document.component.html
- src/app/admin/components/transcripts/view-transcription-document/view-transcription-document.component.spec.ts
- src/app/admin/components/transcripts/view-transcription-document/view-transcription-document.component.ts
- src/app/admin/models/common/hidden-file-banner.ts
https://tools.hmcts.net/jira/browse/DMP-4005
https://tools.hmcts.net/jira/browse/DMP-4006
Deletion banner logic changed so it looks at mapped reason.marked_for_deletion rather than is_marked_for_deletion against audio/transcript file
Renamed isMarkedForManualDeletion to isApprovedForManualDeletion for clearer meaning
> DMP-4005/6 - deletion banner logic change for audio/transcription

- cypress/e2e/functional/admin-portal/audio-file-details-spec.cy.js
- src/app/admin/components/common/hidden-file-banner/hidden-file-banner.component.html
- src/app/admin/components/common/hidden-file-banner/hidden-file-banner.component.spec.ts
User mapping for marked for deletion by in hidden file banner was being incorrectly mapped to marked for deletion by. Now this is changed to hidden by.
> DMP-4005 user mapping for deletion is now hidden by

- src/app/portal/components/case/case-file/case-events-table/case-events-table.component.html
- src/app/portal/components/case/case-file/case-hearings-table/case-hearings-table.component.html
Some dates had no prefix 0 on the date, standardised them across case file
> Case file - standardise date formats

- cypress/e2e/functional/admin-portal/search-spec.cy.js
- darts-api-stub/admin/events/events.js
- src/app/admin/components/events/advanced-event-details/advanced-event-details.component.html
- src/app/admin/components/events/advanced-event-details/advanced-event-details.component.spec.ts
- src/app/admin/components/events/view-event/view-event.component.spec.ts
- src/app/admin/facades/events/events-facade.service.spec.ts
- src/app/admin/models/events/event-data.interface.ts
- src/app/admin/models/events/event.ts
- src/app/admin/services/events/events.service.ts
[DMP-4084](https://tools.hmcts.net/jira/browse/DMP-4084)
Add 'Is current' to event advanced details
http://localhost:3000/admin/events/111
> DMP-4084: Add 'Is current' to event advanced details

- package.json
- server/server.ts
- yarn.lock
Express v4 to v5 migration
Path route matching syntax is when a string is supplied as the first parameter to the app.all(), app.use(), app.METHOD(), router.all(), router.METHOD(), and router.use() APIs. The following changes have been made to how the path string is matched to an incoming request:
The wildcard * must have a name, matching the behavior of parameters :, use /*splat instead of /*
https://expressjs.com/en/guide/migrating-5.html#path-syntax
> express v4 to v5, unnamed wildcard routes no longer allowed

- cypress/e2e/functional/admin-portal/event-details-spec.cy.js
- darts-api-stub/admin/events/events.js
- src/app/admin/admin.routes.ts
- src/app/admin/components/events/advanced-event-details/advanced-event-details.component.spec.ts
- src/app/admin/components/events/basic-event-details/basic-event-details.component.html
- src/app/admin/components/events/basic-event-details/basic-event-details.component.spec.ts
- src/app/admin/components/events/obfuscate-event-text/obfuscate-event-text.component.html
- src/app/admin/components/events/obfuscate-event-text/obfuscate-event-text.component.spec.ts
- src/app/admin/components/events/obfuscate-event-text/obfuscate-event-text.component.ts
- src/app/admin/components/events/view-event/view-event.component.html
- src/app/admin/components/events/view-event/view-event.component.scss
- src/app/admin/components/events/view-event/view-event.component.spec.ts
- src/app/admin/components/events/view-event/view-event.component.ts
- src/app/admin/facades/events/events-facade.service.spec.ts
- src/app/admin/facades/events/events-facade.service.ts
- src/app/admin/models/events/event.ts
- src/app/admin/services/events/events.service.spec.ts
- src/app/admin/services/events/events.service.ts
[DMP-3660](https://tools.hmcts.net/jira/browse/DMP-3660)
[DMP-3910](https://tools.hmcts.net/jira/browse/DMP-3910)
- Add **Obfuscate event text** button to event details screen
- Add success and warning banners
- Hide feature behind isManualDeletionEnabled() feature flag
- Add route protection to obfuscation screen based on feature flag
- Remove expired case banner
Note the `POST /admin/events/obfuscate` endpoint is still in progress
> DMP-3660 & DMP-3910 Add event text obfuscation flow

- src/app/admin/components/groups/group-record/group-record.component.html
- src/app/admin/components/groups/group-record/group-record.component.scss
- src/app/core/components/layout/footer/footer.component.html
[DMP-4096](https://tools.hmcts.net/jira/browse/DMP-4096)
[DMP-4149](https://tools.hmcts.net/jira/browse/DMP-4149)
- Remove `<h2 class="govuk-visually-hidden">Support links</h2>` from footer
- Update h3 tags on view group screen to h2
> DMP-4096 & 4149: Fix heading tags, remove h2 from footer

- server/controllers/auth.ts
- server/views/azuread-b2c-login.html
https://tools.hmcts.net/jira/browse/DMP-4229
B2C change
Previous change created baseUrl to be referenced in b2c template. This change reverts that and uses b2c hostname. This will be the correct long term config value to be used.
> DMP-4229 - remove baseUrl, add b2c hostname

- src/app/portal/components/audios/audio-view/audio-view.component.ts
[DMP-4121](https://tools.hmcts.net/jira/browse/DMP-4121)
- Add null check to endtime before parsing timestamp as a Luxon DateTime
> DMP-4121: Fix last playing event highlight in audio view

- .eslintrc.json
- cypress/e2e/functional/admin-portal/automated-tasks-spec.cy.js
- darts-api-stub/admin/automated-tasks/automated-tasks.js
- src/app/admin/components/automated-tasks/view-automated-tasks/view-automated-tasks.component.html
- src/app/admin/components/automated-tasks/view-automated-tasks/view-automated-tasks.component.spec.ts
- src/app/admin/components/automated-tasks/view-automated-tasks/view-automated-tasks.component.ts
- src/app/admin/components/system-configuration/system-configuration.component.html
- src/app/admin/components/system-configuration/system-configuration.component.spec.ts
- src/app/admin/components/system-configuration/system-configuration.component.ts
- src/app/admin/models/automated-task/automated-task.interface.ts
- src/app/admin/models/automated-task/automated-task.ts
- src/app/admin/services/automated-tasks/automated-tasks.service.ts
- src/app/core/components/common/details-table/details-table.component.ts
- src/app/core/components/common/tabs/tabs.component.ts
- src/app/core/directives/govuk-summary-list/govuk-summary-action.directive.spec.ts
- src/app/core/directives/govuk-summary-list/govuk-summary-action.directive.ts
- src/app/core/directives/govuk-summary-list/govuk-summary-key.directive.spec.ts
- src/app/core/directives/govuk-summary-list/govuk-summary-key.directive.ts
- src/app/core/directives/govuk-summary-list/govuk-summary-list-row.directive.spec.ts
- src/app/core/directives/govuk-summary-list/govuk-summary-list-row.directive.ts
- src/app/core/directives/govuk-summary-list/govuk-summary-list.directive.spec.ts
- src/app/core/directives/govuk-summary-list/govuk-summary-list.directive.ts
- src/app/core/directives/govuk-summary-list/govuk-summary-value.directive.spec.ts
- src/app/core/directives/govuk-summary-list/govuk-summary-value.directive.ts
- src/app/core/directives/govuk-summary-list/govuk-summary.directive.ts
- src/app/core/directives/govuk-summary-list/index.ts
- src/styles.scss
[DMP-3817](https://tools.hmcts.net/jira/browse/DMP-3817)
- Created some new directives to simplify and wrap the Gov uk summary list (https://design-system.service.gov.uk/components/summary-list/)
- Deprecated the details table in favour of the above approach when displaying this type of data as it's more maintainable and more accessible.
- Refactored the tab navigation in the SystemConfigurationComponent to work with the router instead of using the location API as it was causing some strange bugs.
- Conditionally shows ARM RPO attributes
- Updated tests
> DMP-3817 Show ARM RPO attributes for automated task

- .eslintrc.json
- src/app/admin/components/courthouses/courthouse-search-form/courthouse-search-form.component.spec.ts
- src/app/admin/components/courthouses/courthouse-search-form/courthouse-search-form.component.ts
- src/app/admin/components/courthouses/courthouses.component.html
- src/app/admin/components/courthouses/courthouses.component.ts
- src/app/admin/components/groups/groups.component.ts
- src/app/admin/components/users/user-search-form/user-search-form.component.spec.ts
- src/app/admin/components/users/user-search-form/user-search-form.component.ts
- src/app/admin/components/users/user-search-results/user-search-results.component.ts
- src/app/admin/components/users/users.component.html
- src/app/admin/components/users/users.component.spec.ts
- src/app/admin/components/users/users.component.ts
- src/app/core/services/form-state.service.spec.ts
- src/app/core/services/form-state.service.ts
[DMP-4209](https://tools.hmcts.net/jira/browse/DMP-4209)
Added new FormStateService to support persistence of form values
Form values and results are now persisted when returning to a previously used search form on:
- http://localhost:3000/admin/users
- http://localhost:3000/admin/groups
- http://localhost:3000/admin/courthouses
> DMP-4209: Add state persistence to user, group and courthouse admin search forms

- cypress/e2e/functional/admin-portal/audio-file-details-spec.cy.js
- darts-api-stub/admin/medias/medias.js
- src/app/admin/components/audio-file/advanced-audio-file-details/advanced-audio-file-details.component.html
- src/app/admin/models/transformed-media/audio-file-data.interface.ts
- src/app/admin/models/transformed-media/audio-file.ts
- src/app/admin/services/transformed-media/transformed-media.service.ts
https://tools.hmcts.net/jira/browse/DMP-4240
Can be safely merged before [DMP-4270](https://tools.hmcts.net/jira/browse/DMP-4270) (backend counterpart change) is implemented. If the property isn't in the response then it won't render anything.
> DMP-4240 Add 'Is current?' property to audio file details screen

- cypress/e2e/functional/admin-portal/automated-tasks-spec.cy.js
- darts-api-stub/admin/automated-tasks/automated-tasks.js
- src/app/admin/admin.routes.ts
- src/app/admin/components/automated-tasks/automated-task-status/automated-task-status.component.html
- src/app/admin/components/automated-tasks/automated-task-status/automated-task-status.component.spec.ts
- src/app/admin/components/automated-tasks/automated-task-status/automated-task-status.component.ts
- src/app/admin/components/automated-tasks/automated-tasks.component.html
- src/app/admin/components/automated-tasks/automated-tasks.component.spec.ts
- src/app/admin/components/automated-tasks/automated-tasks.component.ts
- src/app/admin/components/automated-tasks/run-automated-task/run-automated-task.component.html
- src/app/admin/components/automated-tasks/run-automated-task/run-automated-task.component.spec.ts
- src/app/admin/components/automated-tasks/run-automated-task/run-automated-task.component.ts
- src/app/admin/components/automated-tasks/view-automated-tasks/view-automated-tasks.component.html
- src/app/admin/components/automated-tasks/view-automated-tasks/view-automated-tasks.component.spec.ts
- src/app/admin/components/automated-tasks/view-automated-tasks/view-automated-tasks.component.ts
- src/app/admin/components/system-configuration/system-configuration.component.html
- src/app/admin/components/system-configuration/system-configuration.component.spec.ts
- src/app/admin/components/system-configuration/system-configuration.component.ts
- src/app/admin/models/automated-task/automated-task-status.ts
- src/app/admin/services/automated-tasks/automated-tasks.service.spec.ts
- src/app/admin/services/automated-tasks/automated-tasks.service.ts
[DMP-4217](https://tools.hmcts.net/jira/browse/DMP-4217)
Attempting to manually run an automated task presents user with a confirmation screen before sending the request on the following screens:
[/admin/system-configuration/automated-tasks](http://localhost:3000/admin/system-configuration/automated-tasks)
[/admin/system-configuration/automated-tasks/4](http://localhost:3000/admin/system-configuration/automated-tasks/4)
When the request completes the user is returned to where they came from.
> DMP-4217: Add confirmation screen when running an inactive automated task

- src/app/core/components/common/specific-or-range-date-picker/specific-or-range-date-picker.component.ts
[DMP-4321](https://tools.hmcts.net/jira/browse/DMP-4321)
Update logic to refresh the validity of the child controls in the date range form group resolving the bug described in the ticket.
> DMP-4321 Fix date range validation error messages

- config/default.json
- src/app/core/interceptors/error/error.interceptor.ts
[DMP-4261](https://tools.hmcts.net/jira/browse/DMP-4261)
Fix brief redirection to 'There is a problem with this service' screen and go directly to the login screen upon session expiry.
Session ttl reduced to 5 seconds to allow testing, must be reverted to 8 hours before merging
> DMP-4261 Expire user session gracefully

- cypress/e2e/functional/your-audio-spec.cy.js
- src/app/portal/components/audios/audios.component.html
- src/app/portal/components/audios/audios.component.spec.ts
- src/app/portal/components/audios/audios.component.ts
https://tools.hmcts.net/jira/browse/DMP-4197
Added active tab service to Your Audio component to ensure relevant tab is returned after performing action, e.g. deleting audio from expired audio table.
> DMP-4197 Your audio tab active tab service change

- cypress/e2e/functional/admin-portal/case-file-spec.cy.js
- src/app/core/services/active-tab/active-tab.service.spec.ts
- src/app/core/services/active-tab/active-tab.service.ts
- src/app/portal/components/case/case-file/case-hearings-table/case-hearings-table.component.html
- src/app/portal/components/case/case-file/case-hearings-table/case-hearings-table.component.spec.ts
- src/app/portal/components/case/case-file/case-hearings-table/case-hearings-table.component.ts
- src/app/portal/components/hearing/hearing.component.ts
https://tools.hmcts.net/jira/browse/DMP-4964
Saved tabs for admin & portal hearing screens are cleared when entering them from hearing results list
> DMP-4964 Clear saved tab when clicking into hearing details

- src/app/admin/components/transcripts/view-transcription-document/transcript-file-advanced-detail/transcript-file-advanced-detail.component.ts
>[Jira](https://tools.hmcts.net/jira/browse/DMP-4951)
This Git Diff showcases modifications made to the `transcript-file-advanced-detail.component.ts` file. The primary change involves the handling of date formatting for various document properties, ensuring that if the transformation returns `null`, an empty string is returned instead.
- Updated the formatting of the 'Date uploaded' field to return an empty string if the date transformation is `null`.
- Updated the formatting of the 'Date last modified' field similarly, handling potential `null` values.
- Enhanced the 'Date hidden' field to return an empty string if the date transformation is `null`.
- Adjusted the 'Retain until' field to also return an empty string for `null` values in date transformation.
**Does this PR introduce a …
> DMP-4951: Admin Transciptions Advanced Details tab shows null

- src/app/admin/components/transcripts/view-transcript/transcript-details/transcript-details.component.ts
- src/app/portal/services/transcription/transcription.service.spec.ts
- src/app/portal/services/transcription/transcription.service.ts
https://tools.hmcts.net/jira/browse/DMP-5027
Admin transcript screen utilises new govuk summary directive, so old mapping function is not required in this component at all. Mapping function used by portal components updated to reference only portal case link.
> DMP-5027 removed admin reference from transcript case link

- config/custom-environment-variables.json
- config/default.json
- cypress/e2e/functional/case-file-spec.cy.js
- darts-api-stub/cases/case.js
- server/app-config.ts
- src/app/core/components/common/data-table/data-table.component.html
- src/app/core/components/common/data-table/data-table.component.spec.ts
- src/app/core/components/common/data-table/data-table.component.ts
- src/app/core/services/app-config/app-config.service.spec.ts
- src/app/core/services/app-config/app-config.service.ts
- src/app/core/services/dynatrace/dynatrace.service.spec.ts
- src/app/portal/components/case/case-file/case-events-table/case-events-table.component.html
- src/app/portal/components/case/case-file/case-events-table/case-events-table.component.spec.ts
- src/app/portal/components/case/case-file/case-events-table/case-events-table.component.ts
- src/app/portal/components/case/case.component.html
- src/app/portal/components/case/case.component.spec.ts
- src/app/portal/components/case/case.component.ts
- src/app/portal/models/events/case-event.ts
- src/app/portal/models/events/paginated-case-events.interface.ts
- src/app/portal/models/events/paginated-case-events.type.ts
- src/app/portal/services/case/case.service.spec.ts
- src/app/portal/services/case/case.service.ts
https://tools.hmcts.net/jira/browse/DMP-4955
New pagination.courtLogEventsPageLimit configurable value set via PAGINATION_COURTLOG_EVENTS_LIMIT env var. Default value is 500.
Now using query params for pagination on case events
> DMP-4955 Added pagination for court log events

- src/app/admin/facades/transcript/transcript-facade.service.spec.ts
- src/app/admin/facades/transcript/transcript-facade.service.ts
- src/app/admin/models/transcription/transcription-workflow.ts
- src/app/core/components/common/timeline/timeline.component.html
- src/app/core/components/common/timeline/timeline.component.spec.ts
>[Jira](https://tools.hmcts.net/jira/browse/DMP-4960)
This Git Diff introduces new test cases in the `transcript-facade.service.spec.ts` file to validate the behavior of the `TranscriptFacadeService` when handling comments in transcription workflows. The service now accommodates workflows without a status ID and maps comments to a timeline correctly, both for single and multiple comments.
- **New Test Cases**:
- Added a test to verify that comments are correctly mapped to the timeline when the workflow status is not present.
- Another test ensures correct mapping of multiple comments to the timeline without a status.
- **Service Modifications**:
- Updated `TranscriptFacadeService` to handle workflows with optional `statusId`.
- Improved the `getHistory` method to filter and map workflows …
> DMP-4960: Empty author on transcription comment should not display System user

- src/app/admin/components/transcripts/search-completed-transcripts-results/search-completed-transcripts-results.component.html
- src/app/admin/components/transcripts/search-completed-transcripts-results/search-completed-transcripts-results.component.ts
- src/app/admin/components/transcripts/search-transcripts-results/search-transcripts-results.component.html
- src/app/admin/components/transcripts/transcripts.component.html
- src/app/admin/models/transcription/transcription-document-search-result.ts
N/A
A client-side error was occurring if the `hearing` object on the transcription-documents search response was empty.
Other miscellaneous tweaks
* Updating table captions to be clearer
* Don't show results table when loading results
> Handle empty hearing on admin portal transcript documents search

- src/app/admin/components/courthouses/courthouse-record/courthouse-record.component.spec.ts
- src/app/admin/components/users/user-groups/assign-groups/assign-groups.component.spec.ts
- src/app/admin/components/users/user-groups/remove-groups/remove-groups.component.spec.ts
- src/app/admin/components/users/user-groups/user-groups/user-groups.component.spec.ts
- src/app/admin/components/users/user-record/user-record.component.spec.ts
- src/app/admin/models/users/user-data.interface.ts
- src/app/admin/models/users/user.type.ts
- src/app/admin/services/user-admin/user-admin.service.spec.ts
- src/app/admin/services/user-admin/user-admin.service.ts
>[Jira](https://tools.hmcts.net/jira/browse/DMP-5042)
This Git diff introduces changes to the user management functionality within an application by updating interfaces, types, and service methods. The primary modification is the addition of a new property, `is_system_user`, which allows for more granular control over user data. The changes also include adjustments to unit tests to account for this new property, ensuring that both system and non-system users are properly handled in various scenarios.
- **Interface Updates**:
- `UserData` interface now includes an optional property `is_system_user`.
- `User` type now requires the property `isSystemUser`.
- **Service Method Changes**:
- `getUsers`, `searchUsers`, and `getUsersById` methods updated to accept an `allowSystemUsers` boolean …
> DMP-5042: (Dev only) Ignore system users in user endpoints

- package.json
- renovate.json
- yarn.lock
Reverts hmcts/darts-portal#2054 and tells renovate to ignore updates to the `@ministryofjustice/frontend` package
> Revert "Update dependency @ministryofjustice/frontend to v4.0.2"

- charts/darts-portal/Chart.yaml
- charts/darts-portal/values.yaml
- server/index.ts
https://tools.hmcts.net/jira/browse/DMP-5135
Prevent active connections being added to darts-portal pods scheduled for shut down
> DMP-5135 increase stop server timeout from 20s to 60s
