hmcts/darts-portal

- Jenkinsfile_CNP
- Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/DMP-37
initial jenkinsfiles for darts-portal
```
[ ] Yes
[x] No
```
> initial pipeline template for angular frontend

- charts/darts-portal/Chart.yaml
- to trigger updates to environments
```
[ ] Yes
[ ] No
```
> Helm chart version bump

- Dockerfile
- package.json
- adding some helpful yarn scripts for docker
```
[ ] Yes
[ ] No
```
> Using HMCTS base for docker build

- angular.json
- karma.conf.js
- package.json
- server/controllers/api.ts
- sonar-project.properties
- it needs "lcov" report
```
[ ] Yes
[ ] No
```
> [DMP-75] Fixing code coverage for sonarcloud

- server/controllers/auth.ts
- server/views/azuread-login.html
N/A
Updated after reading: https://learn.microsoft.com/en-us/azure/active-directory-b2c/customize-ui-with-html?pivots=b2c-user-flow#custom-html-page-content
```
[ ] Yes
[x] No
```
> Fixing up HTML as expected by Azure AD

- charts/darts-portal/Chart.yaml
- charts/darts-portal/values.yaml
- config/custom-environment-variables.json
- config/default.json
- server/controllers/auth.ts
- server/views/azuread-login.html
> POC azure ad login2

- .yarn/sdks/eslint/package.json
- .yarn/sdks/prettier/package.json
- .yarn/sdks/typescript/lib/tsserver.js
- .yarn/sdks/typescript/lib/tsserverlibrary.js
> yarn-PnP fix (fixes imports and tslib issue)

- server/controllers/api.ts
- server/controllers/authentication.ts
- server/routes.ts
https://tools.hmcts.net/jira/browse/DMP-430
- only setting the content-type header
- other headers copied in from the request were causing issues
- fixing disable auth for API proxy
```
[ ] Yes
[ ] No
```
> DMP-430 Fixing auth callback request to DARTS API

- charts/darts-portal/Chart.yaml
- charts/darts-portal/values.dev.template.yaml
- charts/darts-portal/values.stg.template.yaml
- charts/darts-portal/values.yaml
- config/custom-environment-variables.json
- config/default.json
- package.json
- server/controllers/auth.ts
- server/views/azuread-b2c-login.html
N/A
- copy assets into dist directory on build
- adding portal hostname to config
- using hostname from config for absolute asset paths in login page
```
[ ] Yes
[X] No
```
> Fixes for Azure AD B2C login page template

- charts/darts-portal/Chart.yaml
- charts/darts-portal/values.dev.template.yaml
- charts/darts-portal/values.stg.template.yaml
- charts/darts-portal/values.yaml
- config/custom-environment-variables.json
N/A
See title
```
[ ] Yes
[X] No
```
> DARTS_PORTAL_HOSTNAME -> DARTS_PORTAL_URL

- server/server.ts
N/A
As per title
```
[ ] Yes
[X] No
```
> Setting CORS headers on Azure AD B2C login pages

- .pnp.cjs
- Dockerfile
- angular.json
- package.json
- server/controllers/authentication.ts
- src/app/services/auth/auth.service.ts
- yarn-audit-known-issues
- yarn.lock
N/A
- this is to prevent caching at the Azure front door level
- using session save callback to ensure session is set correctly
- fixing `yarn start` so it works locally
```
[ ] Yes
[x] No
```
> Adding timestamp to angular session check

- src/app/auth/auth.guard.ts
- src/app/components/home/home.component.ts
https://tools.hmcts.net/jira/browse/DMP-433
Unauthenticated to authenticated route preservation and redirect. e.g. if a user attempts to access a route that requires authentication but makes a subsequent successful authentication then they should be redirected to the previous page that they were attempting to access while unauthenticated post login.
```
[ ] Yes
[x] No
```
> DMP-433 unauthenticated route preservation and redirect after successful authentication

- server/views/azuread-b2c-login.html
> Dmp 361 external login page

- Jenkinsfile_parameterized
> Adding Jenkinsfile_parameterized, for deploy to sandbox

- Jenkinsfile_CNP
- server/server.ts
> Adding more logs to debug session issue

- server/views/azuread-b2c-login.html
Repositioning Azure elements.
```
[ ] Yes
[X] No
```
> Dmp 361 ext sign in

- server/views/azuread-b2c-login.html
Footer fix & password link repositioning
```
[ ] Yes
[x] No
```
> DMP361 : feature : footer fix & positioning

- darts-api-stub/authentication/external.js
- darts-api-stub/views/external-logout.ejs
- server/controllers/api.ts
- server/controllers/authentication.ts
- src/app/components/layout/header/header.component.html
- src/app/components/layout/header/header.component.spec.ts
- src/app/components/layout/header/header.component.ts
- src/app/services/auth/auth.service.spec.ts
- src/app/services/auth/auth.service.ts
https://tools.hmcts.net/jira/browse/DMP-490
Adding logout routes
Adding logout to the DARTS API stub
```
[ ] Yes
[x] No
```
> DMP-490 Logout

- server/views/azuread-b2c-login.html
Changing the target ID of the email text field to resolve a styling conflict.
```
[ ] Yes
[x] No
```
> patch : correcting css ID conflict

- server/views/azuread-b2c-login.html
> Removing embedded Javascript

- .prettierignore
- server/views/azuread-b2c-login.html
> Removing more embedded Javascript

- server/assets/stylesheets/reset-password.css
https://tools.hmcts.net/jira/browse/DMP-493
Added padding to footer
```
[ ] Yes
[x] No
```
> DMP-493 styling fixes

- src/app/components/login/login.component.html
- src/app/components/login/login.component.spec.ts
- src/app/components/login/login.component.ts
https://tools.hmcts.net/jira/browse/DMP-552
Added Error Summary and Message
```
[ ] Yes
[x] No
```
> Error message and summary added

- server/assets/javascripts/reset-password.js
- server/assets/stylesheets/reset-password.css
https://tools.hmcts.net/jira/browse/DMP-494
Removed console.log statements, hidden email address text and changed link colour to blue
```
[ ] Yes
[x] No
```
> DMP-494-Forgotton-Password-Verify-Code

- server/assets/javascripts/reset-password.js
https://tools.hmcts.net/jira/browse/DMP-493
Removal of email address text in placeholder
```
[ ] Yes
[x] No
```
> DMP-493-Forgotten-Password-Request-Code

- server/assets/javascripts/reset-password.js
- server/assets/stylesheets/reset-password.css
https://tools.hmcts.net/jira/browse/DMP-585
- adding styling for continue and change email buttons
- adding JS to hook into verify code XHR request and carry out DOM updates
```
[ ] Yes
[x] No
```
> DMP-585 Password reset flow - code accepted screen

- server/assets/javascripts/reset-password.js
https://tools.hmcts.net/jira/browse/DMP-494
removal of asterisk and placeholder in input box
```
[ ] Yes
[x] No
```
> DMP-494-Forgotten-Password-Verify-Code

- server/assets/javascripts/reset-password.js
- server/assets/stylesheets/reset-password.css
https://tools.hmcts.net/jira/browse/DMP-585
- continue button size
- handle "Use a different account" button click event to reverse changes made when verify code is successful
```
[ ] Yes
[x] No
```
> DMP-585 Password reset flow - code accepted screen fixes

- server/assets/javascripts/reset-password.js
- server/assets/stylesheets/reset-password.css
- re-positioning after text change
- handling smaller screens
https://tools.hmcts.net/jira/browse/DMP-585
```
[ ] Yes
[x] No
```
> DMP-585 Password reset flow - code accepted more change account fixes

- server/assets/javascripts/search.js
- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/components/search/search.component.html
- src/app/components/search/search.component.spec.ts
- src/app/components/search/search.component.ts
This implements the simple search page (https://tools.hmcts.net/jira/browse/DMP-507)
```
[ ] Yes
[x] No
```
> Dmp 507 simple case search

- server/assets/javascripts/reset-password.js
https://tools.hmcts.net/jira/browse/DMP-585
Changing when tab order function is called
```
[ ] Yes
[x] No
```
> DMP-585-Code-Accepted

- server/assets/javascripts/search.js
- src/app/app.module.ts
- src/app/components/search/search.component.html
- src/app/components/search/search.component.spec.ts
- src/app/components/search/search.component.ts
- Added clear text-box logic into appropriate Angular files
- Created passing unit test
```
[ ] Yes
[ x ] No
```
> Dmp 507 search cases

- README.md
> dummy Update README.md

- server/assets/javascripts/login.js
- server/views/azuread-b2c-login.html
https://tools.hmcts.net/jira/browse/DMP-541
- error styling added
- fixing wrapXhrOpen function call
```
[ ] Yes
[x] No
```
> DMP-541 External sign-in errors fixes

- server/views/azuread-b2c-login.html
https://tools.hmcts.net/jira/browse/DMP-541
As title
```
[ ] Yes
[x] No
```
> DMP-541 Fixing item level error message styling for external login page

- server/assets/javascripts/login.js
N/A
As per title
```
[ ] Yes
[x] No
```
> Trying to fix the wrapXhrOpen call in the external login page

- server/assets/stylesheets/login.css
- server/views/azuread-b2c-login.html
- The 'forgotten password' link is now in the correct place (this will only show correctly via the actual Azure API)
- The checkbox 'double' box issue has been addressed
- The checkbox label is centred
- Tabbing through the page elements now occurs in correct sequential order
```
[ ] Yes
[ X ] No
```
> Dmp 590 qa comments

- server/assets/stylesheets/login.css
- server/views/azuread-b2c-login.html
https://tools.hmcts.net/jira/browse/DMP-363
- ensure item level errors messages are color red
- minor tweak to box-shadows for the checkbox
```
[ ] Yes
[x] No
```
> DMP-363 Styling tweaks for external login page

- src/app/components/search/results/results.component.html
- src/app/components/search/results/results.component.scss
https://tools.hmcts.net/jira/browse/DMP-804
> DMP-804: Display reporting restriction to case search results

- darts-api-stub/case/case.js
- src/app/components/search/results/results.component.html
- src/app/components/search/results/results.component.spec.ts
- src/app/types/case.d.ts
Type updates in frontend for case data and dev stubs. Specifically against case id, case number, reporting restrictions to go from camel to snake case.
```
[ ] Yes
[X ] No
```
> camel to snake changes in stub, front end refs, types

- src/app/components/search/results/results.component.html
- src/app/components/search/search.component.html
https://tools.hmcts.net/jira/browse/DMP-891
> DMP-891: Text change 'Case number' to 'Case ID'

- darts-api-stub/hearings/hearings.js
- darts-api-stub/index.js
- src/app/services/hearing/hearing.service.ts
https://tools.hmcts.net/jira/browse/DMP-880
Updated to new endpoint in API
```
[ ] Yes
[X] No
```
> DMP 880 updated url and stubbed

- src/app/components/search/search.component.ts
[DMP-1016](https://tools.hmcts.net/jira/browse/DMP-1016)
> DMP-1016: Clear errors from search results on clear search

- src/app/components/search/results/results.component.spec.ts
- src/app/components/search/results/results.component.ts
[DMP-1026](https://tools.hmcts.net/jira/browse/DMP-1026)
> DMP-1026: Reset column sort on new search

- src/styles.scss
https://tools.hmcts.net/jira/browse/DMP-1032
Addition of hover/mouseover styles for back link and links.
```
[ ] Yes
[x] No
```
> DMP-1032-link-mouseover/hover-styles

- server/assets/javascripts/accessibility.js
- server/assets/javascripts/login.js
- server/views/azuread-b2c-login.html
DMP-995/999/1000/1001 
Accessibility changes for external login
```
[ ] Yes
[X ] No
```
> DMP-995/999/1000/1001 - accessibility changes

- src/app/components/hearing/hearing.component.html
- src/app/components/hearing/hearing.component.spec.ts
- src/app/components/hearing/hearing.component.ts
- src/app/components/hearing/order-confirmation/order-confirmation.component.html
- src/app/components/hearing/order-confirmation/order-confirmation.component.ts
- src/app/services/hearing/hearing.service.ts
https://tools.hmcts.net/jira/browse/DMP-1055
- Email Address changed from static to dynamic value
```
[ ] Yes
[x] No
```
> DMP-1055-Email address for order confirmation screen

- src/app/components/login/login.component.html
DMP-992
```
[ ] Yes
[x ] No
```
> DMP-992 added roles to radio labels login page

- src/app/components/search/search.component.html
> DMP-1015 Case search aria-label datepicker 

- src/app/components/case/case.component.html
New breadcrumbs for case file screen
- [No ] Does this PR introduce a breaking change
> DMP-997 breadcrumb for case file

- src/app/components/case/case.component.html
- src/app/components/case/case.component.scss
Small css change to remove gap above breadcrumb
> DMP-997 Breadcrumbs case file

- darts-api-stub/cases/case.js
- src/app/components/case/hearing-results/hearing-results.component.ts
- src/app/components/common/data-table/data-table.component.spec.ts
- src/app/components/common/data-table/data-table.component.ts
Column sorting for numbers, dates, array on data table
- [x ] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [x ] tests have been updated / new tests has been added (if needed)
- [ x] Does this PR introduce a breaking change
> DMP-965 sorting for numbers, dates, array on data table

- src/app/components/hearing/hearing.component.html
- src/app/components/hearing/order-confirmation/order-confirmation.component.ts
- src/app/components/hearing/request-playback-audio/request-playback-audio.component.spec.ts
- src/app/components/hearing/request-playback-audio/request-playback-audio.component.ts
[N/A](https://tools.hmcts.net/jira/browse/DMP-1094)
Fixing audio request "requestor" field
> DMP-1094 Setting audio request userID

- src/app/app.routes.spec.ts
- src/app/components/hearing/hearing.component.spec.ts
- src/app/services/user/user.service.spec.ts
- src/app/services/user/user.service.ts
Migrate user service from promises to observables
> Observable User Service

- src/app/components/search/search.component.html
- src/app/components/search/search.component.spec.ts
https://tools.hmcts.net/jira/browse/DMP-1204
Linking date input labels to the input fields for automation testing
> DMP-1204-Date-Fields-Labels

- src/app/components/hearing/request-playback-audio/time-input/time-input.component.html
https://tools.hmcts.net/jira/browse/DMP-1210
- Matching labels to correct Ids for time inputs for automation testing
> DMP-1210-Time-Input-Labels

- src/app/components/audios/audios.component.html
- src/app/components/common/audio-player/audio-player.component.html
- src/app/components/common/audio-player/audio-player.component.scss
- src/app/components/common/data-table/data-table.component.html
- src/app/components/common/data-table/data-table.component.scss
- src/app/components/common/data-table/data-table.component.spec.ts
- src/app/components/common/data-table/data-table.component.ts
- src/app/components/hearing/events-and-audio/events-and-audio.component.html
- src/app/components/hearing/events-and-audio/events-and-audio.component.scss
- src/app/components/hearing/events-and-audio/events-and-audio.component.spec.ts
- src/app/components/hearing/events-and-audio/events-and-audio.component.ts
- src/app/components/hearing/hearing.component.spec.ts
- src/app/components/hearing/hearing.component.ts
- src/app/types/hearing-audio-event.interface.ts
https://tools.hmcts.net/jira/browse/DMP-966
> DMP-966: Update events and audio table

- server/views/azuread-b2c-login.html
https://tools.hmcts.net/jira/browse/DMP-621
Changed the URL on the external login page to internal login page
> DMP-621-External-To-Internal-Link

- src/app/components/hearing/request-playback-audio/request-playback-audio.component.html
https://tools.hmcts.net/jira/browse/DMP-1242
- removed pattern error message from request playback audio input box
> DMP-1242-Removed-Pattern-Error-Message

- charts/darts-portal/Chart.yaml
N/A
Upgrading to use Workload Identity
> Upgrading node.js helm chart to v3.0.0

- src/app/components/search/search.component.html
- src/app/components/search/search.component.ts
https://tools.hmcts.net/jira/browse/DMP-781
Loading spinner for case search
> DMP-781-Search-Results-Loading

- Jenkinsfile_CNP
N/A
To help with debugging, as requested by platops
> Adding disableCleanupOfHelmReleaseOnFailure() to jenkinsfile

- charts/darts-portal/Chart.yaml
- charts/darts-portal/values.yaml
- config/default.json
- server/middleware/session.ts
https://tools.hmcts.net/jira/browse/DMP-434
Small change to add config reference for express middleware secret
- [ X] commit messages are meaningful and follow good commit message guidelines
- [ X] README and other documentation has been updated / added (if needed)
- [ X] tests have been updated / new tests has been added (if needed)
- [X ] Does this PR introduce a breaking change
> DMP-434 kv secret reference for express middleware

- server/assets/javascripts/errors.js
- server/assets/javascripts/login.js
- server/assets/javascripts/reset-password.js
https://tools.hmcts.net/jira/browse/DMP-681
Attempt to style azure b2c password reset errors
- [ X] commit messages are meaningful and follow good commit message guidelines
- [ X] README and other documentation has been updated / added (if needed)
- [ X] tests have been updated / new tests has been added (if needed)
- [ X] Does this PR introduce a breaking change
> DMP-681 Password reset errors on b2c pages

- server/assets/javascripts/errors.js
- server/assets/javascripts/login.js
- server/assets/javascripts/reset-password.js
- server/assets/stylesheets/reset-password.css
Remove duplicate errors, attempt to reset errors on new code request, css styling
DMP-681
> DMP-681 B2C Styling for verification code 

- server/assets/javascripts/change-password.js
- server/assets/javascripts/errors.js
- server/assets/stylesheets/change-password.css
https://tools.hmcts.net/jira/browse/DMP-550
Handling field validation for the change password screen.
> DMP-550 reset password new password validation

- server/assets/javascripts/errors.js
- server/assets/javascripts/login.js
- server/assets/javascripts/reset-password.js
- server/assets/stylesheets/reset-password.css
Removes errors on successful verification, append to existing summary box if exists, used for 'required' message. New click event for verify button
> DMP-681 b2c errors reset password

- src/app/components/hearing/hearing.component.ts
N/A
Fix console error relating to fieldId.
> fix fieldId console error

- server/assets/javascripts/reset-password.js
Added darts-error to parent when required on verify click, passes in array if multiple show errors for gov error summary
DMP-681
- [X ] commit messages are meaningful and follow good commit message guidelines
- [ X] README and other documentation has been updated / added (if needed)
- [ X] tests have been updated / new tests has been added (if needed)
- [ X] Does this PR introduce a breaking change
> DMP-681 B2C Verification code error formatting reset pwd

- server/assets/stylesheets/change-password.css
- fix for multiple error messages
https://tools.hmcts.net/jira/browse/DMP-550
CSS fix for change password validation summary
> DMP-550 B2C change password validation error summary

- server/assets/javascripts/reset-password.js
- server/assets/stylesheets/change-password.css
- server/assets/stylesheets/reset-password.css
DMP-681
CSS Styling for govuk list
Remove errors before populating summary on non-requests to avoid duplicates
> DMP-681 Reset & Change pwd css styling for errors

- server/controllers/api.ts
> Adding some logs to API proxy

- server/controllers/api.ts
- server/routes.ts
- src/app/components/hearing/events-and-audio/events-and-audio.component.html
N/A
Stuff for testing/debugging audio streaming issue, to be removed later.
> Adding bits for testing audio streaming issue

- server/routes.ts
> Amending logging for test audio API request

- server/assets/javascripts/errors.js
- server/assets/javascripts/reset-password.js
DMP-1245
Added set timeout to allow DOM updates before running item level error functions. Input event fires before dom has updated.
> DMP-1245 B2C Email error formatting

- cypress/e2e/functional/your-audio-spec.cy.js
- darts-api-stub/audios/audios.js
- src/app/components/app.component.spec.ts
- src/app/components/app.component.ts
- src/app/components/audios/audio-delete/audio-delete.component.spec.ts
- src/app/components/audios/audio-delete/audio-delete.component.ts
- src/app/components/audios/audios.component.html
- src/app/components/audios/audios.component.ts
- src/app/components/hearing/hearing.component.html
- src/app/components/hearing/hearing.component.scss
- src/app/components/hearing/hearing.component.spec.ts
- src/app/components/hearing/hearing.component.ts
- src/app/components/hearing/order-confirmation/order-confirmation.component.spec.ts
- src/app/components/hearing/order-confirmation/order-confirmation.component.ts
- src/app/services/header/header.service.ts
[DMP-1114](https://tools.hmcts.net/jira/browse/DMP-1114)
- Add clear link for failed 'in-progress' requests. This uses the same pattern for deleting other requests.
- Move nav show / hide logic into delete component
- Refactor `showPrimaryNavigation(boolean)` to `showNavigation()` and `hideNavigation()`
- Add FT
> DMP-1114: Clear failed audio request

- src/app/components/audios/audio-view/audio-view.component.html
- src/app/components/case/case.component.html
- src/app/components/hearing/hearing.component.html
Fix nested `<a>` tag in breadcrumb component
> Fix breadcrumb markup

- Jenkinsfile_CNP
N/A
Removing redundant parts which might speed up the build slightly.
> Removing some unnecessary commands from the Jenkinsfile

- server/controllers/authentication.ts
N/A
Amending this to not redirect as it's causing issues with the audio stream testing
> Auth bootstrap - Do not redirect

- cypress/e2e/functional/hearing-transcripts-spec.cy.js
- darts-api-stub/hearings/hearings.js
- src/app/components/case/case.component.ts
- src/app/components/hearing/events-and-audio/events-and-audio.component.ts
- src/app/components/hearing/hearing.component.html
- src/app/components/hearing/hearing.component.scss
- src/app/components/hearing/hearing.component.spec.ts
- src/app/components/hearing/hearing.component.ts
- src/app/services/case/case.service.spec.ts
- src/app/services/case/case.service.ts
- src/app/services/mapping/mapping.service.spec.ts
- src/app/services/mapping/mapping.service.ts
https://tools.hmcts.net/jira/browse/DMP-862
- Added transcripts at the hearing level
- Tab for transcripts section in a hearing
- Added request a new transcript button
> DMP-862-Hearings-Transcript-Tab

- config/custom-environment-variables.json
- config/default.json
- server/middleware/session.ts
- src/app/components/hearing/events-and-audio/events-and-audio.component.ts
- src/app/components/hearing/hearing.component.html
- src/app/components/hearing/hearing.component.spec.ts
- src/app/directives/breadcrumb.directive.ts
- src/app/services/audio-request/audio-request.service.spec.ts
N/A
Adding session TTL for redis
- the session was living for 24 hours in redis and they were building up
- now set to 20 mins
A few lint fixes
> Session TTL

- src/app/components/common/data-table/data-table.component.html
https://tools.hmcts.net/jira/browse/DMP-1468
Using a `td`, as recommended, if the column header is empty text.
> DM-1468 Fixing accessibility issue with empty table headers

- config/custom-environment-variables.json
- config/default.json
- cypress/e2e/functional/case-file-spec.cy.js
- darts-api-stub/cases/case.js
- server/app-config.ts
- src/app/components/audios/audio-view/audio-view.component.spec.ts
- src/app/components/audios/audio-view/audio-view.component.ts
- src/app/components/case/case.component.html
- src/app/components/case/case.component.ts
- src/app/components/common/forbidden/forbidden.component.html
- src/app/components/common/forbidden/forbidden.component.spec.ts
- src/app/components/common/forbidden/forbidden.component.ts
- src/app/components/error/internal-server/internal-error.component.html
- src/app/components/error/internal-server/internal-error.component.spec.ts
- src/app/components/error/internal-server/internal-error.component.ts
- src/app/components/search/search-error/search-error.component.spec.ts
- src/app/components/search/search.component.spec.ts
- src/app/services/app-config/app-config.service.spec.ts
- src/app/services/app-config/app-config.service.ts
https://tools.hmcts.net/jira/browse/DMP-1486
Adding the forbidden component.
Adding a loading state to the case file screen
Handling case load errors, including 400, 403 and 404
> DMP-1486 Case loading and 403 error

- src/app/components/layout/header/header.component.html
- src/app/components/layout/header/header.component.spec.ts
https://tools.hmcts.net/jira/browse/DMP-1513
- adding visually hidden text to give context to the count
> DMP-1513 Fixing accessibility issue with "Your audio" count

- src/app/components/hearing/request-transcript/request-times/request-times.component.html
- src/app/components/hearing/request-transcript/request-transcript-confirmation/request-transcript-confirmation.component.html
https://tools.hmcts.net/jira/browse/DMP-1528
- adding `href` attribute to ensure they are included in the tab ordering
> DMP-1528 Fixing tab order issue with request transcription cancel buttons

- config/custom-environment-variables.json
- config/default.json
- config/development.json
- server/controllers/api.ts
- server/middleware/session.ts
- server/routes.ts
- src/app/components/hearing/events-and-audio/events-and-audio.component.html
N/A
Removing all the rubbish I added for testing/debugging the audio streaming issue.
> Removing audio streaming testing changes

- src/app/components/audios/audio-view/audio-view.component.html
- src/app/components/audios/audio-view/audio-view.component.ts
- src/app/components/hearing/hearing.component.html
- src/app/components/hearing/hearing.component.ts
- src/app/components/login/login.component.html
- src/app/components/login/login.component.ts
- src/app/components/search/search.component.html
- src/app/components/search/search.component.ts
[DMP-1440](https://tools.hmcts.net/jira/browse/DMP-1440)
Replace individual errors with validation-error-summary component
> Portal - Validation Error Summary Component

- src/app/components/hearing/request-transcript/request-times/request-times.component.html
- src/app/components/hearing/request-transcript/request-transcript.component.html
https://tools.hmcts.net/jira/browse/DMP-1545
Set paging limit to 15 instead of 10 as per original ticket AC (https://tools.hmcts.net/jira/browse/DMP-917)
> DMP-1545: Set paging limit to 15 for request transcript journey

- src/app/components/hearing/request-transcript/request-transcript.component.html
[DMP-872](https://tools.hmcts.net/jira/browse/DMP-872)
If audio is not available for the hearing, when selecting **Request a new transcript** user is navigated to a screen informing them that there is no audio available and they are not able to request the transcript
> DMP-872 - No audio available for transcript request

- cypress/e2e/functional/request-transcript-spec.cy.js
- darts-api-stub/transcriptions/transcriptions.js
- src/app/components/hearing/request-transcript/request-transcript.component.html
- src/app/types/error-message.interface.ts
Code, stub, FT updated for updated BE endpoint to allow duplicated transcription link to work
> DMP-1578 Duplicated transcription ID bug, view duplicated transcription link

- darts-api-stub/audios/audio-requests.js
N/A
Add support for expired requests to delete audio stub so that deletion of expired requests is reflected in UI
> Add support for expired audio requests to delete audio stub 

- src/app/components/app.component.html
- src/app/components/app.component.spec.ts
- src/app/components/app.component.ts
https://tools.hmcts.net/jira/browse/DMP-1589
- goes to #content skipping the header and top nav
> DMP-1589 Adding global skip link

- darts-api-stub/cases/case.js
- darts-api-stub/hearings/hearings.js
- src/app/services/case/case.service.ts
N/A
Fix for JS / console errors for undefined requested_on property for transcripts for case and hearing
> Bug Fix: null requested_on error

- charts/darts-portal/Chart.yaml
- charts/darts-portal/values.stg.template.yaml
- charts/darts-portal/values.yaml
https://tools.hmcts.net/jira/browse/DMP-1646
- removing `darts`
- changing from `.platform` to `.apps`
> DMP-1646 Amending portal URL

- src/app/services/transcription/transcription.service.spec.ts
N/A
Updated unit tests in transcription service to bring test coverage up to 100%
> Updated unit tests for transcription service

- darts-api-stub/transcriptions/transcriptions.js
- src/app/components/transcriptions/view-transcript/view-transcript.component.html
- src/app/components/transcriptions/view-transcript/view-transcript.component.spec.ts
- src/app/components/transcriptions/view-transcript/view-transcript.component.ts
- src/app/types/transcription-details.interface.ts
https://tools.hmcts.net/jira/browse/DMP-1033
- Removal of dependency on Case Service endpoint to return reporting restriction
- Changes to reflect reporting restriction data from transcription endpoint
> DMP-1033-View-Transcript-Via-Your-Transcripts

- src/app/components/common/audio-player/audio-player.component.ts
- src/app/components/hearing/events-and-audio/events-and-audio.component.html
- src/app/components/hearing/events-and-audio/events-and-audio.component.spec.ts
- src/app/components/hearing/events-and-audio/events-and-audio.component.ts
[DMP-1613](https://tools.hmcts.net/jira/browse/DMP-1613)
Allow only one audio to be previewed at a time
> DMP-1613: Allow only one audio to be previewed at a time

- src/app/components/common/data-table/data-table.component.html
- src/app/components/common/data-table/data-table.component.ts
[DMP-1154](https://tools.hmcts.net/jira/browse/DMP-1154)
[DMP-1155](https://tools.hmcts.net/jira/browse/DMP-1155)
Adds hidden labels for Accessibility as per WAVE analysis
> DMP-1154 - Accessibility (WAVE) - View Hearing Screen - Empty Form Label

- src/app/components/common/details-table/details-table.component.html
- src/app/components/common/details-table/details-table.component.scss
- src/app/components/common/details-table/details-table.component.spec.ts
- src/app/components/common/details-table/details-table.component.ts
- src/app/components/common/govuk-heading/govuk-heading.component.html
- src/app/components/common/govuk-heading/govuk-heading.component.spec.ts
- src/app/components/common/govuk-heading/govuk-heading.component.ts
N/A
- Add GovUK Heading component
- Add Details table component
> UI components

- server/assets/javascripts/mfa.js
- server/assets/stylesheets/mfa.css
- server/views/azuread-b2c-login.html
DMP-1455
Initial changes for MFA screen for the B2C external login
jquery .js file, .css file
> DMP-1455 MFA B2C Changes

- cypress/e2e/functional/upload-transcript.cy.js
- darts-api-stub/transcriptions/transcriptions.js
- src/app/app.routes.ts
- src/app/components/common/details-table/details-table.component.html
- src/app/components/common/details-table/details-table.component.ts
- src/app/components/common/file-upload/file-upload.component.html
- src/app/components/common/file-upload/file-upload.component.spec.ts
- src/app/components/common/file-upload/file-upload.component.ts
- src/app/components/hearing/hearing.component.ts
- src/app/components/transcriptions/approve-transcript/approve-transcript.component.spec.ts
- src/app/components/transcriptions/approve-transcript/approve-transcript.component.ts
- src/app/components/transcriptions/view-transcript/view-transcript.component.html
- src/app/components/your-work/completed-transcript/completed-transcript.component.html
- src/app/components/your-work/completed-transcript/completed-transcript.component.spec.ts
- src/app/components/your-work/completed-transcript/completed-transcript.component.ts
- src/app/components/your-work/upload-transcript/upload-transcript.component.html
- src/app/components/your-work/upload-transcript/upload-transcript.component.spec.ts
- src/app/components/your-work/upload-transcript/upload-transcript.component.ts
- src/app/services/transcription/transcription.service.spec.ts
- src/app/services/transcription/transcription.service.ts
- src/app/types/transcription-details.interface.ts
https://tools.hmcts.net/jira/browse/DMP-1326
- Add Upload transcript journey for manual and automated flow
- Add file upload re-usable form component. Implements ControlValueAccessor interface to plugin into Angular reactive forms.
- Get Audio button redirects user to request audio screen with start and end time fields populated
- Add null check to details component
- Add `is_manual: boolean; hearing_id: number;` to TranscriptionDetails type
- Renamed `request_id: number; -> transcription_id: number;` to match the API response.
As Your Work screen isn't ready yet:
Navigate directly via URL to `/work/<transcription-id>`
Ensure the transcription is in a state of 'With Transcriber' (trs_id: 5)
> DMP-1326: Upload Transcript

- server/assets/javascripts/mfa.js
- server/assets/stylesheets/mfa.css
DMP-1455
MFA B2C changes, formatting for text, and new account details
> DMP-1455 MFA B2C Changes 

- server/assets/javascripts/mfa.js
- server/assets/stylesheets/login.css
- server/assets/stylesheets/mfa.css
MFA B2C changes, css styling and changed registering click event for can't scan link
4th attempt
> DMP-1455 MFA B2C

- src/app/app.routes.ts
N/A
To allow direct navigation to /work for testing
> Remove allowed roles to enable to test

- server/assets/javascripts/errors.js
- server/assets/javascripts/mfa.js
- server/assets/javascripts/reset-password.js
- server/assets/stylesheets/mfa.css
new totp title formatting, conditional info box, error formatting
1st PR
> DMP-1457 TOTP B2C

- server/assets/javascripts/errors.js
- server/assets/javascripts/mfa.js
- server/assets/stylesheets/mfa.css
Jquery/JS/CSS updates to format summary/page errors and update styling for TOTP B2C screen
> DMP-1457 TOTP B2C Screen

- src/app/components/audios/audio-view/audio-view.component.scss
- src/app/components/audios/audios.component.scss
- src/app/components/common/data-table/data-table.component.scss
- src/app/components/hearing/hearing.component.scss
- src/app/components/hearing/request-transcript/request-transcript.component.scss
- src/app/components/search/results/results.component.scss
- src/app/components/transcriptions/transcriptions.component.scss
Fix duplicate styling of the data table component cell
> Fix repeated style - .govuk-table__cell padding

- src/app/components/transcriptions/assign-transcript/assign-transcript.component.html
- src/app/components/transcriptions/assign-transcript/assign-transcript.component.ts
https://tools.hmcts.net/jira/browse/DMP-1234
- Case number fix in the breadcrumb for assign transcript order page
> DMP-1234-Assign-Transcript-Order

- src/app/components/transcriptions/transcriptions.component.ts
https://tools.hmcts.net/jira/browse/DMP-1720
Ensure the patch is completed before refreshing the data.
> DMP-1720 Wait before refreshing "Your transcripts" data

- src/app/components/common/data-table/data-table.component.spec.ts
- src/app/components/common/data-table/data-table.component.ts
https://tools.hmcts.net/jira/browse/DMP-1738
- Fixed Bug with Automated vs Manual column sorting
- Added Boolean sorting to data table
> DMP-1738-Transcript-Requests

- cypress/e2e/functional/transcript-requests-spec.cy.js
- darts-api-stub/transcriptions/transcriptions.js
- src/app/components/transcriptions/assign-transcript/assign-transcript.component.html
- src/app/components/transcriptions/assign-transcript/assign-transcript.component.spec.ts
- src/app/components/transcriptions/assign-transcript/assign-transcript.component.ts
- src/app/components/transcriptions/view-transcript/view-transcript.component.html
- src/app/components/your-work/your-work.component.spec.ts
- src/app/components/your-work/your-work.component.ts
- src/app/services/transcription/transcription.service.spec.ts
- src/app/services/transcription/transcription.service.ts
- src/app/types/work-request.interface.ts
https://tools.hmcts.net/jira/browse/DMP-1243
Transcribers can now:
- Assign to me
- Assign to me and request audio
- Assign to me and upload
In addition:
- Fixed 'Completed today' tab on Your work screen
- Update 'Transcript request (x)' count on 'assign to me'
- Fix null start and end time on view transcript
> DMP-1243: Assign transcript request, response and redirect

- darts-api-stub/cases/case.js
- darts-api-stub/hearings/hearings.js
- darts-api-stub/transcriptions/transcriptions.js
- src/app/components/case/case.component.spec.ts
- src/app/components/hearing/hearing.component.spec.ts
- src/app/components/hearing/request-transcript/request-transcript-confirmation/request-transcript-confirmation.component.spec.ts
- src/app/components/hearing/request-transcript/request-transcript-confirmation/request-transcript-confirmation.component.ts
- src/app/components/hearing/request-transcript/request-transcript.component.html
- src/app/components/hearing/request-transcript/request-transcript.component.spec.ts
- src/app/components/hearing/request-transcript/request-transcript.component.ts
- src/app/services/case/case.service.spec.ts
- src/app/services/mapping/mapping.service.ts
- src/app/services/transcription/transcription.service.spec.ts
- src/app/types/transcript.interface.ts
- src/app/types/transcription-request.interface.ts
- src/app/types/transcription-type.interface.ts
- src/app/types/transcription-urgency.interface.ts
link to ticket https://tools.hmcts.net/jira/browse/DMP-1566
main story ticket - https://tools.hmcts.net/jira/browse/DMP-1564
changes made to request and response to use full id names.
> DMP-1566 - changed ids to use full id name.

- src/app/components/error/forbidden/forbidden.component.spec.ts
- src/app/components/error/forbidden/forbidden.component.ts
[DMP-1704](https://tools.hmcts.net/jira/browse/DMP-1704)
Hide primary navigation on forbidden error screen
> Hide nav on forbidden error screen

- darts-api-stub/transcriptions/transcriptions.js
- src/app/components/transcriptions/approve-transcript/approve-transcript-buttons/approve-transcript-buttons.component.html
- src/app/components/transcriptions/approve-transcript/approve-transcript-buttons/approve-transcript-buttons.component.spec.ts
- src/app/components/transcriptions/approve-transcript/approve-transcript-buttons/approve-transcript-buttons.component.ts
- src/app/components/transcriptions/approve-transcript/approve-transcript.component.html
- src/app/components/transcriptions/approve-transcript/approve-transcript.component.ts
- src/app/services/transcription/transcription.service.spec.ts
- src/app/services/transcription/transcription.service.ts
[DMP-1011](https://tools.hmcts.net/jira/browse/DMP-1011)
Makes a call to the API to change the status to either approved or rejected (with a workflow comment).
Displays error if no message provided when rejecting.
> DMP-1011 - Submit Approve/Reject transcript request

- cypress/e2e/functional/your-transcripts-spec.cy.js
- darts-api-stub/transcriptions/transcriptions.js
- src/app/components/transcriptions/approve-transcript/approve-transcript.component.html
- src/app/components/transcriptions/approve-transcript/approve-transcript.component.spec.ts
- src/app/components/transcriptions/approve-transcript/approve-transcript.component.ts
[DMP-1024](https://tools.hmcts.net/jira/browse/DMP-1024)
Shows an error screen if transcription request has already been approved / rejected (409 received)
> DMP-1024 - Multiple users tried to approve a request at the same time.

- cypress/e2e/functional/view-transcript.cy.js
- darts-api-stub/transcriptions/transcriptions.js
- src/app/components/transcriptions/approve-transcript/approve-transcript.component.spec.ts
- src/app/components/transcriptions/approve-transcript/approve-transcript.component.ts
- src/app/components/transcriptions/transcription-requests/transcription-requests.component.spec.ts
- src/app/components/transcriptions/view-transcript/approved-transcript/approved-transcript.component.html
- src/app/components/transcriptions/view-transcript/approved-transcript/approved-transcript.component.spec.ts
- src/app/components/transcriptions/view-transcript/approved-transcript/approved-transcript.component.ts
- src/app/components/transcriptions/view-transcript/rejected-transcript/rejected-transcript.component.html
- src/app/components/transcriptions/view-transcript/rejected-transcript/rejected-transcript.component.spec.ts
- src/app/components/transcriptions/view-transcript/rejected-transcript/rejected-transcript.component.ts
- src/app/components/transcriptions/view-transcript/view-transcript.component.html
- src/app/components/transcriptions/view-transcript/view-transcript.component.ts
- src/app/services/transcription/transcription.service.spec.ts
- src/app/services/transcription/transcription.service.ts
- src/app/types/transcription-details.interface.ts
DMP-1028
Refactoring view transcript component from Your Transcript page
> DMP-1028 Reject transcript view & refactoring

- cypress/e2e/functional/request-audio-spec.cy.js
- src/app/components/common/audio-player/audio-player.component.html
- src/app/components/common/audio-player/audio-player.component.scss
- src/app/components/common/audio-player/audio-player.component.spec.ts
- src/app/components/common/audio-player/audio-player.component.ts
- src/app/components/common/data-table/data-table.component.html
- src/app/components/common/data-table/data-table.component.scss
- src/app/components/hearing/events-and-audio/events-and-audio.component.html
- src/app/components/hearing/events-and-audio/events-and-audio.component.scss
- src/app/components/hearing/events-and-audio/events-and-audio.component.spec.ts
- src/app/components/hearing/events-and-audio/events-and-audio.component.ts
- src/app/types/data-table-column.interface.ts
[DMP-1668](https://tools.hmcts.net/jira/browse/DMP-1668)
- Remove preview buttons
- All audio players shown on page load
- `@Input() preload = true` Added to audio player to enable / disable auto download.
- Add configurable widths to data table columns
> DMP-1668: Update the Hearing Details screen - Events and audio tab

- server/assets/javascripts/errors.js
DMP-1773
Added setTimeout to ensure message is shown before removing
Tested on staging and should work
> DMP-1773 Login b2c bug

- cypress/e2e/functional/transcript-requests-spec.cy.js
- darts-api-stub/transcriptions/transcriptions.js
- src/app/components/error/conflict/conflict.component.html
- src/app/components/error/conflict/conflict.component.spec.ts
- src/app/components/error/conflict/conflict.component.ts
- src/app/components/transcriptions/approve-transcript/approve-transcript.component.html
- src/app/components/transcriptions/approve-transcript/approve-transcript.component.ts
- src/app/components/transcriptions/assign-transcript/assign-transcript.component.html
- src/app/components/transcriptions/assign-transcript/assign-transcript.component.spec.ts
- src/app/components/transcriptions/assign-transcript/assign-transcript.component.ts
[DMP-1353](https://tools.hmcts.net/jira/browse/DMP-1353)
- Refactored conflict error into own component
- Used new conflict component in both approve and assign transcript
> DMP-1353 - 2 people assign a transcript request to themselves

- darts-api-stub/transcriptions/transcriptions.js
- src/app/services/custom-sort/table-custom-sort-functions.service.spec.ts
- src/app/services/custom-sort/table-custom-sort-functions.service.ts
https://tools.hmcts.net/jira/browse/DMP-1746
- Null checking for function
> DMP-1746-Priority-Order-Sort 

- server/assets/javascripts/errors.js
- server/assets/javascripts/login.js
- server/views/azuread-b2c-login.html
Re-order scripts to try fix intermittent error of error.js not loading before login.js
separate setTimeout for input event due to autocomplete delay
> DMP-1773 B2C login errors

- server/assets/javascripts/errors.js
- server/assets/javascripts/login.js
Attempt quicker removal of error
Move event registers into existing settimeout in login
> DMP-1773 b2c

- cypress/e2e/functional/transcript-requests-spec.cy.js
- darts-api-stub/transcriptions/transcriptions.js
- src/app/services/transcription/transcription.service.ts
Bug fix, involved appending Z to transcript hearing date for UTC conversion
> DMP-1865 hearing date bug on view transcript

- src/app/components/audios/audios.component.html
- src/app/components/case/hearing-results/hearing-results.component.html
- src/app/components/hearing/hearing.component.html
- src/app/components/search/results/results.component.html
- src/app/components/transcriptions/transcription-requests/transcription-requests.component.html
- src/app/components/transcriptions/transcriptions.component.html
- src/app/components/your-work/your-work.component.html
- src/styles.scss
N/A
Styling change to make all links .govuk-link and to override :visited state colour
> Add missing govuk-links to a tags, override visited state

- src/app/components/transcriptions/approve-transcript/approve-transcript-buttons/approve-transcript-buttons.component.html
[1837](https://tools.hmcts.net/jira/browse/DMP-1837)
[1838](https://tools.hmcts.net/jira/browse/DMP-1838)
> DMP-1837 & 1838

- src/app/components/transcriptions/approve-transcript/approve-transcript.component.html
- src/app/components/transcriptions/approve-transcript/approve-transcript.component.spec.ts
- src/app/components/transcriptions/approve-transcript/approve-transcript.component.ts
- src/app/services/transcription/transcription.service.ts
DMP-1806
Add Breadcrumb to transcript approval screen
Change label 'From' to 'Requested'
Add null check for start & end time
> DMP-1806: Breadcrumb on approval screen

- cypress/e2e/functional/request-audio-spec.cy.js
- darts-api-stub/audios/index.js
- src/app/components/audios/audio-view/audio-view.component.spec.ts
- src/app/components/common/audio-player/audio-player.component.html
- src/app/components/common/audio-player/audio-player.component.spec.ts
- src/app/components/common/audio-player/audio-player.component.ts
- src/app/services/audio-request/audio-request.service.spec.ts
- src/app/services/audio-request/audio-request.service.ts
- src/app/services/error/error-message.service.ts
https://tools.hmcts.net/jira/browse/DMP-1568
Add a specific error message based on http error code to the audio player component
HEAD request is used to get the status code for the endpoint if an error occurs on audio playback/preview.
> DMP-1568: Audio player error messages

- cypress/e2e/functional/case-file-spec.cy.js
- darts-api-stub/cases/case.js
- src/app/components/case/case-file/case-file.component.html
- src/app/components/case/case-file/case-file.component.scss
- src/app/components/case/case-file/case-file.component.spec.ts
- src/app/components/case/case-file/case-file.component.ts
- src/app/components/case/case.component.spec.ts
- src/app/services/user/user.service.ts
- src/app/types/user-state.ts
DMP-1369
Updated retention link on case file screen
> DMP-1369 Retention link

- cypress/e2e/functional/request-audio-spec.cy.js
- darts-api-stub/audios/audio-requests.js
- src/app/components/hearing/hearing.component.html
- src/app/components/hearing/hearing.component.spec.ts
- src/app/services/error/error-message.service.ts
[DMP-1488](https://tools.hmcts.net/jira/browse/DMP-1488)
> DMP-1488 - Error 409 - duplicate audio request

- darts-api-stub/audios/audio-requests.js
- src/app/components/audios/audio-view/audio-view.component.spec.ts
- src/app/components/audios/audio-view/audio-view.component.ts
- src/app/components/audios/audios.component.spec.ts
- src/app/components/audios/audios.component.ts
- src/app/services/audio-request/audio-request.service.spec.ts
- src/app/services/audio-request/audio-request.service.ts
- src/app/types/audio-request-row.interface.ts
https://tools.hmcts.net/jira/browse/DMP-1835
- Update delete endpoint for media requests
> DMP-1835-Change-Media-Request-Endpoint

- darts-api-stub/audios/audio-requests.js
- src/app/components/audios/audio-view/audio-view.component.spec.ts
- src/app/components/audios/audio-view/audio-view.component.ts
- src/app/services/audio-request/audio-request.service.spec.ts
- src/app/services/audio-request/audio-request.service.ts
https://tools.hmcts.net/jira/browse/DMP-1764
- Updated patch endpoint for media endpoint
> DMP-1764-Change-Media-Request-Patch-Endpoint

- src/app/components/audios/audios.component.ts
[DMP-2018](https://tools.hmcts.net/jira/browse/DMP-2018)
Fix refresh on delete bug
> DMP-2018: Fix refresh on delete bug in AudiosComponent

- Jenkinsfile_CNP
> DMP-1875-ITHC-Test

- cypress/e2e/functional/case-retention-spec.cy.js
- src/app/components/case/case-retention-change/case-retention-change.component.html
- src/app/components/case/case-retention-change/case-retention-change.component.spec.ts
- src/app/components/case/case-retention-change/case-retention-change.component.ts
- src/app/components/case/case-retention-date/case-retention-date.component.html
- src/app/components/case/case-retention-date/case-retention-date.component.spec.ts
- src/app/components/case/case-retention-date/case-retention-date.component.ts
- src/app/validators/before-date.validator.ts
[DMP-1450](https://tools.hmcts.net/jira/browse/DMP-1450)
- Do some additional checks to make sure user is Admin or Judge which allows for reducing retention date below the current
- Do not allow Admin or Judge to reduce retention date lower than the original date
> DMP-1450 - Retention errors

- darts-api-stub/transcriptions/transcriptions.js
- src/app/components/transcriptions/approve-transcript/approve-transcript.component.spec.ts
- src/app/components/transcriptions/approve-transcript/approve-transcript.component.ts
- src/app/components/transcriptions/assign-transcript/assign-transcript.component.spec.ts
- src/app/components/transcriptions/assign-transcript/assign-transcript.component.ts
- src/app/components/transcriptions/view-transcript/approved-transcript/approved-transcript.component.html
- src/app/components/transcriptions/view-transcript/approved-transcript/approved-transcript.component.spec.ts
- src/app/components/transcriptions/view-transcript/rejected-transcript/rejected-transcript.component.html
- src/app/components/transcriptions/view-transcript/rejected-transcript/rejected-transcript.component.spec.ts
- src/app/components/transcriptions/view-transcript/view-transcript.component.html
- src/app/components/your-work/upload-transcript/upload-transcript.component.spec.ts
- src/app/components/your-work/upload-transcript/upload-transcript.component.ts
- src/app/types/transcription-details.interface.ts
DMP-2080
reporting_restriction renamed to case_reporting_restriction
> DMP-2080 Reporting restriction bug

- angular.json
- darts-api-stub/views/login.ejs
- server/app-config.ts
- server/routes.ts
- src/app/app.routes.ts
- src/app/components/common/filters/filter.interface.ts
- src/app/components/common/filters/filters.component.html
- src/app/components/common/filters/filters.component.scss
- src/app/components/common/filters/filters.component.spec.ts
- src/app/components/common/filters/filters.component.ts
- src/app/components/dev/dev.component.html
- src/app/components/dev/dev.component.spec.ts
- src/app/components/dev/dev.component.ts
- src/app/services/app-config/app-config.service.spec.ts
- src/app/services/app-config/app-config.service.ts
DMP-2067
Re-styling to match Figma to be covered by another ticket
- new dev/components route which only runs during NODE_ENV=development (will run by default on dev local)
- single or multiselect for filters
- Searchable filter
- outputs selected filters
- angular.json updated to copy across moj images
- unit tests
> DMP-2067 Generic filter component

- src/app/app.routes.ts
- src/app/components/dev/dev.component.ts
N/A
- allow unauthenticated access
- injecting dependencies for consistency
> Minor dev/components tweaks

- darts-api-stub/cases/case.js
- src/app/services/case/case.service.spec.ts
- src/app/services/case/case.service.ts
https://tools.hmcts.net/jira/browse/DMP-1803
- Update search to use POST endpoint instead of GET
> DMP-1803-Case-Search-Endpoint-Update

- src/app/components/transcriptions/transcriptions.component.html
- src/app/components/transcriptions/transcriptions.component.spec.ts
- src/app/components/transcriptions/transcriptions.component.ts
[DMP-2123](https://tools.hmcts.net/jira/browse/DMP-2123)
> DMP-2123/2124: Singular & plural transcript delete screen text

- src/app/components/common/filters/filters.component.html
- src/app/components/common/filters/filters.component.spec.ts
- src/app/components/common/filters/filters.component.ts
No jira link
- Added isChecked to ensure previously selected checkboxes remain checked upon filtered search results
- Unit tests added
> DevComponents: Filter - isChecked added for search changes

- src/app/components/hearing/hearing.component.html
- src/app/components/hearing/hearing.component.scss
https://tools.hmcts.net/jira/browse/DMP-2085
> DMP-2085: Add spacing to order request summary and confirmation

- cypress/e2e/functional/case-retention-spec.cy.js
- darts-api-stub/roles.js
- darts-api-stub/users.js
- src/app/admin/admin.routes.ts
- src/app/admin/components/users/users.component.html
- src/app/admin/components/users/users.component.spec.ts
- src/app/admin/components/users/users.component.ts
- src/app/app.routes.spec.ts
- src/app/app.routes.ts
- src/app/auth/auth.guard.ts
- src/app/components/error/not-found/not-found.component.spec.ts
- src/app/components/error/not-found/not-found.component.ts
- src/app/components/layout/header/header.component.html
- src/app/components/layout/header/header.component.spec.ts
- src/app/components/layout/header/header.component.ts
- src/app/portal/portal.routes.ts
[DMP-2187](https://tools.hmcts.net/jira/browse/DMP-2187)
- Split Admin and Portal routes
- Placeholder User component
- Hide nav on 404
- Update tests
- Add admin nav
- Add stub ADMIN user
> DMP-2187: Admin portal routing

- darts-api-stub/cases/case.js
- src/app/core/components/common/reporting-restriction/reporting-restriction.component.html
- src/app/core/components/common/reporting-restriction/reporting-restriction.component.spec.ts
- src/app/core/components/common/reporting-restriction/reporting-restriction.component.ts
- src/app/portal/components/audios/audio-view/audio-view.component.html
- src/app/portal/components/audios/audio-view/audio-view.component.spec.ts
- src/app/portal/components/case/case-file/case-file.component.html
- src/app/portal/components/case/case-file/case-file.component.spec.ts
- src/app/portal/components/hearing/hearing.component.html
- src/app/portal/components/hearing/hearing.component.ts
- src/app/portal/components/hearing/order-confirmation/order-confirmation.component.spec.ts
- src/app/portal/components/hearing/request-transcript/request-transcript.component.html
- src/app/portal/components/search/results/results.component.html
- src/app/portal/components/search/results/results.component.ts
- src/app/portal/components/transcriptions/approve-transcript/approve-transcript.component.html
- src/app/portal/components/transcriptions/approve-transcript/approve-transcript.component.spec.ts
- src/app/portal/components/transcriptions/approve-transcript/approve-transcript.component.ts
- src/app/portal/components/transcriptions/assign-transcript/assign-transcript.component.html
- src/app/portal/components/transcriptions/view-transcript/approved-transcript/approved-transcript.component.html
- src/app/portal/components/transcriptions/view-transcript/case-hearing-transcript/case-hearing-transcript.component.html
- src/app/portal/components/transcriptions/view-transcript/rejected-transcript/rejected-transcript.component.html
- src/app/portal/components/your-work/upload-transcript/upload-transcript.component.html
- src/app/portal/components/your-work/upload-transcript/upload-transcript.component.spec.ts
- src/app/portal/models/case/case.interface.ts
- src/app/portal/models/case/case.type.ts
- src/app/portal/services/case/case.service.spec.ts
- src/app/portal/services/case/case.service.ts
https://tools.hmcts.net/jira/browse/DMP-1799
- for all screens in context of a hearing
- refactoring some logic into the reporting restrictions component
- adding more tests
- removing unused `reporting_restriction` field
- distinguishing between case and search results in types
> DMP-1799 Amending reporting restrictions to be scoped to hearing level

- src/app/portal/components/search/search.component.html
src/app/core/components/common/data-table/data-table.component.html
> DMP-2256 Case search date to label text fix

- src/app/admin/components/users/user-search-form/user-search-form.component.html
- src/app/core/components/layout/header/header.component.html
https://tools.hmcts.net/jira/browse/DMP-634
As title
> DMP-634 Visually hide user status label on search and fixing admin header

- cypress/e2e/functional/admin-portal/courthouses-spec.cy.js
- src/app/admin/admin.routes.ts
- src/app/admin/components/courthouses/courthouse-search-form/courthouse-search-form.component.html
- src/app/admin/components/courthouses/courthouse-search-form/courthouse-search-form.component.scss
- src/app/admin/components/courthouses/courthouse-search-form/courthouse-search-form.component.spec.ts
- src/app/admin/components/courthouses/courthouse-search-form/courthouse-search-form.component.ts
- src/app/admin/components/courthouses/courthouses.component.html
- src/app/admin/components/courthouses/courthouses.component.scss
- src/app/admin/components/courthouses/courthouses.component.spec.ts
- src/app/admin/components/courthouses/courthouses.component.ts
- src/app/admin/models/courthouses/courthouse-search-form-values.type.ts
https://tools.hmcts.net/jira/browse/DMP-725
Courthouses component and search form
> DMP-725 Courthouses admin screen

- cypress/e2e/functional/case-retention-spec.cy.js
- src/app/portal/components/case/case-retention-date/case-retention-change/case-retention-change.component.spec.ts
- src/app/portal/components/case/case-retention-date/case-retention-change/case-retention-change.component.ts
[DMP-2161](https://tools.hmcts.net/jira/browse/DMP-2161)
Added full stops
> DMP-2161 [UPDATE] - Add full stops

- cypress/e2e/functional/annotations-spec.cy.js
- src/app/portal/components/hearing/add-annotation/add-annotation-success/add-annotation-success.component.html
- src/app/portal/components/hearing/add-annotation/add-annotation-success/add-annotation-success.component.spec.ts
- src/app/portal/components/hearing/add-annotation/add-annotation-success/add-annotation-success.component.ts
[DMP-1623](https://tools.hmcts.net/jira/browse/DMP-1623)
- Addition of annotation confirmation screen
> DMP-1623-Annotation-Confirmation-Screen

- src/app/admin/components/users/user-search-results/user-search-results.component.html
- src/app/admin/components/users/user-search-results/user-search-results.component.ts
- src/app/admin/components/users/users.component.html
https://tools.hmcts.net/jira/browse/DMP-1834
Minor fixes
- don't show results when loading
- amending email column header to match figma
> DMP-1834 Admin user search fixes

- src/app/core/components/common/tabs/tabs.component.ts
- src/app/portal/components/case/case.component.html
- src/app/portal/components/case/case.component.spec.ts
- src/app/portal/components/case/case.component.ts
- src/app/portal/components/case/hearing-results/hearing-results.component.html
- src/app/portal/components/case/hearing-results/hearing-results.component.spec.ts
- src/app/portal/components/case/hearing-results/hearing-results.component.ts
- src/app/portal/components/hearing/hearing.component.spec.ts
[DMP-2456](https://tools.hmcts.net/jira/browse/DMP-2456)
- Delete annotation from case level screen
>  DMP-2456-Delete-Annotation-Case-Screen

- cypress/e2e/functional/admin-portal/courthouses-spec.cy.js
- cypress/e2e/functional/admin-portal/user-record-spec.cy.js
- cypress/e2e/functional/admin-portal/users-spec.cy.js
- darts-api-stub/admin/users/users.js
- package.json
N/A
Admin portal functional tests are not being picked up by the pipeline due to spec files being in the sub-directory.
- Changed spec path glob to include /**/ as per Cypress docs
- Fix broken FTs
> Fix admin portal FTs

- cypress/e2e/functional/admin-portal/users-spec.cy.js
- src/app/admin/components/users/create-user/create-update-user-form/create-update-user-form.component.ts
https://tools.hmcts.net/jira/browse/DMP-2497
> DMP-2497: Email in use validation error message text change

- src/app/portal/components/audios/audios.component.ts
- src/app/portal/components/your-work/your-work.component.ts
https://tools.hmcts.net/jira/browse/DMP-2472
Stop polling when navigating away from 'Your audio' & 'Your work' screens
> DMP-2472: Manually unsubscribe from polling

- src/app/admin/components/users/groups/assign-groups/assign-groups.component.html
- src/app/admin/components/users/groups/assign-groups/assign-groups.component.scss
- src/app/admin/components/users/groups/assign-groups/assign-groups.component.spec.ts
- src/app/admin/components/users/groups/assign-groups/assign-groups.component.ts
- src/app/core/components/common/data-table/data-table.component.html
- src/app/core/components/common/data-table/data-table.component.scss
- src/app/core/components/common/data-table/data-table.component.ts
- src/app/core/components/common/filters/checkbox-list/checkbox-list-item.type.ts
- src/app/core/components/common/filters/checkbox-list/checkbox-list.component.html
- src/app/core/components/common/filters/checkbox-list/checkbox-list.component.spec.ts
- src/app/core/components/common/filters/checkbox-list/checkbox-list.component.ts
- src/app/dev/dev.component.html
- src/app/dev/dev.component.scss
- src/app/dev/dev.component.ts
https://tools.hmcts.net/jira/browse/DMP-2066
- Filter by role and search by group name
- Add Checkbox List custom form control component to dynamically generate checkboxes that work with reactive forms
- Added to dev/components path
- Add maxHeight to the data table component and enable scrolling
- Add 2-way binding to selected items in the data table component
> DMP-2066 Assign groups component

- src/app/core/components/common/data-table/data-table.component.scss
[DMP-1641](https://tools.hmcts.net/jira/browse/DMP-1641)
- Added word-wrap to table cells for accessibility
> DMP-1641-Text-Spacing

- src/app/core/validators/before-time.validator.ts
[DMP-2480](https://tools.hmcts.net/jira/browse/DMP-2480)
Fix flakey unit test to prevent this error on pipeline:
> DMP-2480: Fix before-time validator

- src/app/admin/components/users/create-user/create-update-user-form/create-update-user-form.component.html
- src/app/admin/components/users/create-user/create-update-user-form/create-update-user-form.component.spec.ts
- src/app/admin/components/users/create-user/create-update-user-form/create-update-user-form.component.ts
DMP-2497
- Text changes
- Add max length validation to optional description field on create / edit user
> DMP-2497: Error message text change

- config/default.json
- server/middleware/session.ts
> Setting a better session cookie name

- src/app/admin/components/users/create-user/create-update-user-form/create-update-user-form.component.spec.ts
- src/app/admin/components/users/create-user/create-update-user-form/create-update-user-form.component.ts
https://tools.hmcts.net/jira/browse/DMP-2551
- Updated email validation error message
- Add unit tests to cover error message text
> DMP-2551: Update email validation error message

- src/app/admin/components/users/user-record/user-record.component.html
- src/app/core/components/common/tabs/tabs.component.html
- src/app/core/components/common/tabs/tabs.component.spec.ts
- src/app/core/directives/tab.directive.ts
https://tools.hmcts.net/jira/browse/DMP-2550
- Add screen reader text input to tab component / directive
- Add unit test for screen reader text
> DMP-2550: Add screen reader text to tab component

- cypress/e2e/functional/your-transcripts-spec.cy.js
- darts-api-stub/transcriptions/transcriptions.js
- src/app/core/services/error/error-message.service.ts
- src/app/portal/components/transcriptions/error/partial-delete-error/partial-delete-error.component.html
- src/app/portal/components/transcriptions/error/partial-delete-error/partial-delete-error.component.scss
- src/app/portal/components/transcriptions/error/partial-delete-error/partial-delete-error.component.spec.ts
- src/app/portal/components/transcriptions/error/partial-delete-error/partial-delete-error.component.ts
- src/app/portal/components/transcriptions/transcriptions.component.spec.ts
- src/app/portal/components/transcriptions/transcriptions.component.ts
- src/app/portal/portal.routes.ts
[DMP-1694](https://tools.hmcts.net/jira/browse/DMP-1694)
- Partial delete error screen for 400 status error codes when hiding/removing transcript requests
> DMP-1694-Hiding-Transcriptions

- cypress/e2e/functional/admin-portal/user-record-spec.cy.js
- darts-api-stub/admin/security-groups/security-groups.js
- darts-api-stub/admin/security-roles/security-roles.js
- darts-api-stub/admin/users/users.js
- darts-api-stub/index.js
- src/app/admin/admin.routes.ts
- src/app/admin/components/users/assign-groups/assign-groups.component.html
- src/app/admin/components/users/assign-groups/assign-groups.component.scss
- src/app/admin/components/users/assign-groups/assign-groups.component.spec.ts
- src/app/admin/components/users/assign-groups/assign-groups.component.ts
- src/app/admin/components/users/assign-groups/security-group-selector/security-group-selector.component.html
- src/app/admin/components/users/assign-groups/security-group-selector/security-group-selector.component.scss
- src/app/admin/components/users/assign-groups/security-group-selector/security-group-selector.component.spec.ts
- src/app/admin/components/users/assign-groups/security-group-selector/security-group-selector.component.ts
- src/app/admin/components/users/user-record/user-record.component.html
- src/app/admin/components/users/user-record/user-record.component.scss
- src/app/admin/components/users/user-record/user-record.component.ts
- src/app/admin/models/users/security-role.type.ts
- src/app/admin/models/users/user.type.ts
- src/app/admin/services/user-admin/user-admin.service.spec.ts
- src/app/admin/services/user-admin/user-admin.service.ts
- src/app/core/components/common/data-table/data-table.component.html
- src/app/dev/dev.component.html
- src/app/dev/dev.component.ts
https://tools.hmcts.net/jira/browse/DMP-2225
- Complete assign groups journey
- Add FTs
- Remove hidden groups from UI
- Default to Groups tab on cancel / return to user record screen
> DMP-2225: Assign groups

- src/app/core/components/common/details-table/details-table.component.html
- src/app/core/components/common/details-table/details-table.component.scss
[DMP-2435](https://tools.hmcts.net/jira/browse/DMP-2435)
- Fix for empty table header issue on Admin portal user record table header
> DMP-2435: Fix admin portal user record table header

- src/app/portal/components/case/case-retention-date/case-retention-confirm/case-retention-confirm.component.html
[DMP-2210](https://tools.hmcts.net/jira/browse/DMP-2210)
- Add accessibility text to retention change links
- Add .govuk-link class / styles to the anchor tags
> DMP-2210: Add accessibility text to retention change links

- cypress/e2e/functional/request-audio-spec.cy.js
- darts-api-stub/audios/index.js
- src/app/portal/components/hearing/events-and-audio/events-and-audio.component.html
- src/app/portal/models/hearing/hearing-audio.interface.ts
https://tools.hmcts.net/jira/browse/DMP-2300
New message on audio preview when is_available is false
> DMP-2300 Preview audio message for unavailable audio

- src/app/portal/components/case/case-retention-date/case-retention-change/case-retention-change.component.html
https://tools.hmcts.net/jira/browse/DMP-2546
- Add service now incident reference hint to case retention change confirmation screen
> DMP-2546: Add hint for service now incident number in change reason

- src/app/core/components/layout/header/admin-navigation/admin-navigation.component.html
- src/app/core/components/layout/header/admin-navigation/admin-navigation.component.spec.ts
- src/app/core/components/layout/header/admin-navigation/admin-navigation.component.ts
- src/app/core/components/layout/header/header.component.html
- src/app/core/components/layout/header/header.component.spec.ts
- src/app/core/components/layout/header/header.component.ts
- src/app/core/components/layout/header/portal-navigation/portal-navigation.component.html
- src/app/core/components/layout/header/portal-navigation/portal-navigation.component.spec.ts
- src/app/core/components/layout/header/portal-navigation/portal-navigation.component.ts
https://tools.hmcts.net/jira/browse/DMP-2220
- Divide admin and portal navigation into separate components.
> DMP:2220: Separate admin and portal navigation

- darts-api-stub/roles.js
- darts-api-stub/users.js
- src/app/admin/admin.routes.ts
- src/app/core/components/layout/header/header.component.spec.ts
- src/app/core/components/layout/header/header.component.ts
- src/app/core/components/layout/header/portal-navigation/portal-navigation.component.html
- src/app/core/components/layout/header/portal-navigation/portal-navigation.component.spec.ts
- src/app/core/models/user/role-name.type.ts
- src/app/core/services/user/user.service.spec.ts
- src/app/core/services/user/user.service.ts
- src/app/portal/components/case/case-file/case-file.component.html
- src/app/portal/components/transcriptions/transcriptions.component.html
- src/app/portal/components/transcriptions/transcriptions.component.spec.ts
- src/app/portal/components/transcriptions/transcriptions.component.ts
- src/app/portal/portal.routes.ts
https://tools.hmcts.net/jira/browse/DMP-2404
- allow access to admin portal
- allow access to "Your transcripts"
- allow access to case retention
> DMP-2404 Fixes for Super User role

- cypress/e2e/functional/admin-portal/user-record-spec.cy.js
- darts-api-stub/admin/courthouses/courthouses.js
- darts-api-stub/admin/security-groups/security-groups.js
- darts-api-stub/admin/security-roles/security-roles.js
- src/app/admin/admin.routes.ts
- src/app/admin/components/courthouses/courthouse-record/courthouse-record.component.html
- src/app/admin/components/courthouses/courthouse-record/courthouse-record.component.ts
- src/app/admin/components/courthouses/create-courthouse/create-courthouse.component.spec.ts
- src/app/admin/components/courthouses/create-courthouse/create-update-courthouse-confirmation/create-update-courthouse-confirmation.component.html
- src/app/admin/components/courthouses/create-courthouse/create-update-courthouse-confirmation/create-update-courthouse-confirmation.component.scss
- src/app/admin/components/courthouses/create-courthouse/create-update-courthouse-confirmation/create-update-courthouse-confirmation.component.spec.ts
- src/app/admin/components/courthouses/create-courthouse/create-update-courthouse-confirmation/create-update-courthouse-confirmation.component.ts
- src/app/admin/components/courthouses/create-courthouse/create-update-courthouse-form/create-update-courthouse-form.component.html
- src/app/admin/components/courthouses/create-courthouse/create-update-courthouse-form/create-update-courthouse-form.component.spec.ts
- src/app/admin/components/courthouses/create-courthouse/create-update-courthouse-form/create-update-courthouse-form.component.ts
- src/app/admin/components/courthouses/edit-courthouse/edit-courthouse.component.html
- src/app/admin/components/courthouses/edit-courthouse/edit-courthouse.component.spec.ts
- src/app/admin/components/courthouses/edit-courthouse/edit-courthouse.component.ts
- src/app/admin/components/users/create-user/create-user.component.ts
- src/app/admin/models/courthouses/create-update-courthouse-form-values.type.ts
- src/app/admin/models/users/security-group.type.ts
- src/app/admin/services/courthouses/courthouse.service.spec.ts
- src/app/admin/services/courthouses/courthouses.service.ts
- src/app/core/components/common/details-table/details-table.component.ts
[DMP-2252](https://tools.hmcts.net/jira/browse/DMP-2252)
> DMP-2252 + 2263 - Edit and check a courthouse

- cypress/e2e/functional/admin-portal/group-record.spec.cy.js
- cypress/e2e/functional/admin-portal/groups-spec.cy.js
- darts-api-stub/admin/security-groups/security-groups.js
- src/app/admin/admin.routes.ts
- src/app/admin/components/courthouses/create-courthouse/create-update-courthouse-form/create-update-courthouse-form.component.spec.ts
- src/app/admin/components/groups/group-courthouses/group-courthouses.component.html
- src/app/admin/components/groups/group-courthouses/group-courthouses.component.scss
- src/app/admin/components/groups/group-courthouses/group-courthouses.component.spec.ts
- src/app/admin/components/groups/group-courthouses/group-courthouses.component.ts
- src/app/admin/components/groups/group-record/group-record.component.html
- src/app/admin/components/groups/group-record/group-record.component.scss
- src/app/admin/components/groups/group-record/group-record.component.spec.ts
- src/app/admin/components/groups/group-record/group-record.component.ts
- src/app/admin/components/groups/group-users/group-users.component.html
- src/app/admin/components/groups/group-users/group-users.component.spec.ts
- src/app/admin/components/groups/group-users/group-users.component.ts
- src/app/admin/components/groups/groups.component.html
- src/app/admin/components/groups/groups.component.spec.ts
- src/app/admin/components/groups/groups.component.ts
- src/app/admin/components/users/user-groups/assign-groups/assign-groups.component.spec.ts
- src/app/admin/models/users/security-group.interface.ts
- src/app/admin/models/users/security-group.type.ts
- src/app/admin/services/courthouses/courthouses.service.ts
- src/app/admin/services/groups/groups.service.spec.ts
- src/app/admin/services/groups/groups.service.ts
- src/app/admin/services/user-admin/user-admin.service.spec.ts
https://tools.hmcts.net/jira/browse/DMP-2299
- Add view group record screen
- Add assign courthouse to group
- Add remove courthouse from group
> DMP-2299: Add view group details screen

- cypress/e2e/functional/admin-portal/group-record.spec.cy.js
- darts-api-stub/admin/users/users.js
- darts-api-stub/users.js
- src/app/admin/admin.routes.ts
- src/app/admin/components/groups/group-courthouses/group-courthouses.component.html
- src/app/admin/components/groups/group-courthouses/group-courthouses.component.scss
- src/app/admin/components/groups/group-courthouses/group-courthouses.component.ts
- src/app/admin/components/groups/group-record/group-record.component.html
- src/app/admin/components/groups/group-record/group-record.component.spec.ts
- src/app/admin/components/groups/group-record/group-record.component.ts
- src/app/admin/components/groups/group-users/group-users.component.html
- src/app/admin/components/groups/group-users/group-users.component.scss
- src/app/admin/components/groups/group-users/group-users.component.spec.ts
- src/app/admin/components/groups/group-users/group-users.component.ts
- src/app/admin/components/groups/remove-group-users/remove-group-users.component.html
- src/app/admin/components/groups/remove-group-users/remove-group-users.component.spec.ts
- src/app/admin/components/groups/remove-group-users/remove-group-users.component.ts
- src/app/admin/services/groups/groups.service.ts
- src/app/admin/services/user-admin/user-admin.service.ts
- src/app/core/components/common/auto-complete/auto-complete.component.html
- src/app/core/components/common/auto-complete/auto-complete.component.scss
- src/app/core/components/common/auto-complete/auto-complete.component.spec.ts
- src/app/core/components/common/auto-complete/auto-complete.component.ts
[DMP-2303](https://tools.hmcts.net/jira/browse/DMP-2303)
[DMP-2581](https://tools.hmcts.net/jira/browse/DMP-2581)
[DMP-2305](https://tools.hmcts.net/jira/browse/DMP-2305)
- Add users tab on group details screen
- Add assign users to group
- Add remove users from group
- Add autocomplete component
> DMP-2303, DMP-2581 & DMP-2305 - Group details - Users tab

- darts-api-stub/audios/audio-requests.js
- src/app/portal/components/hearing/hearing.component.spec.ts
- src/app/portal/components/hearing/hearing.component.ts
- src/app/portal/services/audio-request/audio-request.service.spec.ts
- src/app/portal/services/audio-request/audio-request.service.ts
- src/app/portal/services/hearing/hearing.service.spec.ts
- src/app/portal/services/hearing/hearing.service.ts
[DMP-2521](https://tools.hmcts.net/jira/browse/DMP-2521)
- Request Audio Service Method changes
> DMP-2521-Audio-Requests-Playback-And-Download

- src/app/core/components/common/audio-player/audio-player.component.html
- src/app/portal/components/hearing/events-and-audio/events-and-audio.component.html
https://tools.hmcts.net/jira/browse/DMP-2561
> DMP 2561 - Preview hint text

- src/app/core/services/error/error-message.service.ts
- src/app/portal/components/case/case.component.spec.ts
- src/app/portal/components/case/hearing-results/hearing-results.component.html
- src/app/portal/components/hearing/hearing.component.html
- src/app/portal/components/hearing/hearing.component.spec.ts
[DMP-2659](https://tools.hmcts.net/jira/browse/DMP-2659)
- Translation QA user cannot get case/hearing transcriptions
> DMP-2659-Translation-User-Changes 

- src/app/portal/components/search/search.component.spec.ts
- src/app/portal/components/search/search.component.ts
https://tools.hmcts.net/jira/browse/DMP-2646
> DMP-2646 - Case Search - bug fix for stored error messages

- darts-api-stub/cases/case.js
- darts-api-stub/hearings/hearings.js
- darts-api-stub/users.js
- src/app/core/services/error/error-message.service.ts
- src/app/portal/components/case/case.component.ts
- src/app/portal/components/case/hearing-results/hearing-results.component.html
- src/app/portal/components/case/hearing-results/hearing-results.component.ts
- src/app/portal/components/hearing/hearing.component.html
- src/app/portal/components/hearing/hearing.component.ts
https://tools.hmcts.net/jira/browse/DMP-2659
- handling 403 when getting case/hearing transcripts in component
- setting to null, if in error and adding a null check in the template
- fixing endpoints in error-message.service
- amending stub to get more like the real API - responding with 403 when the user has only got TRANSLATION_QA role
> DMP-2659 Fixing Translation QA get transcripts

- src/app/admin/components/courthouses/courthouses.component.spec.ts
- src/app/admin/components/courthouses/create-courthouse/create-courthouse.component.spec.ts
- src/app/admin/components/courthouses/create-courthouse/create-update-courthouse-form/create-update-courthouse-form.component.spec.ts
- src/app/admin/components/courthouses/edit-courthouse/edit-courthouse.component.spec.ts
- src/app/admin/components/groups/group-courthouses/group-courthouses.component.spec.ts
- src/app/admin/components/groups/group-form/group-form.component.ts
- src/app/admin/components/groups/group-record/group-record.component.spec.ts
- src/app/admin/components/groups/groups.component.spec.ts
- src/app/admin/components/users/user-groups/remove-groups/remove-groups.component.spec.ts
- src/app/admin/components/users/user-groups/user-groups/user-groups.component.spec.ts
- src/app/admin/services/groups/groups.service.spec.ts
- src/app/admin/services/user-admin/user-admin.service.spec.ts
- src/app/admin/services/user-admin/user-admin.service.ts
- src/app/core/components/common/audio-player/audio-player.component.spec.ts
- src/app/core/components/common/filters/filters.component.spec.ts
- src/app/core/services/app-config/app-config.service.spec.ts
- src/app/portal/services/audio-request/audio-request.service.spec.ts
- src/app/portal/services/case/case.service.spec.ts
> Increased test coverage

- cypress/e2e/functional/admin-portal/groups-spec.cy.js
- darts-api-stub/admin/security-groups/security-groups.js
- darts-api-stub/admin/security-roles/security-roles.js
- src/app/admin/components/groups/create-edit-group/create-edit-group.component.html
- src/app/admin/components/groups/create-edit-group/create-edit-group.component.spec.ts
- src/app/admin/components/groups/create-edit-group/create-edit-group.component.ts
- src/app/admin/components/groups/group-form/group-form.component.html
- src/app/admin/components/groups/group-form/group-form.component.spec.ts
- src/app/admin/components/groups/group-form/group-form.component.ts
- src/app/admin/components/groups/group-record/group-record.component.html
- src/app/admin/components/groups/group-record/group-record.component.spec.ts
- src/app/admin/components/groups/group-record/group-record.component.ts
- src/app/admin/components/groups/groups.component.html
- src/app/admin/components/groups/groups.component.spec.ts
- src/app/admin/components/users/user-groups/assign-groups/assign-groups.component.spec.ts
- src/app/admin/components/users/user-groups/assign-groups/assign-groups.component.ts
- src/app/admin/components/users/user-groups/user-groups/user-groups.component.html
- src/app/admin/models/groups/security-group-form-values.type.ts
- src/app/admin/models/users/security-role.interface.ts
- src/app/admin/models/users/security-role.type.ts
- src/app/admin/services/groups/groups.service.spec.ts
- src/app/admin/services/groups/groups.service.ts
- src/app/admin/services/user-admin/user-admin.service.spec.ts
- src/app/core/components/layout/header/admin-navigation/admin-navigation.component.ts
- src/app/core/components/layout/header/portal-navigation/portal-navigation.component.ts
[DMP-2317](https://tools.hmcts.net/jira/browse/DMP-2317)
- Create new group functionality
- Fix navigation active page indicator
- Fix SecurityRole role_name / display_name confusion
Note: Staging endpoint is not ready yet for this so stub testing only
> DMP-2317: Create New Group

- cypress/e2e/functional/request-audio-spec.cy.js
- src/app/portal/components/hearing/request-playback-audio/request-playback-audio.component.html
- src/app/portal/components/hearing/request-playback-audio/request-playback-audio.component.ts
- src/app/portal/components/hearing/request-playback-audio/time-input/time-input.component.ts
- src/app/portal/components/hearing/request-transcript/request-times/request-times.component.ts
https://tools.hmcts.net/jira/browse/DMP-2563
Added validation to request audio times to not accept end time before start time.
> DMP-2563 No validation bug on Request Audio for end time before start time

- src/app/admin/components/groups/group-record/group-record.component.html
https://tools.hmcts.net/jira/browse/DMP-2727
- multiple "User" linksi
- adding screen reader text and CSS id attribute
> DMP-2727 Fixing accessibility issue on admin group screen

- src/app/core/components/common/auto-complete/auto-complete.component.html
https://tools.hmcts.net/jira/browse/DMP-2739
As title
> DMP-2739 Accessibility fix for autocomplete labels

- src/app/core/services/cookies/cookies.service.spec.ts
- src/app/core/services/cookies/cookies.service.ts
Set same site to strict for cookie_policy
> DMP-2534 - same site strict set on cookie_policy

- config/custom-environment-variables.json
- config/default.json
- server/app-config.ts
- src/app/core/services/app-config/app-config.service.spec.ts
- src/app/core/services/app-config/app-config.service.ts
- src/app/core/services/dynatrace/dynatrace.service.spec.ts
- src/app/core/services/dynatrace/dynatrace.service.ts
Cookies, dynatrace script url moved outside of secrets
> DMP-2534 Cookies, dynatrace script url moved outside of secrets

- src/app/portal/components/audios/audio-view/audio-view.component.spec.ts
- src/app/portal/components/audios/audio-view/audio-view.component.ts
https://tools.hmcts.net/jira/browse/DMP-2558
- plus tests
> DMP-2558 Don't check playback audio for a download audio request

- src/app/admin/services/retention-policies/retention-policies.service.spec.ts
- src/app/admin/services/retention-policies/retention-policies.service.ts
DMP-2475
Fix duration input values not defaulting to 0 from ''
> DMP-2475: fix duration string bug

- cypress/e2e/functional/admin-portal/retention-policies-spec.cy.js
- src/app/admin/admin.routes.ts
- src/app/admin/components/audio-cache/audio-cache.component.html
- src/app/admin/components/audio-cache/audio-cache.component.spec.ts
- src/app/admin/components/audio-cache/audio-cache.component.ts
- src/app/admin/components/courthouses/courthouse-record/courthouse-record.component.html
- src/app/admin/components/events/events.component.html
- src/app/admin/components/events/events.component.spec.ts
- src/app/admin/components/events/events.component.ts
- src/app/admin/components/file-deletion/file-deletion.component.html
- src/app/admin/components/file-deletion/file-deletion.component.spec.ts
- src/app/admin/components/file-deletion/file-deletion.component.ts
- src/app/admin/components/retention-policies/create-edit-retention-policy/create-edit-retention-policy.component.html
- src/app/admin/components/retention-policies/create-edit-retention-policy/create-edit-retention-policy.component.spec.ts
- src/app/admin/components/retention-policies/create-edit-retention-policy/create-edit-retention-policy.component.ts
- src/app/admin/components/retention-policies/retention-policies.component.html
- src/app/admin/components/retention-policies/retention-policies.component.ts
- src/app/admin/components/retention-policies/retention-policy-form/retention-policy-form.component.html
- src/app/admin/components/system-configuration/system-configuration.component.html
- src/app/admin/components/system-configuration/system-configuration.component.spec.ts
- src/app/admin/components/system-configuration/system-configuration.component.ts
- src/app/admin/components/transcripts/transcripts.component.html
- src/app/admin/components/transcripts/transcripts.component.spec.ts
- src/app/admin/components/transcripts/transcripts.component.ts
- src/app/app.routes.ts
- src/app/core/components/layout/header/admin-navigation/admin-navigation.component.html
https://tools.hmcts.net/jira/browse/DMP-2714
- Add remaining routes and placeholder screens for admin portal so the navigation links somewhere instead of 404 pages
- System configuration screen tabs linked to route and vice versa.
- Designs changes as per figma
- Changed `admin/courthouses/edit/:id` to `admin/courthouses/:id/edit`
> DMP-2714: Admin portal navigation updates

- src/app/admin/components/retention-policies/retention-policy-form/retention-policy-form.component.html
- src/app/admin/components/retention-policies/retention-policy-form/retention-policy-form.component.scss
https://tools.hmcts.net/jira/browse/DMP-2815
Text changes and styling
> DMP-2815: Update retention form to match Figma design

- cypress/e2e/functional/admin-portal/retention-policies-spec.cy.js
- src/app/admin/components/retention-policies/retention-policy-form/retention-policy-form.component.html
- src/app/admin/components/retention-policies/retention-policy-form/retention-policy-form.component.scss
- src/app/admin/components/retention-policies/retention-policy-form/retention-policy-form.component.ts
DMP-2815
Update submit button text based on context to match Figma
> DMP-2815: Update submit button text based on context

- cypress/e2e/functional/case-file-spec.cy.js
- cypress/e2e/functional/case-retention-spec.cy.js
- cypress/e2e/functional/commands.js
- src/app/core/components/app/app.component.html
- src/app/core/components/app/app.component.ts
- src/app/core/components/cookies/cookie-banner/cookie-banner.component.html
- src/app/core/components/cookies/cookie-banner/cookie-banner.component.spec.ts
- src/app/core/components/cookies/cookie-banner/cookie-banner.component.ts
- src/app/core/services/cookies/cookies.service.spec.ts
- src/app/core/services/cookies/cookies.service.ts
- src/app/portal/components/case/case-retention-date/case-retention-date.component.html
https://tools.hmcts.net/jira/browse/DMP-2620
Cookie banner implemented according to GDS specs
> DMP-2620 Cookie banner

- cypress/e2e/functional/case-search-spec.cy.js
- src/app/portal/components/search/search-error/search-error.component.html
- src/app/portal/components/search/search-error/search-error.component.spec.ts
[DMP-2769](https://tools.hmcts.net/jira/browse/DMP-2769)
Update too many results error message to be more reflective of what the backend requires
> DMP-2769: Update case search 102 error message text

- darts-api-stub/roles.js
- src/app/core/services/user/user.service.spec.ts
- src/app/core/services/user/user.service.ts
- src/app/portal/components/hearing/hearing.component.html
- src/app/portal/components/hearing/hearing.component.ts
- src/app/portal/components/hearing/request-playback-audio/request-playback-audio.component.html
- src/app/portal/components/hearing/request-playback-audio/request-playback-audio.component.spec.ts
- src/app/portal/components/hearing/request-playback-audio/request-playback-audio.component.ts
https://tools.hmcts.net/jira/browse/DMP-2640
Stub updated Trina Gulliver to contain courthouseIds: [1, 2, 3, 4]
> DMP-2640 - Audio download request courthouse transcriber, global admin/superuser

- server/views/azuread-b2c-login.html
- src/app/admin/admin.routes.ts
- src/app/app.routes.ts
- src/app/portal/portal.routes.ts
https://tools.hmcts.net/jira/browse/DMP-2721
> DMP-2721 Title updates for routes

- src/app/admin/models/courthouses/region.interface.ts
- src/app/core/components/common/file-upload/file-upload.component.ts
- src/app/core/components/common/filters/checkbox-list/checkbox-list.component.ts
- src/app/portal/components/audios/audios.component.ts
> Some sonar fixes

- src/app/admin/components/transcripts/search-transcripts-form/search-transcripts-form.component.html
- src/app/admin/components/transcripts/search-transcripts-form/search-transcripts-form.component.scss
- src/app/admin/components/transcripts/search-transcripts-form/search-transcripts-form.component.spec.ts
- src/app/admin/components/transcripts/search-transcripts-form/search-transcripts-form.component.ts
- src/app/admin/components/transcripts/transcripts.component.html
- src/app/admin/components/transcripts/transcripts.component.spec.ts
- src/app/admin/components/transcripts/transcripts.component.ts
[DMP-2504](https://tools.hmcts.net/jira/browse/DMP-2504)
Add search form for transcript requests to admin portal
> DMP-2504: ADMIN - Add search transcript form

- src/app/admin/components/retention-policies/retention-policy-form/retention-policy-form.component.ts
[DMP-2930](https://tools.hmcts.net/jira/browse/DMP-2930)
Call `.updateValueAndValidity();` on form to refresh the validation error summary component with recently set error for future start time.
> DMP-2930 - Bugfix missing validation summary message

- src/app/admin/components/users/user-groups/user-groups/user-groups.component.html
- src/app/admin/components/users/user-groups/user-groups/user-groups.component.ts
[DMP-2540](https://tools.hmcts.net/jira/browse/DMP-2540)
Add `aria-label` and `role="status"` to selected text
More info: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/status_role
> DMP-2540: Make user selected group count screen readable

- src/app/admin/components/groups/group-courthouses/group-courthouses.component.html
https://tools.hmcts.net/jira/browse/DMP-2708
Make group courthouses accessible by screen reader
> DMP-2708: Make group courthouse screen readable

- src/app/core/components/cookies/cookies.component.html
[DMP-2866](https://tools.hmcts.net/jira/browse/DMP-2866)
- Removed main tag inside cookies component html as content (parent) component has the main tag wrapping the whole page
> DMP-2866: Cookies page two main landmarks

- src/app/admin/components/transcripts/search-transcripts-form/search-transcripts-form.component.html
[DMP-2936](https://tools.hmcts.net/jira/browse/DMP-2936)
change label
> DMP-2936: Fix label

- cypress/e2e/functional/admin-portal/transcript-requests-spec.cy.js
- darts-api-stub/admin/transcriptions/transcription-workflows.js
- src/app/admin/components/transcripts/view-transcript/view-transcript.component.html
- src/app/admin/components/transcripts/view-transcript/view-transcript.component.spec.ts
- src/app/admin/components/transcripts/view-transcript/view-transcript.component.ts
- src/app/core/components/common/timeline/timeline.component.html
- src/app/core/components/common/timeline/timeline.component.spec.ts
- src/app/core/models/timeline/timeline.type.ts
- src/app/dev/dev.component.ts
[DMP-2538](https://tools.hmcts.net/jira/browse/DMP-2538)
> DMP-2538: Add history tab to transcript request screen

- cypress/e2e/functional/admin-portal/transcript-requests-spec.cy.js
- darts-api-stub/admin/transcriptions/transcription-status.js
- darts-api-stub/admin/transcriptions/transcriptions.js
- darts-api-stub/index.js
- darts-api-stub/transcriptions/transcriptions.js
- src/app/admin/admin.routes.ts
- src/app/admin/components/transcripts/change-transcript-status/change-transcript-status.component.html
- src/app/admin/components/transcripts/change-transcript-status/change-transcript-status.component.spec.ts
- src/app/admin/components/transcripts/change-transcript-status/change-transcript-status.component.ts
- src/app/admin/components/transcripts/transcripts.component.spec.ts
- src/app/admin/components/transcripts/view-transcript/view-transcript.component.html
- src/app/admin/components/transcripts/view-transcript/view-transcript.component.scss
- src/app/admin/components/transcripts/view-transcript/view-transcript.component.spec.ts
- src/app/admin/components/transcripts/view-transcript/view-transcript.component.ts
- src/app/admin/models/transcription/index.ts
- src/app/admin/models/transcription/transcription-status-data.interface.ts
- src/app/admin/models/transcription/transcription-status.ts
- src/app/admin/models/transcription/update-transcript-status-request.interface.ts
- src/app/admin/services/transcription-admin/transcription-admin.service.spec.ts
- src/app/admin/services/transcription-admin/transcription-admin.service.ts
- src/app/core/components/common/details-table/details-table.component.html
- src/app/core/components/common/details-table/details-table.component.ts
- src/app/core/components/common/govuk-banner/govuk-banner.component.ts
[DMP-1265](https://tools.hmcts.net/jira/browse/DMP-1265)
Is dependant upon: https://github.com/hmcts/darts-portal/pull/1043
> DMP-1265: Change transcript status in admin portal

- cypress/e2e/functional/admin-portal/automated-tasks-spec.cy.js
- darts-api-stub/admin/automated-tasks/automated-tasks.js
- darts-api-stub/index.js
- src/app/admin/components/automated-tasks/automated-tasks.component.html
- src/app/admin/components/automated-tasks/automated-tasks.component.scss
- src/app/admin/components/automated-tasks/automated-tasks.component.spec.ts
- src/app/admin/components/automated-tasks/automated-tasks.component.ts
- src/app/admin/components/system-configuration/system-configuration.component.html
- src/app/admin/components/system-configuration/system-configuration.component.ts
- src/app/admin/models/automated-task/automated-task.interface.ts
- src/app/admin/models/automated-task/automated-task.ts
- src/app/admin/services/automated-tasks/automated-tasks.service.spec.ts
- src/app/admin/services/automated-tasks/automated-tasks.service.ts
- src/app/core/services/error/error-message.service.ts
[DMP-2668](https://tools.hmcts.net/jira/browse/DMP-2668)
- Added automated tasks screen to admin portal
- Added service, types and tests 
- Add run task functionality
> DMP-2668: Automated Tasks screen

- src/app/admin/components/groups/groups.component.html
https://tools.hmcts.net/jira/browse/DMP-2604
> DMP-2604 add all roles default to groups admin

- darts-api-stub/admin/transcriptions/transcription-workflows.js
- src/app/admin/services/transcription-admin/transcription-admin.service.spec.ts
- src/app/admin/services/transcription-admin/transcription-admin.service.ts
> DMP-2525 small query param update

- darts-api-stub/admin/users/users.js
- src/app/admin/services/user-admin/user-admin.service.spec.ts
- src/app/admin/services/user-admin/user-admin.service.ts
> DMP-2525 get users transcription details update

- cypress/e2e/functional/your-work-spec.cy.js
- darts-api-stub/transcriptions/transcriptions.js
- src/app/admin/services/transcription-admin/transcription-admin.service.ts
- src/app/portal/components/transcriptions/assign-transcript/assign-transcript.component.ts
- src/app/portal/components/your-work/upload-transcript/upload-transcript.component.ts
- src/app/portal/models/transcriptions/transcription-urgency.interface.ts
- src/app/portal/models/transcriptions/user-transcription-request.interface.ts
- src/app/portal/services/transcription/transcription.service.ts
> DMP-2525 Handle transcriptions without urgency

- src/app/core/components/login/login.component.html
[DMP-2848](https://tools.hmcts.net/jira/browse/DMP-2848)
> DMP-2848: Remove role="radio" attribute from labels on login screen

- cypress/e2e/functional/admin-portal/transcript-requests-spec.cy.js
- src/app/admin/components/transcripts/transcripts.component.spec.ts
- src/app/admin/components/transcripts/transcripts.component.ts
https://tools.hmcts.net/jira/browse/DMP-3029
As per title
> DMP-3029: Add redirect to transcript details page when only one search result

- src/app/admin/services/transcription-admin/transcription-admin.service.spec.ts
- src/app/admin/services/transcription-admin/transcription-admin.service.ts
> DMP-2525 - Admin View Transcript Details - Defaults for current status items

- src/app/admin/services/transcription-admin/transcription-admin.service.ts
> DMP-2525 handle security groups without display names

- src/app/admin/components/transcripts/search-transcripts-form/search-transcripts-form.component.spec.ts
- src/app/admin/components/transcripts/search-transcripts-form/search-transcripts-form.component.ts
- src/app/admin/services/transcription-admin/transcription-admin.service.spec.ts
- src/app/admin/services/transcription-admin/transcription-admin.service.ts
https://tools.hmcts.net/jira/browse/DMP-3030
- Fix date formats for transcript search form `01/01/2021 -> 2021-01-01`
- Set specifc date to from date in specific mode
> DMP-3030: Fix date formats in search request

- cypress/e2e/functional/admin-portal/user-record-spec.cy.js
- src/app/admin/components/users/user-record/user-record.component.html
https://tools.hmcts.net/jira/browse/DMP-2992
> DMP-2992 - Remove audio files tab from user record screen

- src/app/admin/admin.routes.ts
- src/app/admin/components/search/search.component.html
- src/app/admin/components/search/search.component.spec.ts
- src/app/admin/components/search/search.component.ts
- src/app/admin/components/transcripts/transcripts.component.html
- src/app/admin/components/transcripts/transcripts.component.ts
- src/app/app.routes.ts
- src/app/core/components/layout/header/admin-navigation/admin-navigation.component.html
https://tools.hmcts.net/jira/browse/DMP-2987
Updated nav bar, dummy search component, default admin path changed
> DMP-2987 - Updated nav bar, dummy search component, default admin path changed

- src/app/admin/components/courthouses/create-courthouse/create-update-courthouse-confirmation/create-update-courthouse-confirmation.component.ts
No ticket
Null check added to edit courthouse page
> Edit courthouse null check fix

- server/middleware/session.ts
https://tools.hmcts.net/jira/browse/DMP-2784
See ticket for screenshot of setting
> DMP-2784 set strict on same site darts_session

- src/app/admin/components/transcripts/search-transcripts-form/search-transcripts-form.component.html
- src/app/admin/components/transcripts/search-transcripts-form/search-transcripts-form.component.spec.ts
- src/app/admin/components/transcripts/search-transcripts-form/search-transcripts-form.component.ts
- src/app/admin/components/transcripts/transcripts.component.html
- src/app/admin/components/transcripts/transcripts.component.ts
- src/app/admin/constants/transcript-search-form-error-messages.ts
- src/app/core/components/common/datepicker/datepicker.component.html
- src/app/core/components/common/datepicker/datepicker.component.ts
- src/app/core/components/common/specific-or-range-date-picker/specific-or-range-date-picker.component.html
- src/app/core/components/common/specific-or-range-date-picker/specific-or-range-date-picker.component.scss
- src/app/core/components/common/specific-or-range-date-picker/specific-or-range-date-picker.component.spec.ts
- src/app/core/components/common/specific-or-range-date-picker/specific-or-range-date-picker.component.ts
- src/app/core/validators/date-range.validator.ts
- src/app/core/validators/future-date.validator.ts
- src/app/core/validators/real-date.validator.ts
https://tools.hmcts.net/jira/browse/DMP-2959
- Refactored specific or date range form controls into a reusable component
- Added sensible validation logic and messages
> DMP-2959: Search transcript validation errors

- server/server.ts
https://tools.hmcts.net/jira/browse/DMP-2783
> DMP-2783 Add hsts header

- src/app/admin/services/transcription-admin/transcription-admin.service.ts
Add change link to 'Requested' and 'Approved' transcripts as per update to JIRA ticket
> DMP-2525: Add change link to 'Requested' and 'Approved' transcripts

- cypress/e2e/functional/admin-portal/automated-tasks-spec.cy.js
- src/app/admin/components/automated-tasks/view-automated-tasks/view-automated-tasks.component.html
- src/app/admin/components/automated-tasks/view-automated-tasks/view-automated-tasks.component.scss
- src/app/admin/components/automated-tasks/view-automated-tasks/view-automated-tasks.component.ts
https://tools.hmcts.net/jira/browse/DMP-3088
- [Add active inactive tag to view automated tasks](https://github.com/hmcts/darts-portal/pull/1100/commits/2cf6715f47bcefb0972ec6a065e84bcb9236a9a1)
- [Add 'system' as fallback if user cannot be found](https://github.com/hmcts/darts-portal/pull/1100/commits/500d4ac1de26653b19c2f9db1dce83ce5ca396aa)
> DMP-3088: Fix automated task screen

- cypress/e2e/functional/admin-portal/event-mappings-spec.cy.js
- darts-api-stub/admin/event-mappings/event-handlers.js
- darts-api-stub/admin/event-mappings/event-mappings.js
- darts-api-stub/data/.gitignore
- darts-api-stub/data/eventMappings.json
- darts-api-stub/data/securityRoles.json
- darts-api-stub/index.js
- server/controllers/stub-data.ts
- server/stubs/event-mappings.ts
- server/stubs/index.ts
- src/app/admin/admin.routes.ts
- src/app/admin/components/system-configuration/event-mappings/event-mapping-form/event-mapping-form.component.html
- src/app/admin/components/system-configuration/event-mappings/event-mapping-form/event-mapping-form.component.scss
- src/app/admin/components/system-configuration/event-mappings/event-mapping-form/event-mapping-form.component.spec.ts
- src/app/admin/components/system-configuration/event-mappings/event-mapping-form/event-mapping-form.component.ts
- src/app/admin/components/system-configuration/event-mappings/event-mappings.component.html
- src/app/admin/components/system-configuration/event-mappings/event-mappings.component.scss
- src/app/admin/components/system-configuration/event-mappings/event-mappings.component.spec.ts
- src/app/admin/components/system-configuration/event-mappings/event-mappings.component.ts
- src/app/admin/components/system-configuration/system-configuration.component.html
- src/app/admin/components/system-configuration/system-configuration.component.spec.ts
- src/app/admin/components/system-configuration/system-configuration.component.ts
- src/app/admin/models/event-mappings/event-mapping.interface.ts
- src/app/admin/models/event-mappings/event-mapping.type.ts
- src/app/admin/services/event-mappings/event-mappings.service.spec.ts
- src/app/admin/services/event-mappings/event-mappings.service.ts
- src/app/core/components/common/data-table/data-table.component.html
- src/app/core/components/common/data-table/data-table.component.scss
- src/app/core/components/common/data-table/data-table.component.spec.ts
- src/app/core/components/common/data-table/data-table.component.ts
https://tools.hmcts.net/jira/browse/DMP-3037
New filter form and search results for event mappings
Dev only, stub changes
New table caption style has been added
> DMP-3037 - Event mappings change, new form and search results, filters

- darts-api-stub/admin/event-mappings/event-mappings.js
- darts-api-stub/data/.gitignore
- server/controllers/stub-data.ts
https://tools.hmcts.net/jira/browse/DMP-754
Event mappings form/table
> DMP-754 Remove eventmappings from stub

- cypress/e2e/functional/admin-portal/groups-spec.cy.js
- cypress/e2e/functional/admin-portal/user-record-spec.cy.js
- cypress/e2e/functional/admin-portal/users-spec.cy.js
- darts-api-stub/admin/security-groups/security-groups.js
- darts-api-stub/admin/users/users.js
- darts-api-stub/data/securityRoles.json
- src/app/admin/admin.routes.ts
- src/app/admin/components/users/deactivate-user/deactivate-user.component.html
- src/app/admin/components/users/deactivate-user/deactivate-user.component.scss
- src/app/admin/components/users/deactivate-user/deactivate-user.component.spec.ts
- src/app/admin/components/users/deactivate-user/deactivate-user.component.ts
- src/app/admin/components/users/user-record/user-record.component.html
- src/app/admin/components/users/user-record/user-record.component.scss
- src/app/admin/components/users/user-record/user-record.component.ts
- src/app/admin/services/groups/groups.service.spec.ts
- src/app/admin/services/groups/groups.service.ts
- src/app/admin/services/user-admin/user-admin.service.spec.ts
- src/app/admin/services/user-admin/user-admin.service.ts
https://tools.hmcts.net/jira/browse/DMP-2323
- Add deactivate user screen
- Update stub
> DMP-2323: Add deactivate user screen

- src/app/admin/services/transcription-admin/transcription-admin.service.ts
DMP-2525https://tools.hmcts.net/jira/browse/DMP-2525
Small change to hide associated groups when transcript is in approved or requested status
> DMP-2525: [BUG] Hide associated groups for approved/requested transcript

- cypress/e2e/functional/admin-portal/courthouse-record-spec.cy.js
- cypress/e2e/functional/admin-portal/user-record-spec.cy.js
- src/app/admin/components/courthouses/courthouse-record/courthouse-record.component.html
- src/app/admin/components/users/user-record/user-record.component.html
- src/app/core/components/common/details-table/details-table.component.html
https://tools.hmcts.net/jira/browse/DMP-3146
https://tools.hmcts.net/jira/browse/DMP-3136
https://tools.hmcts.net/jira/browse/DMP-3147
https://tools.hmcts.net/jira/browse/DMP-3150
> DMP-3146 DMP-3136 DMP-3147 DMP-3150 Accessibility fixes

- cypress/e2e/functional/admin-portal/transformed-media-spec.cy.js
- darts-api-stub/admin/transformed-media/transformed-media.js
- darts-api-stub/index.js
- server/controllers/stub-data.ts
- server/stubs/index.ts
- server/stubs/transformed-media.ts
- src/app/admin/components/transformed-media/search-transformed-media/search-transformed-media.component.html
- src/app/admin/components/transformed-media/search-transformed-media/search-transformed-media.component.spec.ts
- src/app/admin/components/transformed-media/search-transformed-media/search-transformed-media.component.ts
- src/app/admin/components/transformed-media/transformed-media-search-results/transformed-media-search-results.component.html
- src/app/admin/components/transformed-media/transformed-media-search-results/transformed-media-search-results.component.spec.ts
- src/app/admin/components/transformed-media/transformed-media-search-results/transformed-media-search-results.component.ts
- src/app/admin/models/transformed-media/transformed-media-admin-data.interface.ts
- src/app/admin/models/transformed-media/transformed-media-admin.ts
- src/app/admin/models/transformed-media/transformed-media-search-form.values.ts
- src/app/admin/services/transformed-media/transformed-media.service.spec.ts
- src/app/admin/services/transformed-media/transformed-media.service.ts
- src/app/core/components/common/data-table/data-table.component.html
- src/app/core/components/common/data-table/data-table.component.scss
- src/app/core/components/common/data-table/data-table.component.ts
- src/app/core/pipes/bytes.pipe.spec.ts
- src/app/core/pipes/bytes.pipe.ts
[DMP-3043](https://tools.hmcts.net/jira/browse/DMP-3043)
> DMP-3043: Transformed media search results

- src/app/admin/components/system-configuration/event-mappings/add-update-event-mapping/add-update-event-mapping.component.html
Minor update to fix input css error class
> DMP-2746 fixed input error class

- cypress/e2e/functional/admin-portal/automated-tasks-spec.cy.js
- src/app/admin/components/automated-tasks/automated-task-status/automated-task-status.component.spec.ts
- src/app/admin/components/automated-tasks/automated-task-status/automated-task-status.component.ts
- src/app/admin/components/automated-tasks/automated-tasks.component.html
- src/app/admin/components/automated-tasks/automated-tasks.component.spec.ts
- src/app/admin/components/automated-tasks/automated-tasks.component.ts
- src/app/admin/components/automated-tasks/view-automated-tasks/view-automated-tasks.component.html
- src/app/admin/components/automated-tasks/view-automated-tasks/view-automated-tasks.component.spec.ts
- src/app/admin/components/automated-tasks/view-automated-tasks/view-automated-tasks.component.ts
- src/app/admin/models/automated-task/automated-task-status.ts
https://tools.hmcts.net/jira/browse/DMP-3079
Adding task name context to banner.
> DMP-3079 Adding task name to task status banner

- cypress/e2e/functional/admin-portal/transcript-requests-spec.cy.js
- src/app/admin/components/transcripts/view-transcript/view-transcript.component.html
- src/app/portal/components/audios/audio-view/audio-view.component.html
https://tools.hmcts.net/jira/browse/DMP-3190
- accessibility fix
- using span instead of h1
> DMP-3190 Amending transcript and audio captions

- src/app/admin/components/system-configuration/event-mappings/event-mappings.component.html
> DMP-754 Bug remove change link for inactive event mappings

- src/app/admin/models/event-mappings/event-mapping.interface.ts
- src/app/admin/services/event-mappings/event-mappings.service.ts
> DMP-2746 Bug, sub type to null if empty string, event mappings add

- cypress/e2e/functional/admin-portal/transformed-media-spec.cy.js
- darts-api-stub/admin/media-requests/media-requests.js
- src/app/admin/admin.routes.ts
- src/app/admin/components/transformed-media/change-owner-transformed-media/change-owner-transformed-media.component.html
- src/app/admin/components/transformed-media/change-owner-transformed-media/change-owner-transformed-media.component.scss
- src/app/admin/components/transformed-media/change-owner-transformed-media/change-owner-transformed-media.component.spec.ts
- src/app/admin/components/transformed-media/change-owner-transformed-media/change-owner-transformed-media.component.ts
- src/app/admin/components/transformed-media/view-transformed-media/view-transformed-media.component.html
- src/app/admin/components/transformed-media/view-transformed-media/view-transformed-media.component.spec.ts
- src/app/admin/components/transformed-media/view-transformed-media/view-transformed-media.component.ts
- src/app/admin/services/transformed-media/transformed-media.service.spec.ts
- src/app/admin/services/transformed-media/transformed-media.service.ts
[DMP-3045](https://tools.hmcts.net/jira/browse/DMP-3045)
> Dmp 3045: Change media request owner from transformed media

- src/app/admin/components/users/user-transcripts/user-transcripts.component.html
- src/app/admin/components/users/user-transcripts/user-transcripts.component.ts
> DMP-2229 Bug fix for click link

- cypress/e2e/functional/admin-portal/event-mappings-spec.cy.js
- darts-api-stub/admin/event-mappings/event-mappings.js
- src/app/admin/admin.routes.ts
- src/app/admin/components/system-configuration/event-mappings/add-update-event-mapping/add-update-event-mapping.component.html
- src/app/admin/components/system-configuration/event-mappings/add-update-event-mapping/add-update-event-mapping.component.scss
- src/app/admin/components/system-configuration/event-mappings/add-update-event-mapping/add-update-event-mapping.component.spec.ts
- src/app/admin/components/system-configuration/event-mappings/add-update-event-mapping/add-update-event-mapping.component.ts
- src/app/admin/components/system-configuration/event-mappings/event-mappings.component.html
- src/app/admin/components/system-configuration/system-configuration.component.html
- src/app/admin/components/system-configuration/system-configuration.component.ts
- src/app/admin/models/event-mappings/event-mapping-form-values.interface.ts
- src/app/admin/services/event-mappings/event-mappings.service.spec.ts
- src/app/admin/services/event-mappings/event-mappings.service.ts
https://tools.hmcts.net/jira/browse/DMP-2763
> DMP-2763 Edit event mapping changes

- cypress/e2e/functional/admin-portal/transcript-requests-spec.cy.js
- darts-api-stub/admin/medias/medias.js
- darts-api-stub/admin/transcriptions/transcription-documents.js
- darts-api-stub/transcriptions/transcriptions.js
- src/app/admin/components/transcripts/search-completed-transcripts-results/search-completed-transcripts-results.component.spec.ts
- src/app/admin/components/transcripts/search-completed-transcripts-results/search-completed-transcripts-results.component.ts
- src/app/admin/components/transcripts/transcripts.component.spec.ts
- src/app/admin/components/transcripts/view-transcription-document/view-transcription-document.component.html
- src/app/admin/components/transcripts/view-transcription-document/view-transcription-document.component.scss
- src/app/admin/components/transcripts/view-transcription-document/view-transcription-document.component.spec.ts
- src/app/admin/components/transcripts/view-transcription-document/view-transcription-document.component.ts
- src/app/admin/components/transformed-media/associated-audio-table/associated-audio-table.component.html
- src/app/admin/components/transformed-media/associated-audio-table/associated-audio-table.component.spec.ts
- src/app/admin/components/transformed-media/associated-audio-table/associated-audio-table.component.ts
- src/app/admin/components/transformed-media/view-transformed-media/view-transformed-media.component.html
- src/app/admin/components/transformed-media/view-transformed-media/view-transformed-media.component.spec.ts
- src/app/admin/components/transformed-media/view-transformed-media/view-transformed-media.component.ts
- src/app/admin/models/transcription/index.ts
- src/app/admin/models/transcription/transcription-document-data.interface.ts
- src/app/admin/models/transcription/transcription-document-search-result-data.interface.ts
- src/app/admin/models/transcription/transcription-document-search-result.ts
- src/app/admin/models/transcription/transcription-document.ts
- src/app/admin/services/transcription-admin/transcription-admin.service.spec.ts
- src/app/admin/services/transcription-admin/transcription-admin.service.ts
- src/app/admin/services/transformed-media/transformed-media.service.spec.ts
- src/app/admin/services/transformed-media/transformed-media.service.ts
[DMP-2729](https://tools.hmcts.net/jira/browse/DMP-2729)
Implement view transcription file details page
Refactored associated media table into a shared component
Renamed some types to make more sense
> DMP-2729: Transcription file details page

- cypress/e2e/functional/admin-portal/event-mappings-spec.cy.js
- darts-api-stub/admin/event-mappings/event-mappings.js
- darts-api-stub/data/eventMappings.json
- src/app/admin/admin.routes.ts
- src/app/admin/components/system-configuration/event-mappings/add-update-event-mapping/add-update-event-mapping.component.html
- src/app/admin/components/system-configuration/event-mappings/add-update-event-mapping/add-update-event-mapping.component.ts
- src/app/admin/components/system-configuration/event-mappings/delete-event-mapping/delete-event-mapping.component.html
- src/app/admin/components/system-configuration/event-mappings/delete-event-mapping/delete-event-mapping.component.spec.ts
- src/app/admin/components/system-configuration/event-mappings/delete-event-mapping/delete-event-mapping.component.ts
- src/app/admin/components/system-configuration/system-configuration.component.html
- src/app/admin/components/system-configuration/system-configuration.component.ts
- src/app/admin/models/event-mappings/event-mapping.interface.ts
- src/app/admin/models/event-mappings/event-mapping.type.ts
- src/app/admin/services/event-mappings/event-mappings.service.ts
- src/app/core/components/common/delete/delete.component.html
- src/app/core/components/common/delete/delete.component.ts
https://tools.hmcts.net/jira/browse/DMP-2764
> DMP-2764 Delete event mapping

- darts-api-stub/admin/retention-policies/retention-policies.js
- src/app/core/services/error/error-message.service.ts
https://tools.hmcts.net/jira/browse/DMP-2888
> DMP-2888 handle 409 for retention policies

- src/app/admin/components/transformed-media/search-transformed-media-form/search-transformed-media-form.component.html
- src/app/admin/components/transformed-media/search-transformed-media-form/search-transformed-media-form.component.ts
- src/app/admin/constants/transcript-search-form-error-messages.ts
- src/app/admin/services/transformed-media/transformed-media.service.spec.ts
- src/app/admin/services/transformed-media/transformed-media.service.ts
As title
Also added number only validation for request id
> DMP-2678 mapping to null for empty string, transformed media search

- server/routes.ts
- server/server.ts
[N/A](https://tools.hmcts.net/jira/browse/DMP-3255)
To avoid additional `darts_session` Set-Cookie headers from these requests.
> Moving B2C template routes to before session middleware

- cypress/e2e/functional/admin-portal/event-mappings-spec.cy.js
- src/app/admin/components/system-configuration/event-mappings/add-update-event-mapping/add-update-event-mapping.component.html
- src/app/admin/components/system-configuration/event-mappings/add-update-event-mapping/add-update-event-mapping.component.spec.ts
- src/app/admin/components/system-configuration/event-mappings/add-update-event-mapping/add-update-event-mapping.component.ts
https://tools.hmcts.net/jira/browse/DMP-3028
> DMP-3028 - Type subtype validation on add event mapping

- darts-api-stub/admin/medias/medias.js
- darts-api-stub/admin/security-groups/security-groups.js
- darts-api-stub/admin/transformed-media/transformed-media.js
- src/app/admin/components/transcripts/view-transcription-document/view-transcription-document.component.spec.ts
- src/app/admin/components/transformed-media/associated-audio-table/associated-audio-table.component.spec.ts
- src/app/admin/components/transformed-media/associated-audio-table/associated-audio-table.component.ts
- src/app/admin/components/transformed-media/search-transformed-media/search-transformed-media.component.ts
- src/app/admin/components/transformed-media/transformed-media-search-results/transformed-media-search-results.component.ts
- src/app/admin/components/transformed-media/view-transformed-media/view-transformed-media.component.spec.ts
- src/app/admin/components/transformed-media/view-transformed-media/view-transformed-media.component.ts
- src/app/admin/models/transformed-media/associated-media-data.interface.ts
- src/app/admin/models/transformed-media/associated-media.ts
- src/app/admin/models/transformed-media/transformed-media-admin-data.interface.ts
- src/app/admin/models/transformed-media/transformed-media-admin.ts
- src/app/admin/services/transformed-media/transformed-media.service.spec.ts
- src/app/admin/services/transformed-media/transformed-media.service.ts
https://tools.hmcts.net/jira/browse/DMP-2679
Updated code as /api/admin/transformed-medias/:id was not as expected in Stub
> DMP-2679 - Fix transformed media view

- src/app/admin/components/transcripts/search-completed-transcripts-results/search-completed-transcripts-results.component.ts
- src/app/admin/models/transcription/transcription-search-request.interface.ts
- src/app/admin/services/transcription-admin/transcription-admin.service.spec.ts
- src/app/admin/services/transcription-admin/transcription-admin.service.ts
https://tools.hmcts.net/jira/browse/DMP-3139
Omitted transcription_id from completed transcript search
> DMP-3139 Fixes for completed transcript search

- src/app/admin/components/transformed-media/search-transformed-media/search-transformed-media.component.spec.ts
- src/app/admin/components/transformed-media/search-transformed-media/search-transformed-media.component.ts
https://tools.hmcts.net/jira/browse/DMP-3274
> DMP-3274 - Transformed Media - Redirect to view page if 1 result returned

- server/controllers/authentication.ts
- server/middleware/is-authenticated.ts
- server/server.ts
- server/utils/authentication-utils.ts
- src/app/core/services/auth/auth.service.ts
> Removing debug log messages

- config/default.json
- cypress/e2e/functional/error-spec.cy.js
- cypress/e2e/functional/request-audio-spec.cy.js
- cypress/e2e/functional/your-audio-spec.cy.js
https://tools.hmcts.net/jira/browse/DMP-3035
Updating support contact details.
> DMP-3035 Updating support contact details

- src/app/admin/components/automated-tasks/automated-tasks.component.ts
- src/app/core/components/common/data-table/data-table.component.html
- src/app/core/models/data-table/data-table-column.interface.ts
- src/app/portal/components/audios/audios.component.ts
- src/app/portal/components/transcriptions/transcription-requests/transcription-requests.component.ts
- src/app/portal/components/transcriptions/transcriptions.component.ts
- src/app/portal/components/your-work/your-work.component.ts
https://tools.hmcts.net/jira/browse/DMP-2794
> DMP-2794: a11y - Add visually hidden headers to empty <th>

- yarn-audit-known-issues
> Removing audit known issues

- src/app/portal/components/hearing/request-transcript/request-transcript.component.ts
- yarn-audit-known-issues
https://tools.hmcts.net/jira/browse/DMP-2794
> DMP-2794: Add <th> hidden text

- src/app/portal/services/case/case.service.spec.ts
- src/app/portal/services/case/case.service.ts
https://tools.hmcts.net/jira/browse/DMP-3263
- removing duplicates from "courtroom" array when processing search results
> DMP-3263 Fixing multiple idential courtrooms showing as "Multiple" in case search

- darts-api-stub/index.js
- src/app/admin/services/transcription-admin/transcription-admin.service.spec.ts
- src/app/admin/services/transcription-admin/transcription-admin.service.ts
Reverts hmcts/darts-portal#1188
> Revert "DMP-1662 API reference character change"

- src/app/core/components/layout/header/header.component.html
- src/app/core/components/layout/header/header.component.spec.ts
https://tools.hmcts.net/jira/browse/DMP-3234
https://tools.hmcts.net/jira/browse/DMP-3235
> DMP-3234 admin/user portal links, fix deprecated RouterTestingModule, unit tests

- cypress/e2e/functional/admin-portal/search.spec.cy.js
- src/app/admin/components/search/search-form/search-form.component.html
- src/app/admin/components/search/search-form/search-form.component.scss
- src/app/admin/components/search/search-form/search-form.component.spec.ts
- src/app/admin/components/search/search-form/search-form.component.ts
- src/app/admin/components/search/search.component.html
- src/app/admin/components/search/search.component.spec.ts
- src/app/admin/components/search/search.component.ts
- src/app/admin/services/courthouses/courthouse.service.spec.ts
- src/app/admin/services/courthouses/courthouses.service.ts
- src/app/core/components/common/courthouse/courthouse.component.html
- src/app/core/components/common/courthouse/courthouse.component.ts
https://tools.hmcts.net/jira/browse/DMP-1190
Add admin search form
> DMP-1190: ADMIN - Add search form for cases, hearings, events and audio

- src/app/core/pipes/join.spec.ts
- src/app/core/pipes/join.ts
- src/app/portal/components/case/case-file/case-file.component.html
https://tools.hmcts.net/jira/browse/DMP-3304
- modifying the `join` pipe to handle this
> DMP-3304 Adding "-" for missing prosecutor, defence and defendant values

- cypress/e2e/functional/admin-portal/transcript-requests-spec.cy.js
- src/app/admin/components/transcripts/view-transcription-document/transcript-file-advanced-detail/transcript-file-advanced-detail.component.html
- src/app/admin/components/transcripts/view-transcription-document/transcript-file-basic-detail/transcript-file-basic-detail.component.html
N/A
Removing "Transcript ID" from transcript doc screen
- it's the same as "Request ID"
Fixing date "at" time issue for optional fields
- incorporating the "at" into the date time formatting
> Hide transcript document screen fixes

- cypress/e2e/functional/admin-portal/hide-or-delete-file-spec.cy.js
- cypress/e2e/functional/admin-portal/transformed-media-spec.cy.js
- darts-api-stub/admin/medias/medias.js
- src/app/admin/components/audio-file/audio-file.component.html
- src/app/admin/components/audio-file/audio-file.component.ts
- src/app/admin/components/file-deletion/file-hide-or-delete/file-hide-or-delete.component.html
- src/app/admin/components/file-deletion/file-hide-or-delete/file-hide-or-delete.component.spec.ts
- src/app/admin/components/file-deletion/file-hide-or-delete/file-hide-or-delete.component.ts
- src/app/admin/components/transformed-media/associated-audio-hide-delete/associated-audio-hide-delete.component.html
- src/app/admin/components/transformed-media/associated-audio-hide-delete/associated-audio-hide-delete.component.scss
- src/app/admin/components/transformed-media/associated-audio-hide-delete/associated-audio-hide-delete.component.spec.ts
- src/app/admin/components/transformed-media/associated-audio-hide-delete/associated-audio-hide-delete.component.ts
- src/app/admin/components/transformed-media/associated-audio-table/associated-audio-table.component.html
- src/app/admin/components/transformed-media/associated-audio-table/associated-audio-table.component.ts
- src/app/admin/models/hidden-reasons/file-hide-data.interface.ts
- src/app/admin/models/hidden-reasons/file-hide.ts
- src/app/admin/services/transcription-admin/transcription-admin.service.ts
- src/app/admin/services/transformed-media/transformed-media.service.spec.ts
- src/app/admin/services/transformed-media/transformed-media.service.ts
https://tools.hmcts.net/jira/browse/DMP-2728
Associated audio hide functionality for audio files
Test locally via /admin/audio-file/0
> DMP-2728 Changes for associated audio hide flow, unit tests

- darts-api-stub/authentication/index.js
- darts-api-stub/users.js
- darts-api-stub/views/login.ejs
- server/controllers/authentication.ts
- server/types/classes/userState.ts
- src/app/app.routes.spec.ts
- src/app/core/models/user/user-state.interface.ts
- src/app/core/services/user/user.service.spec.ts
- src/app/core/services/user/user.service.ts
- src/app/portal/components/hearing/hearing.component.spec.ts
- src/app/portal/components/hearing/request-playback-audio/request-playback-audio.component.spec.ts
[DMP-2975](https://tools.hmcts.net/jira/browse/DMP-2975)
Update stub users
Update node layer
> DMP-2975: Add isActive flag to userState

- darts-api-stub/admin/security-roles/security-roles.js
- darts-api-stub/data/securityRoles.json
- darts-api-stub/roles.js
- server/controllers/download.ts
- src/app/admin/components/courthouses/courthouse-record/courthouse-record.component.spec.ts
- src/app/core/models/user/role-name.type.ts
- src/app/core/services/user/user.service.spec.ts
- src/app/core/services/user/user.service.ts
- src/app/portal/portal.routes.ts
https://tools.hmcts.net/jira/browse/DMP-3390
Update the literal role name from 'JUDGE' to 'JUDICIARY'
> DMP-3390: Update JUDGE role name to JUDICIARY

- cypress/e2e/functional/admin-portal/transcript-requests-spec.cy.js
- src/app/admin/components/transcripts/view-transcription-document/transcript-file-advanced-detail/transcript-file-advanced-detail.component.html
https://tools.hmcts.net/jira/browse/DMP-3247
Advanced detail table updates
> DMP-3247 - transcript file updates

- src/app/portal/components/case/case-file/case-file.component.html
- src/app/portal/components/case/case.component.html
https://tools.hmcts.net/jira/browse/DMP-2796
> DMP-2796 ally fixes for heading levels

- src/app/admin/components/transcripts/search-transcripts-form/search-transcripts-form.component.html
- src/app/admin/components/transcripts/search-transcripts-form/search-transcripts-form.component.ts
- src/app/admin/components/transcripts/transcripts.component.html
- src/app/admin/components/transcripts/transcripts.component.spec.ts
- src/app/admin/components/transformed-media/search-transformed-media-form/search-transformed-media-form.component.html
- src/app/admin/components/transformed-media/search-transformed-media-form/search-transformed-media-form.component.ts
- src/app/admin/components/transformed-media/search-transformed-media/search-transformed-media.component.html
- src/app/admin/components/transformed-media/search-transformed-media/search-transformed-media.component.spec.ts
- src/app/admin/components/transformed-media/search-transformed-media/search-transformed-media.component.ts
https://tools.hmcts.net/jira/browse/DMP-3370
> DMP-3370 - Bug fix - courthouse autocomplete across transcript, media forms

- cypress/e2e/functional/admin-portal/user-record-spec.cy.js
- darts-api-stub/admin/users/users.js
- darts-api-stub/users.js
- src/app/admin/components/users/activate-user/activate-user.component.spec.ts
- src/app/admin/components/users/activate-user/activate-user.component.ts
- src/app/admin/components/users/user-record/user-record.component.html
- src/app/admin/components/users/user-record/user-record.component.spec.ts
- src/app/admin/components/users/user-record/user-record.component.ts
[DMP-3232](https://tools.hmcts.net/jira/browse/DMP-3232)
> DMP-3232: Handle 409 error on user activation

- server/controllers/download.ts
https://tools.hmcts.net/jira/browse/DMP-3430
Fixing annotation document download
> DMP-3430 Fixing annotation document download

- server/assets/stylesheets/change-password.css
- server/assets/stylesheets/login.css
- server/assets/stylesheets/mfa.css
- server/assets/stylesheets/reset-password.css
- src/app/core/components/common/data-table/data-table.component.scss
- src/app/portal/components/hearing/request-playback-audio/time-input/time-input.component.scss
- src/app/portal/components/search/case-search-results/case-search-results.component.scss
- src/assets/datepicker.scss
[DMP-2797](https://tools.hmcts.net/jira/browse/DMP-2797)
> DMP-2797: Migrate font-size overrides from px to rem

- src/app/portal/services/case/case.service.ts
https://tools.hmcts.net/jira/browse/DMP-3456
Returning case hearing in asc order from the service function
> DMP-3456 Bug - sort case hearings by asc

- src/app/admin/components/file-deletion/file-hide-or-delete/file-hide-or-delete.component.html
https://tools.hmcts.net/jira/browse/DMP-3369
> DMP-3369 Hide or delete file radio buttons, update label for attribute

- src/app/admin/components/transcripts/search-transcripts-form/search-transcripts-form.component.html
https://tools.hmcts.net/jira/browse/DMP-2967
> DMP-2697 Transcript search, radio label a11y fixes

- src/app/core/components/common/datepicker/datepicker.component.html
- src/app/core/components/common/datepicker/datepicker.component.ts
- src/app/core/components/common/specific-or-range-date-picker/specific-or-range-date-picker.component.html
https://tools.hmcts.net/jira/browse/DMP-2966
> DMP-2966 - A11y - @input aria-label for datepicker component

- src/app/admin/components/courthouses/courthouse-record/courthouse-record.component.spec.ts
- src/app/admin/components/courthouses/courthouse-record/courthouse-record.component.ts
[DMP-3148](https://tools.hmcts.net/jira/browse/DMP-3148)
> DMP-3148: Add checkbox label to courthouse users

- cypress/e2e/functional/admin-portal/hide-or-delete-file-spec.cy.js
- darts-api-stub/admin/medias/medias.js
- src/app/admin/components/audio-file/audio-file.component.html
- src/app/admin/components/audio-file/audio-file.component.spec.ts
- src/app/admin/components/audio-file/audio-file.component.ts
- src/app/admin/components/common/hidden-file-banner/hidden-file-banner.component.html
- src/app/admin/components/common/hidden-file-banner/hidden-file-banner.component.ts
- src/app/admin/services/transformed-media/transformed-media.service.spec.ts
- src/app/admin/services/transformed-media/transformed-media.service.ts
https://tools.hmcts.net/jira/browse/DMP-3384
> DMP-3384 unhide audio file

- server/controllers/stub-data.ts
- src/app/admin/components/search/search.component.html
[DMP-3317](https://tools.hmcts.net/jira/browse/DMP-3317)
[DMP-3315](https://tools.hmcts.net/jira/browse/DMP-3315)
Removed stubs for hearing and audio as the API endpoints are now available
Fixed bug where "No results found" was being displayed whilst loading search results
> DMP-3315 & DMP-3317: Remove hearings and audio stubbed search results.

- cypress/e2e/functional/admin-portal/transcript-requests-spec.cy.js
- darts-api-stub/transcriptions/transcriptions.js
- src/app/admin/components/transcripts/view-transcription-document/transcript-file-basic-detail/transcript-file-basic-detail.component.html
- src/app/portal/models/transcriptions/transcription-details.interface.ts
- src/app/portal/models/transcriptions/transcription-details.type.ts
- src/app/portal/services/mapping/mapping.service.ts
[DMP-3406](https://tools.hmcts.net/jira/browse/DMP-3406)
`Requested date` field is in the ticket but not in the Figma so had to guess the DateTime format
`hide_request_from_requestor` new prop added to the response for `Removed from user transcripts` field
> DMP-3406: Add extra fields to transcript request details

- src/app/admin/components/transformed-media/search-transformed-media/search-transformed-media.component.ts
[DMP-3429](https://tools.hmcts.net/jira/browse/DMP-3429)
> DMP-3429: Bug fix - Transformed media search loading spinner

- src/app/admin/components/transcripts/search-transcripts-form/search-transcripts-form.component.html
- src/app/admin/components/transcripts/search-transcripts-form/search-transcripts-form.component.ts
- src/app/admin/components/transformed-media/search-transformed-media-form/search-transformed-media-form.component.html
- src/app/admin/components/transformed-media/search-transformed-media-form/search-transformed-media-form.component.ts
- src/app/admin/services/transcription-admin/transcription-admin.service.ts
https://tools.hmcts.net/jira/browse/DMP-3522
Bug fix to ensure courthouse values are mapped
> DMP-3522 Bug fix - Rename courthouse form control across transcript/media searches

- src/app/admin/components/transcripts/view-transcript/view-transcript.component.html
- src/app/admin/components/transcripts/view-transcript/view-transcript.component.ts
- src/app/portal/models/transcriptions/transcription-details.type.ts
- src/app/portal/services/mapping/mapping.service.ts
- src/styles.scss
[DMP-3428](https://tools.hmcts.net/jira/browse/DMP-3428)
[DMP-3516](https://tools.hmcts.net/jira/browse/DMP-3516)
- Fixed back button white space issue globally, this needs to be visually checked in all instances of `.govuk-back-link`
- Fix null start and end time
- Remove breadcrumb
- Make title request ID
> DMP-3428: View transcript bugs

- src/app/admin/components/audio-file/advanced-audio-file-details/advanced-audio-file-details.component.html
- src/app/admin/components/audio-file/basic-audio-file-details/basic-audio-file-details.component.html
> DMP-2709 remove leading zero from audio file times

- cypress/e2e/functional/admin-portal/courthouse-record-spec.cy.js
- cypress/e2e/functional/admin-portal/transformed-media-spec.cy.js
https://tools.hmcts.net/jira/browse/DMP-3215
> DMP-3215 a11y fixes for Cypress

- src/app/admin/components/transcripts/search-completed-transcripts-results/search-completed-transcripts-results.component.html
- src/app/admin/components/transcripts/search-completed-transcripts-results/search-completed-transcripts-results.component.spec.ts
- src/app/admin/components/transcripts/search-completed-transcripts-results/search-completed-transcripts-results.component.ts
https://tools.hmcts.net/jira/browse/DMP-3469
> DMP-3469: Add request ID column to completed transcript results

- src/app/admin/components/audio-file/audio-file.component.html
- src/app/admin/components/audio-file/audio-file.component.ts
[DMP-3546](https://tools.hmcts.net/jira/browse/DMP-3546)
> DMP-3546: Add back button to audio file screen

- cypress/e2e/functional/request-audio-spec.cy.js
- darts-api-stub/audios/index.js
> DMP-3526 - Allow preview audio FT to pass in succession

- server/controllers/stub-data.ts
[DMP-2963](https://tools.hmcts.net/jira/browse/DMP-2963)
Endpoint is now available so removing stubbed response
> DMP-2963: Remove event / court log stub

- src/app/admin/components/transformed-media/view-transformed-media/view-transformed-media.component.html
https://tools.hmcts.net/jira/browse/DMP-3557
> DMP-3557 Transformed media - replace breadcrumb with back link

- src/app/admin/components/common/hidden-file-banner/hidden-file-banner.component.html
- src/app/admin/components/search/audio-search-results/audio-search-results.component.html
- src/app/admin/components/search/audio-search-results/audio-search-results.component.ts
N/A
Add "." to audio file hidden banner
Remove hearing date column
> Small bugfixes

- cypress/e2e/functional/case-file-spec.cy.js
- cypress/e2e/functional/request-transcript-spec.cy.js
- src/app/admin/components/transcripts/search-transcripts-form/search-transcripts-form.component.html
- src/app/admin/components/transformed-media/search-transformed-media-form/search-transformed-media-form.component.html
- src/app/core/components/common/reporting-restriction/reporting-restriction.component.html
- src/app/portal/components/case/case-file/case-file.component.html
- src/app/portal/components/hearing/hearing-file/hearing-file.component.html
- src/app/portal/components/hearing/request-transcript/request-transcript-confirmation/request-transcript-confirmation.component.html
- src/app/portal/components/hearing/request-transcript/request-transcript.component.html
https://tools.hmcts.net/jira/browse/DMP-2796
> DMP-2796 - A11y heading levels changed

- cypress/e2e/functional/admin-portal/search.spec.cy.js
- server/controllers/stub-data.ts
- server/stubs/events.ts
- src/app/admin/components/search/search-form/search-form.component.html
- src/app/admin/components/search/search-form/search-form.component.spec.ts
- src/app/admin/components/search/search-form/search-form.component.ts
- src/app/admin/components/search/search.component.html
- src/app/admin/components/search/search.component.spec.ts
- src/app/admin/components/search/search.component.ts
- src/app/admin/models/search/admin-search-results-tab.ts
- src/app/admin/services/admin-search/admin-search.service.spec.ts
- src/app/admin/services/admin-search/admin-search.service.ts
https://tools.hmcts.net/jira/browse/DMP-3475
> DMP-3475: Admin Search - Persist form state and search results

- cypress/e2e/functional/transcript-requests-spec.cy.js
- cypress/e2e/functional/your-work-spec.cy.js
- darts-api-stub/transcriptions/transcriptions.js
> DMP-3526 - Request transcripts, allow ft to run in isolation

- darts-api-stub/cases/case.js
- src/app/admin/components/courthouses/create-courthouse/create-courthouse.component.ts
- src/app/admin/components/users/create-user/create-user.component.ts
- src/app/core/components/common/data-table/data-table.component.ts
Removal of redundant api, removal of some redundant to do comments
> Remove redundant stub api, remove some todos

- cypress/e2e/functional/admin-portal/hide-or-delete-file-spec.cy.js
- cypress/e2e/functional/admin-portal/transformed-media-spec.cy.js
- src/app/admin/components/transformed-media/associated-audio-table/associated-audio-table.component.html
- src/app/admin/components/transformed-media/view-transformed-media/view-transformed-media.component.html
> Add seconds + AM/PM to transformed media time format

- src/app/core/components/app/app.component.html
- src/app/core/components/layout/content/content.component.html
- src/styles.scss
[DMP-3024](https://tools.hmcts.net/jira/browse/DMP-3024)
- Fixed collapsing gutters on smaller displays
- Fixed some code formatting / self closing tags
> DMP-3024: Fix collapsing gutters on smaller displays

- src/app/portal/components/hearing/hearing.component.scss
[DMP-3588](https://tools.hmcts.net/jira/browse/DMP-3588)
Fix back button spacing
> DMP-3588: Fix back button spacing

- cypress/e2e/functional/upload-transcript-spec.cy.js
- cypress/e2e/functional/view-transcript-spec.cy.js
- darts-api-stub/transcriptions/transcriptions.js
Added missing -spec expected in Cypress filenames. These tests were never included in functional test running so this change includes fixes for view & upload transcript.
> Functional test fixes for view/upload transcript

- cypress/e2e/functional/transcript-requests-spec.cy.js
- src/app/portal/components/transcriptions/assign-transcript/assign-transcript.component.ts
- src/app/portal/components/your-work/upload-transcript/upload-transcript.component.html
- src/app/portal/components/your-work/upload-transcript/upload-transcript.component.spec.ts
- src/app/portal/components/your-work/upload-transcript/upload-transcript.component.ts
- src/app/portal/services/transcription/transcription.service.spec.ts
- src/app/portal/services/transcription/transcription.service.ts
https://tools.hmcts.net/jira/browse/DMP-3599
> DMP-3599 Refactoring mapping logic into service functions

- src/app/admin/components/audio-file/advanced-audio-file-details/advanced-audio-file-details.component.html
- src/app/admin/components/audio-file/advanced-audio-file-details/advanced-audio-file-details.component.scss
Remove show versions link from audio file adv details
> Remove show versions link from audio file adv details

- src/app/admin/components/automated-tasks/automated-tasks.component.html
- src/app/admin/components/automated-tasks/automated-tasks.component.ts
- src/app/admin/components/retention-policies/retention-policies.component.html
- src/app/admin/components/retention-policies/retention-policies.component.ts
- src/app/admin/components/transcripts/transcripts.component.html
- src/app/admin/components/transcripts/transcripts.component.spec.ts
- src/app/admin/components/transcripts/transcripts.component.ts
- src/app/admin/components/transcripts/view-transcript/view-transcript.component.html
- src/app/admin/components/transcripts/view-transcript/view-transcript.component.ts
- src/app/admin/components/transformed-media/search-transformed-media/search-transformed-media.component.html
- src/app/admin/components/transformed-media/view-transformed-media/view-transformed-media.component.html
- src/app/admin/components/transformed-media/view-transformed-media/view-transformed-media.component.ts
- src/app/portal/components/transcriptions/assign-transcript/assign-transcript.component.html
- src/app/portal/components/transcriptions/assign-transcript/assign-transcript.component.ts
- src/app/portal/components/your-work/upload-transcript/upload-transcript.component.html
- src/app/portal/components/your-work/upload-transcript/upload-transcript.component.ts
https://tools.hmcts.net/jira/browse/DMP-3586
> DMP-3586 - Loading spinner updates

- src/app/core/components/common/data-table/data-table.component.html
https://tools.hmcts.net/jira/browse/DMP-2846
Confirmed output with Kyle H
> DMP-2846 Aria labels added to th in data table for sortable/non sortable columns

- darts-api-stub/transcriptions/transcriptions.js
- src/app/portal/components/transcriptions/view-transcript/approved-transcript/approved-transcript.component.html
- src/app/portal/services/transcription/transcription.service.spec.ts
- src/app/portal/services/transcription/transcription.service.ts
https://tools.hmcts.net/jira/browse/DMP-3472
> DMP-3472: Fix start and end time null bug

- cypress/e2e/functional/hearing-screen-spec.cy.js
- cypress/e2e/functional/request-transcript-spec.cy.js
- cypress/e2e/functional/view-transcript-spec.cy.js
- darts-api-stub/transcriptions/transcriptions.js
- src/app/portal/components/hearing/hearing.component.html
- src/app/portal/components/hearing/request-transcript/request-times/request-times.component.html
- src/app/portal/components/hearing/request-transcript/request-times/request-times.component.spec.ts
- src/app/portal/components/hearing/request-transcript/request-times/request-times.component.ts
- src/app/portal/components/hearing/request-transcript/request-transcript.component.html
- src/app/portal/components/hearing/request-transcript/request-transcript.component.ts
https://tools.hmcts.net/jira/browse/DMP-3471
> DMP-3471 Request transcript - Added outside times validation, ft

- cypress/e2e/functional/admin-portal/event-mappings-spec.cy.js
- src/app/admin/components/system-configuration/event-mappings/add-update-event-mapping/add-update-event-mapping.component.html
- src/app/admin/components/system-configuration/event-mappings/add-update-event-mapping/add-update-event-mapping.component.ts
- src/app/admin/components/system-configuration/event-mappings/event-mapping-form/event-mapping-form.component.html
- src/app/admin/components/system-configuration/event-mappings/event-mapping-form/event-mapping-form.component.ts
- src/app/admin/components/system-configuration/event-mappings/event-mappings.component.html
- src/app/admin/components/system-configuration/event-mappings/event-mappings.component.ts
- src/app/core/pipes/humanizeInitCap.spec.ts
- src/app/core/pipes/humanizeInitCap.ts
https://tools.hmcts.net/jira/browse/DMP-3270
- screen readers didn't read some handler correctly, due to them being all one word, eg. "SentencingRemarksAndRetentionPolicyHandler"
- fixing this by separating the words out by capitals for the option display value only
> DMP-3270 Fixing accessibility issue with event handler select options

- src/app/portal/models/hearing/media/transformed-media-type.ts
- src/app/portal/services/audio-request/audio-request.service.ts
https://tools.hmcts.net/jira/browse/DMP-3630
> DMP-3630 Bug Your Audio - present hyphen for null expiry date

- src/app/admin/components/transcripts/view-transcript/view-transcript.component.html
- src/app/admin/components/transcripts/view-transcript/view-transcript.component.ts
https://tools.hmcts.net/jira/browse/DMP-3516
Make spacing consistent by using app-govuk-heading component
> DMP-3516: Fix white space issue around back button

- cypress/e2e/functional/admin-portal/groups-spec.cy.js
- cypress/e2e/functional/admin-portal/retention-policies-spec.cy.js
- cypress/e2e/functional/admin-portal/transcript-requests-spec.cy.js
- darts-api-stub/admin/retention-policies/retention-policies.js
- darts-api-stub/admin/transcriptions/transcriptions.js
- darts-api-stub/transcriptions/transcriptions.js
DMP-3526
Added reset steps/endpoints in groups-spec files & retention policy files
Transcription-requests updated to be able to run in succession
> DMP-3526 - Reset added to FT's

- src/app/admin/components/search/event-search-results/event-search-results.component.ts
- src/styles.scss
N/A
- Fix datepicker styles
- Fix event id sort
> Minor bug fixes

- cypress/e2e/functional/request-transcript-spec.cy.js
- src/app/portal/components/hearing/request-transcript/request-times/request-times.component.spec.ts
- src/app/portal/components/hearing/request-transcript/request-times/request-times.component.ts
DMP-3471
Very minor spelling change to outside time validation during request transcript flow.
> DMP-3471 Request time validation outside times, typo fix

- cypress/e2e/functional/admin-portal/user-record-spec.cy.js
- cypress/e2e/functional/admin-portal/users-spec.cy.js
- darts-api-stub/admin/users/users.js
> DMP-3526 - Reset users to allow user-record to run in succession

- src/app/admin/services/transcription-admin/transcription-admin.service.ts
DMP-3632
Fix to handle empty transcript workflow gracefully
> DMP-3632: Return default workflow actor when there are no transcript workflows

- src/app/portal/components/your-work/upload-transcript/upload-transcript.component.html
- src/app/portal/components/your-work/upload-transcript/upload-transcript.component.ts
- src/app/portal/components/your-work/your-work.component.html
- src/app/portal/components/your-work/your-work.component.ts
https://tools.hmcts.net/jira/browse/DMP-3607
Hide controls on completed transcripts, from your-work screen. 
Added saved tabs to your-work.
> DMP-3607 hide controls on completed transcript requests in your work

- src/app/core/components/common/notification-banner/notification-banner.component.scss
- src/app/portal/components/case/case.component.ts
- src/app/portal/components/hearing/add-annotation/add-annotation.component.html
- src/app/portal/components/hearing/add-annotation/add-annotation.component.spec.ts
- src/app/portal/components/hearing/add-annotation/add-annotation.component.ts
- src/app/portal/components/hearing/hearing.component.html
- src/app/portal/components/hearing/hearing.component.spec.ts
- src/app/portal/components/hearing/hearing.component.ts
- src/app/portal/components/hearing/request-transcript/request-transcript.component.ts
- src/app/portal/portal.routes.ts
- src/main.ts
DMP-3604
Redirect user to 404 if hearing doesn't exist
> DMP-3604: Redirect user to 404 if hearing doesn't exist

- server/server.ts
https://tools.hmcts.net/jira/browse/DMP-3680
Need to confirm headers once on staging, ensuring CORS B2C headers are not impacted.
> DMP-3680 adding / removing headers for clickjacking x-frame

- src/app/core/components/common/file-upload/file-upload.component.html
- src/app/core/components/common/file-upload/file-upload.component.ts
- src/app/core/validators/max-file-size.validator.ts
- src/app/portal/components/hearing/add-annotation/add-annotation.component.html
- src/app/portal/components/hearing/add-annotation/add-annotation.component.spec.ts
- src/app/portal/components/hearing/add-annotation/add-annotation.component.ts
- src/app/portal/services/annotation/annotation.service.ts
[DMP-3734](https://tools.hmcts.net/jira/browse/DMP-3734)
> DMP-3734: Fix annotation upload validation error messages

- cypress/e2e/functional/request-audio-spec.cy.js
- src/app/portal/components/hearing/hearing.component.html
- src/app/portal/components/hearing/request-playback-audio/request-playback-audio.component.spec.ts
- src/app/portal/components/hearing/request-playback-audio/request-playback-audio.component.ts
https://tools.hmcts.net/jira/browse/DMP-3756
https://tools.hmcts.net/jira/browse/DMP-3583 introduced validation for NO audio, this change introduces time validation checks to ensure it sits within available audio window.
> DMP-3756 Bug - validation to check if times are outside audio times

- cypress/e2e/functional/admin-portal/file-deletion-spec.cy.js
- darts-api-stub/admin/medias/medias.js
- src/app/admin/admin.routes.ts
- src/app/admin/components/file-deletion/audio-file-delete/audio-file-delete.component.html
- src/app/admin/components/file-deletion/audio-file-delete/audio-file-delete.component.spec.ts
- src/app/admin/components/file-deletion/audio-file-delete/audio-file-delete.component.ts
- src/app/admin/components/file-deletion/audio-file-results/audio-file-results.component.html
- src/app/admin/components/file-deletion/audio-file-results/audio-file-results.component.spec.ts
- src/app/admin/components/file-deletion/audio-file-results/audio-file-results.component.ts
- src/app/admin/components/file-deletion/file-deletion.component.html
- src/app/admin/components/file-deletion/file-deletion.component.spec.ts
- src/app/admin/components/file-deletion/file-deletion.component.ts
- src/app/admin/models/file-deletion/audio-file-marked-deletion.interface.ts
- src/app/admin/models/file-deletion/audio-file-marked-deletion.type.ts
- src/app/admin/services/file-deletion/file-deletion.service.spec.ts
- src/app/admin/services/file-deletion/file-deletion.service.ts
- src/app/core/services/user/user.service.ts
https://tools.hmcts.net/jira/browse/DMP-2716
> DMP-2716 Audio file deletion results, marked user validation

- src/app/portal/components/hearing/request-playback-audio/request-playback-audio.component.ts
https://tools.hmcts.net/jira/browse/DMP-3756
> DMP-3756 Bug - Ensure unique error summary for outside time validation

- cypress/e2e/functional/your-audio-spec.cy.js
[DMP-3589](https://tools.hmcts.net/jira/browse/DMP-3589)
> DMP-3589: Reinstate test

- darts-api-stub/index.js
- server/middleware/set-headers.ts
- server/server.ts
https://tools.hmcts.net/jira/browse/DMP-3680
- Moved headers middleware earlier in the pipeline to apply to all responses.
- Disable `X-Powered-By: express` header
> DMP-3680: Fix headers

- src/app/portal/components/case/case-file/case-events-table/case-events-table.component.html
https://tools.hmcts.net/jira/browse/DMP-3822
Disable pagination for court logs
Tested on local pointing to staging, manually
> DMP-3822 Remove pagination for case courtlogs

- src/app/admin/components/groups/group-form/group-form.component.html
- src/app/admin/components/groups/group-form/group-form.component.scss
[DMP-3832](https://tools.hmcts.net/jira/browse/DMP-3832)
> DMP-3832: Change cancel button to link

- src/app/admin/components/groups/group-form/group-form.component.ts
https://tools.hmcts.net/jira/browse/DMP-3829
> DMP-3892: Fix typo in error message

- .github/workflows/close-pr.yml
- .github/workflows/on-pr.yml
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
- using .platform instead of .apps
- removing extra "-" in logout URL
- ensuring env is used for all steps
> Fixes for dev/preview deployment logins

- .github/workflows/b2c-callback-urls.yml
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
> Dev preview fixes external

- src/app/portal/components/hearing/hearing.component.html
- src/app/portal/components/hearing/hearing.component.ts
[DMP-3837](https://tools.hmcts.net/jira/browse/DMP-3837)
Hide button based on permissions matrix in LLD
> DMP-3837: Hide button based on permissions

- src/app/admin/components/transcripts/transcripts.component.html
[DMP-3839](https://tools.hmcts.net/jira/browse/DMP-3839)
> DMP-3829: Transcript request tab text change

- src/app/admin/components/retention-policies/retention-policies.component.html
- src/app/admin/components/retention-policies/retention-policies.component.ts
[DMP-3847](https://tools.hmcts.net/jira/browse/DMP-3847)
Add display name column to retention policies table
> DMP-3847: Add display name column to retention policies table

- package.json
- yarn-audit-known-issues
- yarn.lock
Resolution in package.json to set micromatch version in http-proxy-middleware
> force http-proxy-middleware to use micromatch 4.0.8 vuln fix

- cypress/e2e/functional/admin-portal/search-spec.cy.js
- src/app/admin/services/admin-search/admin-search.service.spec.ts
- src/app/admin/services/admin-search/admin-search.service.ts
[DMP-3811](https://tools.hmcts.net/jira/browse/DMP-3811)
> DMP-3811: Update error message to 1000 from 500

- darts-api-stub/transcriptions/transcriptions.js
- src/app/portal/components/hearing/request-transcript/request-transcript.component.ts
https://tools.hmcts.net/jira/browse/DMP-3267
> DMP-3267 Request transcript times converted to utc before making request

- src/app/admin/components/search/search.component.html
[DMP-3828](https://tools.hmcts.net/jira/browse/DMP-3828)
> DMP-3828: Hide case search results when loading

- src/app/admin/components/transcripts/view-transcript/view-transcript.component.html
- src/app/admin/components/transcripts/view-transcript/view-transcript.component.ts
- src/app/admin/components/users/user-transcripts/user-transcripts.component.html
[DMP-3721](https://tools.hmcts.net/jira/browse/DMP-3721)
> DMP-3721: Fix back link

- src/app/core/components/common/data-table/data-table.component.spec.ts
- src/app/core/components/common/data-table/data-table.component.ts
- tsconfig.json
https://tools.hmcts.net/jira/browse/DMP-3757
Description
Reset rows to initial rows before performing sort
> DMP-3757: Isolate datatable column sorting

- src/app/admin/components/transformed-media/associated-audio-table/associated-audio-table.component.html
- src/app/admin/components/transformed-media/associated-audio-table/associated-audio-table.component.spec.ts
https://tools.hmcts.net/jira/browse/DMP-3881
> DMP-3881 audio link for associated audio table

- cypress/e2e/functional/case-file-spec.cy.js
- cypress/e2e/functional/case-search-spec.cy.js
- darts-api-stub/cases/case.js
- src/app/core/components/common/govuk-banner/govuk-banner.component.scss
- src/app/core/services/error/error-message.service.ts
- src/app/portal/components/case/case-file/case-file.component.html
- src/app/portal/components/case/case-file/case-file.component.scss
- src/app/portal/components/case/case-file/case-file.component.ts
- src/app/portal/components/case/case.component.html
- src/app/portal/components/case/case.component.spec.ts
- src/app/portal/components/case/case.component.ts
- src/app/portal/components/search/case-search-results/case-search-results.component.html
- src/app/portal/components/search/case-search-results/case-search-results.component.scss
- src/app/portal/models/case/case.interface.ts
- src/app/portal/models/case/case.type.ts
- src/app/portal/services/case/case.service.spec.ts
- src/app/portal/services/case/case.service.ts
https://tools.hmcts.net/jira/browse/DMP-2910
https://tools.hmcts.net/jira/browse/DMP-2909
Adds warning banner to case portal search, hides elements on case file screen
Removed top border from reporting restrictions/expired banner on case search result to improve UX for case association
> DMP-2909/2910 expired case search result and case file

- src/app/portal/components/case/case-file/case-file.component.html
- src/app/portal/components/search/case-search-results/case-search-results.component.html
https://tools.hmcts.net/jira/browse/DMP-2909
https://tools.hmcts.net/jira/browse/DMP-2910
https://tools.hmcts.net/jira/browse/DMP-3618
> DMP-2909/2910/3618 Add expired prefix to expiry banner

- src/app/admin/components/events/advanced-event-details/advanced-event-details.component.html
[DMP-3309](https://tools.hmcts.net/jira/browse/DMP-3309)
> DMP-3309: Set default name for system users

- src/app/admin/components/audio-file/audio-file.component.html
- src/app/admin/components/audio-file/audio-file.component.spec.ts
- src/app/admin/components/audio-file/audio-file.component.ts
- src/app/admin/components/file-deletion/file-hide-or-delete-success/file-hide-or-delete-success.component.spec.ts
- src/app/admin/components/file-deletion/file-hide-or-delete-success/file-hide-or-delete-success.component.ts
- src/app/admin/components/file-deletion/file-hide-or-delete/file-hide-or-delete.component.html
- src/app/admin/components/file-deletion/file-hide-or-delete/file-hide-or-delete.component.spec.ts
- src/app/admin/components/file-deletion/file-hide-or-delete/file-hide-or-delete.component.ts
- src/app/admin/components/transformed-media/associated-audio-hide-delete/associated-audio-hide-delete.component.html
- src/app/admin/components/transformed-media/associated-audio-hide-delete/associated-audio-hide-delete.component.spec.ts
- src/app/admin/components/transformed-media/associated-audio-hide-delete/associated-audio-hide-delete.component.ts
- src/app/admin/components/transformed-media/associated-audio-table/associated-audio-table.component.html
- src/app/admin/components/transformed-media/associated-audio-table/associated-audio-table.component.ts
- src/app/admin/components/transformed-media/view-transformed-media/view-transformed-media.component.html
- src/app/admin/components/transformed-media/view-transformed-media/view-transformed-media.component.ts
https://tools.hmcts.net/jira/browse/DMP-3891
State updates, @Input updates to allow correct back link to persist between components/flow
> DMP-3891 Audio file back link fix

- darts-api-stub/hearings/hearings.js
- src/app/portal/services/hearing/hearing.service.ts
https://tools.hmcts.net/jira/browse/DMP-3895
> DMP-3895 sort events by ascending order in hearing service

- cypress/e2e/functional/request-transcript-spec.cy.js
- src/app/portal/components/hearing/request-transcript/request-times/request-times.component.spec.ts
- src/app/portal/components/hearing/request-transcript/request-times/request-times.component.ts
https://tools.hmcts.net/jira/browse/DMP-3902
remove outside time validation, default end time if one event selected
> DMP-3902 remove outside time validation, default end time if one event selected

- server/middleware/session.ts
> Adding event logging for redis

- cypress/e2e/functional/admin-portal/file-deletion-spec.cy.js
- darts-api-stub/admin/transcriptions/transcription-documents.js
- src/app/admin/admin.routes.ts
- src/app/admin/components/file-deletion/audio-file-results/audio-file-results.component.html
- src/app/admin/components/file-deletion/audio-file-results/audio-file-results.component.ts
- src/app/admin/components/file-deletion/file-deletion.component.html
- src/app/admin/components/file-deletion/file-deletion.component.spec.ts
- src/app/admin/components/file-deletion/file-deletion.component.ts
- src/app/admin/components/file-deletion/transcripts-for-deletion/transcripts-for-deletion.component.html
- src/app/admin/components/file-deletion/transcripts-for-deletion/transcripts-for-deletion.component.spec.ts
- src/app/admin/components/file-deletion/transcripts-for-deletion/transcripts-for-deletion.component.ts
- src/app/admin/components/file-deletion/unauthorised-transcript-deletion/unauthorised-transcript-deletion.component.html
- src/app/admin/components/file-deletion/unauthorised-transcript-deletion/unauthorised-transcript-deletion.component.spec.ts
- src/app/admin/components/file-deletion/unauthorised-transcript-deletion/unauthorised-transcript-deletion.component.ts
- src/app/admin/models/file-deletion/index.ts
- src/app/admin/models/file-deletion/transcription-document-for-deletion-data.interface.ts
- src/app/admin/models/file-deletion/transcription-document-for-deletion.type.ts
- src/app/admin/models/index.ts
- src/app/admin/services/file-deletion/file-deletion.service.spec.ts
- src/app/admin/services/file-deletion/file-deletion.service.ts
- src/app/admin/services/transcription-admin/transcription-admin.service.spec.ts
- src/app/admin/services/transcription-admin/transcription-admin.service.ts
- src/app/portal/components/hearing/request-transcript/request-times/request-times.component.ts
[DMP-2731](https://tools.hmcts.net/jira/browse/DMP-2731)
- Add transcripts for deletion screen
- Add transcript count to tab
- Add unathorised deletion screen if user attempts to delete their own deletion requests
- Tab state on file deletion screen is preserved
- Refactored the `FileDeletionService` to be more generic
- Fix `RequestTimesComponent` missing th by adding an empty column 
- Moved private functions to the bottom of `TranscriptionAdminService`
> DMP-2731: Add transcripts for deletion screen

- src/app/admin/admin.routes.ts
https://tools.hmcts.net/jira/browse/DMP-3878
> DMP-3878:Add SUPER_USER role to deactivate user route

- darts-api-stub/admin/medias/medias.js
- src/app/admin/components/transformed-media/associated-audio-hide-delete/associated-audio-hide-delete.component.spec.ts
- src/app/admin/components/transformed-media/associated-audio-hide-delete/associated-audio-hide-delete.component.ts
- src/app/admin/components/transformed-media/associated-audio-table/associated-audio-table.component.ts
- src/app/admin/components/transformed-media/view-transformed-media/view-transformed-media.component.spec.ts
- src/app/admin/models/transformed-media/associated-media-data.interface.ts
- src/app/admin/models/transformed-media/associated-media.ts
- src/app/admin/services/transformed-media/transformed-media.service.spec.ts
- src/app/admin/services/transformed-media/transformed-media.service.ts
- src/app/core/services/error/error-message.service.ts
[DMP-3865](https://tools.hmcts.net/jira/browse/DMP-3865)
> Handle 409 case on hide associated audio

- cypress/e2e/functional/admin-portal/audio-file-details-spec.cy.js
- cypress/e2e/functional/admin-portal/transcript-requests-spec.cy.js
- darts-api-stub/admin/medias/medias.js
- darts-api-stub/admin/transcriptions/transcription-documents.js
- src/app/admin/components/audio-file/audio-file.component.html
- src/app/admin/components/audio-file/audio-file.component.ts
- src/app/admin/components/transcripts/view-transcription-document/view-transcription-document.component.html
- src/app/admin/components/transcripts/view-transcription-document/view-transcription-document.component.ts
- src/app/core/components/common/expired-banner/expired-banner.component.html
- src/app/core/components/common/expired-banner/expired-banner.component.spec.ts
- src/app/core/components/common/expired-banner/expired-banner.component.ts
- src/app/portal/components/case/case-file/case-file.component.html
- src/app/portal/components/case/case-file/case-file.component.ts
- [DMP-3653](https://tools.hmcts.net/jira/browse/DMP-3653)
- [DMP-3657](https://tools.hmcts.net/jira/browse/DMP-3657)
- Add expired banner component
- Refactor case file to use the new component
- Add to view audio file and view transcript file screens
- Add functional tests
> DMP-3653 &  DMP-3657: Add expired banners to view audio file and view transcript file

- src/app/admin/components/search/search-form/search-form.component.html
- src/app/core/components/common/specific-or-range-date-picker/specific-or-range-date-picker.component.html
[DMP-3769](https://tools.hmcts.net/jira/browse/DMP-3769)
Remove H4 tags to fix accessibility issues
> DMP-3769: Remove heading tags

- cypress/e2e/functional/request-audio-spec.cy.js
- darts-api-stub/audios/index.js
- package.json
- src/app/portal/components/hearing/events-and-audio/events-and-audio.component.html
- src/app/portal/components/hearing/events-and-audio/events-and-audio.component.scss
- yarn.lock
See [DMP-3777](https://tools.hmcts.net/jira/browse/DMP-3777
- `is_archived` takes precedence over `is_available` for audio preview message
> DMP-3777: Bugfix - Audio archived. Preview is not available message

- charts/darts-portal/Chart.yaml
- charts/darts-portal/values.yaml
- config/custom-environment-variables.json
- config/default.json
- package.json
- server/controllers/auth.ts
- yarn.lock
https://tools.hmcts.net/jira/browse/DMP-3863
- to be overridden by env var `DARTS_AZUREAD_B2C_HOSTNAME`
- this is so that is can be configured differently to the "hostname" config, set by env var `DARTS_PORTAL_URL`
> DMP-3863 Adding additional config used for the Azure AD B2C hostname

- src/app/admin/components/transcripts/change-transcript-status/change-transcript-status.component.html
See [DMP-3926](https://tools.hmcts.net/jira/browse/DMP-3926)
Add missing default option for transcription status selector
> DMP-3926: Add missing default option for transcription status selector

- darts-api-stub/admin/events/events.js
- src/app/admin/components/events/advanced-event-details/advanced-event-details.component.spec.ts
- src/app/admin/components/events/view-event/view-event.component.html
- src/app/admin/components/events/view-event/view-event.component.spec.ts
- src/app/admin/components/events/view-event/view-event.component.ts
- src/app/admin/facades/events/events-facade.service.spec.ts
- src/app/admin/models/events/event-data.interface.ts
- src/app/admin/models/events/event.ts
- src/app/admin/services/events/events.service.spec.ts
- src/app/admin/services/events/events.service.ts
See [DMP-3910](https://tools.hmcts.net/jira/browse/DMP-3910)
Add expired banner to view event screen
> DMP-3910: Add expired banner to view event screen

- cypress/e2e/functional/admin-portal/transcript-requests-spec.cy.js
- cypress/e2e/functional/transcript-requests-spec.cy.js
- darts-api-stub/transcriptions/transcriptions.js
- src/app/admin/models/transcription/transcription-details.ts
- src/app/portal/components/transcriptions/approve-transcript/approve-transcript.component.spec.ts
- src/app/portal/components/transcriptions/approve-transcript/approve-transcript.component.ts
- src/app/portal/models/transcriptions/transcription-details.type.ts
- src/app/portal/services/mapping/mapping.service.ts
- src/app/portal/services/transcription/transcription.service.spec.ts
[DMP-3904](https://tools.hmcts.net/jira/browse/DMP-3904)
[DMP-3905](https://tools.hmcts.net/jira/browse/DMP-3905)
- Redirect to forbidden page if current logged in user is the transcript requester
- Redirect to not found page if transcript request is not in awaiting authorisation status
> DMP-3904 & DMP-3905: Add redirects to approve transcript component

- cypress/e2e/functional/admin-portal/courthouse-record-spec.cy.js
- cypress/e2e/functional/admin-portal/courthouse-users-spec.cy.js
- cypress/e2e/functional/admin-portal/groups-spec.cy.js
- cypress/e2e/functional/case-retention-spec.cy.js
- cypress/e2e/functional/request-audio-spec.cy.js
- cypress/e2e/functional/view-transcript-spec.cy.js
- cypress/e2e/functional/your-transcripts-spec.cy.js
- darts-api-stub/admin/security-roles/security-roles.js
- darts-api-stub/data/securityRoles.json
- darts-api-stub/users.js
- src/app/admin/components/courthouses/courthouse-record/courthouse-record.component.spec.ts
- src/app/admin/components/courthouses/courthouse-users/courthouse-users.component.spec.ts
- src/app/admin/components/courthouses/courthouse-users/courthouse-users.component.ts
- src/app/admin/components/transcripts/view-transcript/transcript-details/transcript-details.component.spec.ts
- src/app/admin/facades/transcript/transcript-facade.service.spec.ts
- src/app/core/components/common/filters/filters.component.html
- src/app/portal/components/transcriptions/transcriptions.component.spec.ts
See [DMP-3879](https://tools.hmcts.net/jira/browse/DMP-3879)
- Fixed typo in the REQUESTER role display name
- Fixed small markup styling issue with 'Clear filters' link/button
> DMP-3879: Fix courthouse user filter

- src/app/admin/components/courthouses/courthouse-record/courthouse-record.component.spec.ts
- src/app/admin/components/courthouses/courthouse-record/courthouse-record.component.ts
Replicable by going to https://darts.staging.apps.hmcts.net/admin/courthouses/127 on staging and viewing get users request, see dupe id's
> Courthouse record - Bug fix - ensure unique user ids are passed into getUsers

- src/app/core/components/common/filters/filters.component.scss
> Fixing overflow of long email address in the filter component

- cypress/e2e/functional/admin-portal/search-spec.cy.js
- darts-api-stub/admin/events/events.js
- src/app/admin/components/search/event-search-results/event-search-results.component.html
- src/app/admin/components/search/event-search-results/event-search-results.component.scss
- src/app/admin/components/search/event-search-results/event-search-results.component.ts
- src/app/admin/models/search/admin-event-search-result-data.interface.ts
- src/app/admin/models/search/admin-event-search-result.ts
- src/app/admin/services/admin-search/admin-search.service.ts
https://tools.hmcts.net/jira/browse/DMP-3639
Manual and FT carried out
> DMP-3639 - Add expired banner to event search

- src/app/admin/components/automated-tasks/automated-tasks.component.ts
- src/app/portal/components/hearing/request-transcript/request-transcript.component.ts
[DMP-3921](https://tools.hmcts.net/jira/browse/DMP-3921)
> DMP-3921: Add empty column headers back in

- src/app/core/components/common/details-table/details-table.component.scss
N/A
If multiple names are displayed in the details table, separate them by a new line
**Before**
**After**
> Details table - displaying multiple array items on new lines

- src/app/admin/components/file-deletion/file-hide-or-delete/file-hide-or-delete.component.html
- src/app/admin/components/file-deletion/file-hide-or-delete/file-hide-or-delete.component.spec.ts
- src/app/admin/components/file-deletion/file-hide-or-delete/file-hide-or-delete.component.ts
- src/app/portal/components/audios/audios.component.html
- src/app/portal/components/audios/audios.component.spec.ts
- src/app/portal/components/audios/audios.component.ts
- src/app/portal/components/case/case-retention-date/case-retention-date.component.ts
- src/app/portal/components/hearing/hearing.component.ts
- src/app/portal/components/hearing/request-transcript/request-transcript.component.ts
- src/app/portal/components/transcriptions/transcriptions.component.html
- src/app/portal/components/transcriptions/transcriptions.component.spec.ts
- src/app/portal/components/transcriptions/transcriptions.component.ts
https://tools.hmcts.net/jira/browse/DMP-3913
Updated titles as per JIRA ticket
> DMP-3913: Update titles dynamically when route does not change

- src/app/portal/components/audios/audios.component.ts
[DMP-3953](https://tools.hmcts.net/jira/browse/DMP-3953)
Change your audio column from expiry to last accessed
> DMP-3953: Change your audio column from expiry to last accessed

- src/app/portal/components/your-work/upload-transcript/upload-transcript.component.html
N/A
It should only allow doc and docx, not zip.
> Fixing transcription file upload allowed types

- src/app/portal/components/transcriptions/assign-transcript/assign-transcript.component.html
[DMP-3949](https://tools.hmcts.net/jira/browse/DMP-3949)
Update breadcrumb to use transcript request id instead of case id
> DMP-3949: Update breadcrumb to use transcript request id instead of case id

- src/app/portal/components/hearing/add-annotation/add-annotation.component.spec.ts
- src/app/portal/components/hearing/add-annotation/add-annotation.component.ts
- src/app/portal/components/your-work/upload-transcript/upload-transcript.component.spec.ts
- src/app/portal/components/your-work/upload-transcript/upload-transcript.component.ts
N/A
- handling this for transcription and annotation documents
> Showing error screen if file upload fails

- src/app/admin/components/courthouses/courthouse-record/courthouse-record.component.spec.ts
- src/app/admin/components/courthouses/courthouse-record/courthouse-record.component.ts
- src/app/core/components/common/details-table/details-table.component.html
https://tools.hmcts.net/jira/browse/DMP-3958
Group array in courthouse record only contains link if admin
> DMP-3958 Fix angular warnings and group link, non clickable unless admin

- src/app/portal/components/audios/audios.component.html
- src/app/portal/components/audios/audios.component.ts
See [DMP-3953](https://tools.hmcts.net/jira/browse/DMP-3953)
In Your Audio
- Fix last accessed column in Ready table
- Expired column reinstated in expired table
> DMP-3953: Fix 'Your Audio' columns

- src/app/portal/components/audios/audio-view/audio-view.component.spec.ts
- src/app/portal/components/audios/audio-view/audio-view.component.ts
- src/app/portal/models/hearing/hearing-event.interface.ts
N/A
Adding null check for event text before concatenating with event type.
**Before**
**After**
> Fixing event text for audio playback screen

- src/app/core/components/layout/header/portal-navigation/portal-navigation.component.html
- src/app/portal/components/transcriptions/transcriptions.component.html
- src/app/portal/components/transcriptions/transcriptions.component.spec.ts
- src/app/portal/components/transcriptions/transcriptions.component.ts
- src/app/portal/portal.routes.ts
https://tools.hmcts.net/jira/browse/DMP-3939
Unit tested, manually tested locally. Unable to test on staging as currently /transcriptions is returning 504
> DMP-3939 - Permissions updated for your transcripts

- src/app/portal/components/hearing/request-playback-audio/request-playback-audio.component.spec.ts
- src/app/portal/components/hearing/request-playback-audio/request-playback-audio.component.ts
N/A
- times that fall within an audio were incorrectly invalid
- tests add for all scenarios
> Fixing audio request time validation

- src/app/portal/components/transcriptions/transcriptions.component.html
- src/app/portal/components/transcriptions/transcriptions.component.spec.ts
Amended based off revised ACs
https://tools.hmcts.net/jira/browse/DMP-3939
> DMP-3939 permission updates for your transcripts view

- server/controllers/authentication.ts
> Adding redirect URI for handleoauthcode

- src/app/admin/components/search/event-search-results/event-search-results.component.html
- src/app/admin/components/search/event-search-results/event-search-results.component.ts
- src/app/core/components/common/data-table/data-table.component.spec.ts
- src/app/core/components/common/data-table/data-table.component.ts
- src/app/core/models/data-table/data-table-column.interface.ts
Allows sorting on event ts fix
Added logic to data-table to allow asc sorting on load
https://tools.hmcts.net/jira/browse/DMP-3975
> DMP-3975 allowing sorting on event ts on event search

- cypress/e2e/functional/admin-portal/search-spec.cy.js
- cypress/e2e/functional/hearing-screen-spec.cy.js
- darts-api-stub/admin/events/events.js
- src/app/admin/components/search/event-search-results/event-search-results.component.html
- src/app/admin/models/search/admin-event-search-result-data.interface.ts
- src/app/admin/models/search/admin-event-search-result.ts
- src/app/admin/services/admin-search/admin-search.service.ts
https://tools.hmcts.net/jira/browse/DMP-3639
> DMP-3639 Anonymised banner text change, search events

- cypress/e2e/functional/hearing-screen-spec.cy.js
- server/controllers/stub-data.ts
https://tools.hmcts.net/jira/browse/DMP-2893
linked to https://tools.hmcts.net/jira/browse/DMP-3629
> DMP-2893 remove stub data endpoint for medias approve-deletion

- src/app/portal/components/hearing/hearing.component.ts
- src/app/portal/portal.routes.ts
https://tools.hmcts.net/jira/browse/DMP-4086
> DMP-4086 permission update request transcript

- src/app/admin/facades/transcript/transcript-facade.service.spec.ts
- src/app/admin/facades/transcript/transcript-facade.service.ts
https://tools.hmcts.net/jira/browse/DMP-4069
> DMP-4069 sorting workflow history by time and status

- src/app/portal/components/transcriptions/view-transcript/case-hearing-transcript/case-hearing-transcript.component.html
- src/app/portal/services/transcription/transcription.service.spec.ts
- src/app/portal/services/transcription/transcription.service.ts
[DMP-3962](https://tools.hmcts.net/jira/browse/DMP-3962)
This change only applies to Transcript details when accessed via the case/hearing screen.
Stub link: http://localhost:3000/case/1/transcripts/1
> DMP-3962: Amend Heading and Remove Request ID Row in Transcript Details

- darts-api-stub/retentions/retention.js
- src/app/admin/components/search/event-search-results/event-search-results.component.ts
- src/app/core/components/common/data-table/data-table.component.spec.ts
- src/app/core/components/common/data-table/data-table.component.ts
- src/app/core/models/data-table/data-table-column.interface.ts
- src/app/portal/components/case/case-file/case-events-table/case-events-table.component.ts
- src/app/portal/components/case/case-retention-date/case-retention-date.component.ts
https://tools.hmcts.net/jira/browse/DMP-4079
> DMP-4079 Desc ordering on time stamp in case events (court logs)

- cypress/e2e/functional/your-transcripts-spec.cy.js
- darts-api-stub/transcriptions/transcriptions.js
- src/app/portal/components/transcriptions/transcriptions.component.html
- src/app/portal/components/transcriptions/transcriptions.component.ts
https://tools.hmcts.net/jira/browse/DMP-4150
Tab persistance implemented on your transcript approval/rejection flow
Cypress tests for your-transcript can now run consecutively without failing
> DMP-4150 tab persistance on your transcript, cypress tests made idempotent

- src/app/admin/components/audio-file/advanced-audio-file-details/advanced-audio-file-details.component.html
https://tools.hmcts.net/jira/browse/DMP-4097
> DMP-4097 Audio details - hide link if user does not exist

- src/app/admin/components/users/user-groups/assign-groups/assign-groups.component.spec.ts
- src/app/admin/components/users/user-groups/assign-groups/assign-groups.component.ts
- src/app/admin/components/users/user-groups/user-groups/user-groups.component.ts
- src/app/portal/components/audios/audios.component.ts
- src/app/portal/components/transcriptions/transcriptions.component.ts
https://tools.hmcts.net/jira/browse/DMP-4095
Updated across:
- user groups
- assign groups
- your audios
- your transcripts
> DMP-4095 checkboxLabel set for checkbox tables

- server/controllers/auth.ts
- server/views/azuread-b2c-login.html
- src/app/core/components/error/not-found/expired-case/expired-case.component.html
https://tools.hmcts.net/jira/browse/DMP-4229
Fix involves passing baseUrl into b2c template to set href value for banner logo
Also tiny a11y best practice change removing aria role from a heading.
> DMP-4229 - Bug - Set b2c banner logo to base url href

- cypress/e2e/functional/request-audio-spec.cy.js
- src/app/portal/components/hearing/request-playback-audio/request-playback-audio.component.ts
https://tools.hmcts.net/jira/browse/DMP-3880
Added incorrect time format validation to request playback audio
Cypress tests added
Validation message:
> DMP-3880 Request playback audio - added incorrect format validation

- src/app/admin/components/retention-policies/retention-policies.component.ts
- src/app/admin/components/system-configuration/system-configuration.component.spec.ts
- src/app/admin/components/system-configuration/system-configuration.component.ts
[DMP-4222](https://tools.hmcts.net/jira/browse/DMP-4222)
Fix duplicate http calls when changing tabs on system configuration screen
> DMP-4222: System configuration - Duplicate network call bug on tab change

- cypress/e2e/functional/admin-portal/transformed-media-spec.cy.js
- src/app/admin/components/search/audio-search-results/audio-search-results.component.spec.ts
- src/app/admin/components/search/audio-search-results/audio-search-results.component.ts
- src/app/admin/components/search/event-search-results/event-search-results.component.spec.ts
- src/app/admin/components/search/event-search-results/event-search-results.component.ts
- src/app/admin/components/search/hearing-search-results/hearing-search-results.component.spec.ts
- src/app/admin/components/search/hearing-search-results/hearing-search-results.component.ts
- src/app/admin/components/system-configuration/event-mappings/event-mappings.component.html
- src/app/admin/components/system-configuration/event-mappings/event-mappings.component.ts
- src/app/admin/components/transformed-media/transformed-media-search-results/transformed-media-search-results.component.html
- src/app/core/components/common/data-table/data-table.component.html
- src/app/core/components/common/data-table/data-table.component.scss
- src/app/portal/components/search/case-search-results/case-search-results.component.spec.ts
- src/app/portal/components/search/case-search-results/case-search-results.component.ts
https://tools.hmcts.net/jira/browse/DMP-4213
Updated data table component to move caption within table
Applied display: table-caption to match screen design
Added visually hidden span to provide more context on table
Impacted areas: 
* Admin search all tabs
* Admin transformed media search
* Admin event mappings table
> DMP-4213 Accessibility - Table captions outside table

- cypress/e2e/functional/admin-portal/automated-tasks-spec.cy.js
- darts-api-stub/admin/automated-tasks/automated-tasks.js
- src/app/admin/admin.routes.ts
- src/app/admin/components/automated-tasks/change-batch-size/change-batch-size.component.html
- src/app/admin/components/automated-tasks/change-batch-size/change-batch-size.component.spec.ts
- src/app/admin/components/automated-tasks/change-batch-size/change-batch-size.component.ts
- src/app/admin/components/automated-tasks/view-automated-tasks/view-automated-tasks.component.html
- src/app/admin/components/automated-tasks/view-automated-tasks/view-automated-tasks.component.spec.ts
- src/app/admin/components/automated-tasks/view-automated-tasks/view-automated-tasks.component.ts
- src/app/admin/services/automated-tasks/automated-tasks.service.ts
[DMP-3980](https://tools.hmcts.net/jira/browse/DMP-3980)
> DMP-3980: Change batch size of automated task

- src/app/portal/components/transcriptions/view-transcript/rejected-transcript/rejected-transcript.component.html
https://tools.hmcts.net/jira/browse/DMP-4073
> DMP-4073 case number breadcrumb on rejected transcripts

- charts/darts-portal/values.dev.template.yaml
- charts/darts-portal/values.stg.template.yaml
- config/custom-environment-variables.json
- config/default.json
- config/development.json
- src/app/admin/admin.routes.ts
- src/app/admin/components/events/view-event/view-event.component.spec.ts
- src/app/admin/components/events/view-event/view-event.component.ts
- src/app/app.routes.spec.ts
- src/app/core/guards/event-obfuscation/event-obfuscation-guard.spec.ts
- src/app/core/guards/event-obfuscation/event-obfuscation-guard.ts
- src/app/core/guards/event-obfuscation/event-obufscation-guard.spec.ts
- src/app/core/services/app-config/app-config.service.spec.ts
- src/app/core/services/app-config/app-config.service.ts
- src/app/core/services/app-config/feature-flag.service.spec.ts
- src/app/core/services/app-config/feature-flag.service.ts
- src/app/core/services/dynatrace/dynatrace.service.spec.ts
See [DMP-4249](https://tools.hmcts.net/jira/browse/DMP-4249)
- Add event obfuscation feature flag
- `Obfuscate event text` button show/hide logic to depend on the new flag instead of manual deletion feature flag
- Routed to 404 page when disabled
> DMP-4249: Add EVENT_OBFUSCATION_ENABLED feature flag

- cypress/e2e/functional/case-file-spec.cy.js
- cypress/e2e/functional/request-audio-spec.cy.js
- darts-api-stub/cases/case.js
- darts-api-stub/hearings/hearings.js
- server/controllers/stub-data.ts
- src/app/portal/components/case/case-file/case-events-table/case-events-table.component.html
- src/app/portal/components/case/case-file/case-events-table/case-events-table.component.scss
- src/app/portal/components/hearing/events-and-audio/events-and-audio.component.html
- src/app/portal/models/events/case-event-data.interface.ts
- src/app/portal/models/events/case-event.ts
- src/app/portal/models/hearing/hearing-event.interface.ts
- src/app/portal/services/case/case.service.ts
https://tools.hmcts.net/jira/browse/DMP-3993
> DMP-3993 anonymised text for case events

- cypress/e2e/functional/request-audio-spec.cy.js
- darts-api-stub/hearings/hearings.js
- src/app/portal/components/hearing/events-and-audio/events-and-audio.component.html
- src/app/portal/models/hearing/hearing-event.interface.ts
https://tools.hmcts.net/jira/browse/DMP-3992
> DMP-3992 Add anonymised event text msg to hearing events

- src/app/admin/services/admin-search/admin-search.service.ts
- src/app/admin/services/transcription-admin/transcription-admin.service.spec.ts
- src/app/admin/services/transcription-admin/transcription-admin.service.ts
- src/app/admin/services/transformed-media/transformed-media.service.spec.ts
- src/app/admin/services/transformed-media/transformed-media.service.ts
- src/app/portal/services/case/case.service.spec.ts
- src/app/portal/services/case/case.service.ts
https://tools.hmcts.net/jira/browse/DMP-4160
> DMP-4160 upper case applied to courtroom / courthouse values in request

- src/app/admin/components/audio-file/associated-cases-table/associated-cases-table.component.html
- src/app/admin/components/automated-tasks/automated-tasks.component.html
- src/app/admin/components/courthouses/courthouse-record/courthouse-record.component.html
- src/app/admin/components/courthouses/courthouse-users/courthouse-users.component.html
- src/app/admin/components/file-deletion/audio-file-results/audio-file-results.component.html
- src/app/admin/components/file-deletion/transcripts-for-deletion/transcripts-for-deletion.component.html
- src/app/admin/components/groups/group-courthouses/group-courthouses.component.html
- src/app/admin/components/groups/group-users/group-users.component.html
- src/app/admin/components/groups/groups.component.html
- src/app/admin/components/retention-policies/retention-policies.component.html
- src/app/admin/components/transformed-media/associated-audio-table/associated-audio-table.component.html
- src/app/admin/components/users/user-groups/user-groups/user-groups.component.html
- src/app/portal/components/case/case-retention-date/case-retention-date.component.html
- src/app/portal/components/transcriptions/transcription-requests/transcription-requests.component.html
- src/app/portal/components/transcriptions/transcriptions.component.html
- src/app/portal/components/your-work/your-work.component.html
https://tools.hmcts.net/jira/browse/DMP-4234
Hidden table captions added to provide more context on tables for screen reader users
> DMP-4234 Hidden table captions added for a11y

- cypress/e2e/functional/admin-portal/file-deletion-spec.cy.js
- src/app/admin/components/file-deletion/audio-file-results/audio-file-results.component.ts
- src/app/admin/components/file-deletion/transcripts-for-deletion/transcripts-for-deletion.component.ts
- src/app/admin/components/retention-policies/retention-policies.component.ts
- src/app/admin/components/system-configuration/event-mappings/event-mappings.component.ts
- src/app/admin/components/users/user-search-results/user-search-results.component.ts
https://tools.hmcts.net/jira/browse/DMP-4094
> DMP-4094 Adding table cell headers

- src/app/admin/components/transcripts/transcripts.component.html
https://tools.hmcts.net/jira/browse/DMP-4303
> DMP-4304 Fixing transcript search multiple h1 headings

- src/app/portal/components/your-work/your-work.component.html
Spelling fix on to do table caption
https://tools.hmcts.net/jira/browse/DMP-4234
> DMP-4234 Small spelling fix

- config/custom-environment-variables.json
- config/default.json
- server/middleware/session.ts
N/A
- this is to allow running of the image locally using redis in docker
- currently you have to specify the keyvault mount and this is not easy
> Allowing redis connection string to be read from injected env var

- src/app/admin/components/courthouses/courthouse-record/courthouse-record.component.html
- src/app/admin/components/courthouses/courthouse-record/courthouse-record.component.ts
- src/app/admin/components/groups/group-record/group-record.component.html
- src/app/admin/components/groups/group-record/group-record.component.ts
- src/app/admin/components/users/user-record/user-record.component.html
- src/app/admin/components/users/user-record/user-record.component.ts
https://tools.hmcts.net/jira/browse/DMP-4209
> DMP-4209 - Back links added across user, group, courthouse records

- src/app/admin/components/automated-tasks/view-automated-tasks/view-automated-tasks.component.html
https://tools.hmcts.net/jira/browse/DMP-4208
> DMP-4208 - Add back link to view automated task

- src/app/admin/components/audio-file/audio-file.component.ts
- src/app/admin/components/file-deletion/transcripts-for-deletion/transcripts-for-deletion.component.html
- src/app/admin/components/search/audio-search-results/audio-search-results.component.html
- src/app/admin/components/transcripts/search-completed-transcripts-results/search-completed-transcripts-results.component.html
- src/app/admin/components/transcripts/view-transcription-document/view-transcription-document.component.html
- src/app/admin/components/transcripts/view-transcription-document/view-transcription-document.component.spec.ts
- src/app/admin/components/transcripts/view-transcription-document/view-transcription-document.component.ts
- src/app/admin/components/transformed-media/associated-audio-table/associated-audio-table.component.html
https://tools.hmcts.net/jira/browse/DMP-4210
Fix for audio file/transcript docs in file deletion back links
> DMP-4210 utilised history service to detect query param back urls

- config/default.json
- server/middleware/session.ts
https://tools.hmcts.net/jira/browse/DMP-4101
> DMP-4101 Increase session timeout to 8 hours

- src/app/admin/components/events/view-event/view-event.component.html
- src/app/core/components/common/govuk-banner/govuk-banner.component.html
- src/app/core/components/common/govuk-banner/govuk-banner.component.ts
[DMP-4280](https://tools.hmcts.net/jira/browse/DMP-4280)
> DMP-4280: Add configurable aria label to govuk banner component

- src/app/admin/components/audio-file/advanced-audio-file-details/advanced-audio-file-details.component.html
[DMP-4240](https://tools.hmcts.net/jira/browse/DMP-4240)
Removed check as it's hiding the Is current? key value when false
> DMP-4240 Remove 'isCurrent' check in template

- src/styles.scss
[DMP-4250](https://tools.hmcts.net/jira/browse/DMP-4250)
Tables are now aligned:
> DMP-4250: Remove th padding to fix table alignment

- server/controllers/authentication.ts
- server/middleware/is-authenticated.ts
- server/middleware/session.ts
- server/types/session.d.ts
https://tools.hmcts.net/jira/browse/DMP-4101
- the cookie expiry date was getting updated when the session was touched (every request), as was the redis TTL
- adding a static expiry datetime into the session when the user is authenticated (8 hours)
- this is checked in the `is-authenticated` middleware, if the expiry has passed then the session is ended
> DMP-4101 Using a different 8 hour session implementation

- cypress/e2e/functional/admin-portal/courthouse-record-spec.cy.js
- package.json
- src/app/admin/components/courthouses/courthouse-record/courthouse-record.component.html
- src/app/admin/components/courthouses/create-courthouse/create-update-courthouse-form/create-update-courthouse-form.component.html
- src/app/admin/components/courthouses/create-courthouse/create-update-courthouse-form/create-update-courthouse-form.component.spec.ts
- src/app/admin/services/courthouses/courthouse.service.spec.ts
- src/app/admin/services/courthouses/courthouses.service.ts
- yarn.lock
https://tools.hmcts.net/jira/browse/DMP-4161
- UPPER case courthouse name when being entered in form
- UPPER case when prepping data for API request, as a fallback
- displaying courthouse name on courthouse record, it was incorrectly using the display name
> DMP-4161 Admin portal Courthouse name upper case fixes

- cypress/e2e/functional/admin-portal/automated-tasks-spec.cy.js
- darts-api-stub/admin/automated-tasks/automated-tasks.js
- package.json
- src/app/admin/components/automated-tasks/edit-automated-task/edit-automated-task.component.html
- src/app/admin/components/automated-tasks/edit-automated-task/edit-automated-task.component.spec.ts
- src/app/admin/components/automated-tasks/edit-automated-task/edit-automated-task.component.ts
- src/app/admin/components/automated-tasks/view-automated-tasks/view-automated-tasks.component.html
- src/app/admin/components/automated-tasks/view-automated-tasks/view-automated-tasks.component.spec.ts
- src/app/admin/components/automated-tasks/view-automated-tasks/view-automated-tasks.component.ts
- src/app/admin/constants/automated-task-edit-error-messages.ts
- src/app/admin/models/automated-task/automated-task.interface.ts
- src/app/admin/models/automated-task/automated-task.ts
- src/app/admin/services/automated-tasks/automated-tasks.service.ts
https://tools.hmcts.net/jira/browse/DMP-4428
https://tools.hmcts.net/jira/browse/DMP-4429
https://tools.hmcts.net/jira/browse/DMP-4454
- amending fields to be inputs accepting integers, not date times
- including validation
- refactoring to be more general and easier to add extra editable fields in the future
> DMP-4428 DMP-4429 DMP-4454: Fix and refactor ARM RPO start/end hour fields

- server/middleware/session.ts
> Only use secure cookies if host is secure

- cypress/e2e/functional/admin-portal/file-deletion-spec.cy.js
- cypress/e2e/functional/admin-portal/hide-or-delete-file-spec.cy.js
- cypress/e2e/functional/admin-portal/transformed-media-spec.cy.js
- darts-api-stub/admin/medias/medias.js
- setup-jest.ts
- src/app/admin/components/file-deletion/audio-file-results/audio-file-results.component.ts
- src/app/admin/components/file-deletion/file-hide-or-delete/file-hide-or-delete.component.html
- src/app/admin/components/file-deletion/file-hide-or-delete/file-hide-or-delete.component.spec.ts
- src/app/admin/components/file-deletion/file-hide-or-delete/file-hide-or-delete.component.ts
- src/app/admin/components/transformed-media/associated-audio-hide-delete/associated-audio-hide-delete.component.html
- src/app/admin/components/transformed-media/associated-audio-hide-delete/associated-audio-hide-delete.component.spec.ts
- src/app/admin/components/transformed-media/associated-audio-hide-delete/associated-audio-hide-delete.component.ts
- src/app/admin/components/transformed-media/associated-audio-table/associated-audio-table.component.html
- src/app/admin/components/transformed-media/associated-audio-table/associated-audio-table.component.spec.ts
- src/app/admin/components/transformed-media/associated-audio-table/associated-audio-table.component.ts
- src/app/admin/components/transformed-media/view-transformed-media/view-transformed-media.component.spec.ts
- src/app/admin/models/transformed-media/associated-media-data.interface.ts
- src/app/admin/models/transformed-media/associated-media.ts
- src/app/admin/services/transformed-media/transformed-media.service.spec.ts
- src/app/admin/services/transformed-media/transformed-media.service.ts
- src/app/core/components/common/govuk-heading/govuk-heading.component.scss
[DMP-4253](https://tools.hmcts.net/jira/browse/DMP-4253)
- Merged both audio file and associated audio tables into one table in the mark for deletion journey
- FIx govuk heading component styling
- Fix redundant delete column on file deletion confirmation screen
> DMP-4523 Update the associated audio files for marking for deletion

- cypress/e2e/functional/request-audio-spec.cy.js
- darts-api-stub/audios/index.js
- src/app/portal/components/hearing/events-and-audio/events-and-audio.component.html
- src/app/portal/components/hearing/events-and-audio/events-and-audio.component.spec.ts
- src/app/portal/components/hearing/events-and-audio/events-and-audio.component.ts
https://tools.hmcts.net/jira/browse/DMP-4106
Test on local via localhost:3000/case/1/hearing/1 last audio item
> DMP-4106 Audio Preview - Add no audio message if start/end timestamps are the same

- cypress/e2e/functional/admin-portal/hide-or-delete-file-spec.cy.js
- darts-api-stub/admin/medias/medias.js
- src/app/admin/admin.routes.ts
- src/app/admin/components/audio-file/audio-file.component.html
- src/app/admin/components/audio-file/audio-file.component.spec.ts
- src/app/admin/components/audio-file/audio-file.component.ts
- src/app/admin/components/file-deletion/file-unhide-or-undelete/file-unhide-or-undelete.component.html
- src/app/admin/components/file-deletion/file-unhide-or-undelete/file-unhide-or-undelete.component.spec.ts
- src/app/admin/components/file-deletion/file-unhide-or-undelete/file-unhide-or-undelete.component.ts
- src/app/admin/components/transformed-media/associated-audio-hide-delete/associated-audio-hide-delete.component.html
- src/app/admin/components/transformed-media/associated-audio-hide-delete/associated-audio-hide-delete.component.ts
- src/app/admin/components/transformed-media/associated-audio-table/associated-audio-table.component.ts
- src/app/admin/services/transformed-media/transformed-media.service.spec.ts
- src/app/admin/services/transformed-media/transformed-media.service.ts
[DMP-4257](https://tools.hmcts.net/jira/browse/DMP-4257)
admin/audio-file/11 to test unhide with no associated audio
> DMP-4257: New associated audio files screen for unmarking for deletion/unhiding

- src/app/admin/components/retention-policies/retention-policy-form/retention-policy-form.component.spec.ts
- src/app/admin/services/retention-policies/retention-policies.service.spec.ts
> Fixed time based tests

- cypress/e2e/functional/admin-portal/audio-file-details-spec.cy.js
- darts-api-stub/admin/medias/medias.js
- src/app/admin/components/audio-file/associated-cases-table/associated-cases-table.component.html
- src/app/admin/components/audio-file/associated-cases-table/associated-cases-table.component.ts
- src/app/admin/components/audio-file/associated-hearings-table/associated-hearings-table.component.html
- src/app/admin/components/audio-file/associated-hearings-table/associated-hearings-table.component.spec.ts
- src/app/admin/components/audio-file/associated-hearings-table/associated-hearings-table.component.ts
- src/app/admin/components/audio-file/audio-file.component.html
- src/app/admin/components/audio-file/audio-file.component.spec.ts
- src/app/admin/components/audio-file/audio-file.component.ts
- src/app/admin/components/audio-file/basic-audio-file-details/basic-audio-file-details.component.html
- src/app/admin/components/audio-file/basic-audio-file-details/basic-audio-file-details.component.spec.ts
- src/app/admin/components/audio-file/basic-audio-file-details/basic-audio-file-details.component.ts
- src/app/admin/models/transformed-media/associated-case.ts
- src/app/admin/models/transformed-media/associated-hearing.ts
- src/app/admin/models/transformed-media/audio-file-data.interface.ts
- src/app/admin/models/transformed-media/audio-file.ts
- src/app/admin/services/transformed-media/transformed-media.service.ts
https://tools.hmcts.net/jira/browse/DMP-4263
> DMP-4263 New associated hearings table for audio file

- src/app/admin/services/courthouses/courthouses.service.ts
https://tools.hmcts.net/jira/browse/DMP-4506
Sorted courthouses by alphabetical order on admin search dropdown. 
Checked all other courthouse inputs and these are driven by user input via autocomplete
> DMP-4506 sort courthouse dropdown by autocomplete

- cypress/e2e/functional/your-transcripts-spec.cy.js
- src/app/portal/components/transcriptions/transcriptions.component.html
- src/app/portal/components/transcriptions/transcriptions.component.ts
https://tools.hmcts.net/jira/browse/DMP-4102
> DMP-4102 Portal - Your transcripts word change

- src/app/portal/components/transcriptions/transcriptions.component.html
https://tools.hmcts.net/jira/browse/DMP-4102
Update to There are no transcription requests to authorise
> DMP-4102 Text update

- src/app/core/components/layout/header/header.component.html
https://tools.hmcts.net/jira/browse/DMP-4545
> DMP-4545 Text update for portal links

- src/app/admin/components/transcripts/search-transcripts-form/search-transcripts-form.component.ts
- src/app/admin/components/transcripts/transcripts.component.spec.ts
- src/app/admin/components/transcripts/transcripts.component.ts
- src/app/admin/components/transformed-media/search-transformed-media-form/search-transformed-media-form.component.ts
- src/app/admin/components/transformed-media/search-transformed-media/search-transformed-media.component.ts
- src/app/admin/components/users/user-transcripts/user-transcripts.component.ts
- src/app/admin/services/transcription-admin/transcription-admin.service.spec.ts
- src/app/admin/services/transcription-admin/transcription-admin.service.ts
- src/app/core/components/common/courthouse/courthouse.component.spec.ts
- src/app/core/components/common/courthouse/courthouse.component.ts
- src/app/portal/components/search/case-search-form/case-search-form.component.ts
- src/app/portal/components/search/search.component.spec.ts
- src/app/portal/components/search/search.component.ts
Courthouse fields show all on input click, mappings updated to sort alphabetically
- Both admin transcript forms
- Admin Transformed media form
- Portal case search
https://tools.hmcts.net/jira/browse/DMP-4506
> DMP-4506 Courthouse fields updated across admin, portal

- src/app/admin/components/transcripts/search-transcripts-form/search-transcripts-form.component.ts
AC4/5 https://tools.hmcts.net/jira/browse/DMP-4369
> DMP-4369 Admin transcript searches limit changed to 2000

- src/app/admin/components/courthouses/courthouse-search-form/courthouse-search-form.component.ts
- src/app/admin/components/file-deletion/file-hide-or-delete/file-hide-or-delete.component.ts
- src/app/admin/components/users/create-user/create-update-user-form/create-update-user-form.component.ts
- src/app/admin/components/users/user-search-form/user-search-form.component.ts
Setting validation limits on multiple forms from 256 to 255, ensuring validation shows if 256 characters is entered rather than 257.
> Set validation length limits from 256 to 255 across multiple forms

- cypress.config.js
- cypress/e2e/functional/admin-portal/user-record-spec.cy.js
- cypress/e2e/functional/commands.js
- darts-api-stub/admin/transcriptions/transcriptions.js
- darts-api-stub/transcriptions/transcriptions.js
- src/app/admin/components/users/user-transcripts/user-transcripts.component.html
- src/app/admin/components/users/user-transcripts/user-transcripts.component.ts
- src/app/admin/models/transcription/transcription-data.interface.ts
- src/app/admin/models/transcription/transcription.ts
- src/app/admin/services/transcription-admin/transcription-admin.service.ts
- src/app/portal/components/transcriptions/transcription-requests/transcription-requests.component.html
- src/app/portal/components/transcriptions/transcriptions.component.html
- src/app/portal/components/transcriptions/transcriptions.component.spec.ts
- src/app/portal/components/transcriptions/transcriptions.component.ts
- src/app/portal/components/your-work/your-work.component.html
- src/app/portal/components/your-work/your-work.component.spec.ts
- src/app/portal/constants/transcription-columns.ts
- src/app/portal/models/transcriptions/transcript-request.type.ts
- src/app/portal/models/transcriptions/user-transcription-request.interface.ts
- src/app/portal/services/transcription/transcription.service.ts
https://tools.hmcts.net/jira/browse/DMP-4129
Awaiting on BE tickets
> DMP-4129 add approved on column to transcription tables

- src/app/admin/components/file-deletion/file-unhide-or-undelete/file-unhide-or-undelete.component.html
- src/app/admin/components/file-deletion/file-unhide-or-undelete/file-unhide-or-undelete.component.ts
https://tools.hmcts.net/jira/browse/DMP-4568
> DMP-4568 Added error summary to unhide associated audio screen

- src/app/admin/components/search/event-search-results/event-search-results.component.ts
- src/app/portal/components/case/case-file/case-events-table/case-events-table.component.ts
- src/app/portal/components/case/case-retention-date/case-retention-date.component.ts
https://tools.hmcts.net/jira/browse/DMP-4561
> DMP-4561 Removing sort on load as sorting is handled in BE now

- cypress/e2e/functional/your-audio-spec.cy.js
- src/app/portal/components/audios/audios.component.html
- src/app/portal/components/audios/audios.component.scss
- src/app/portal/components/audios/audios.component.spec.ts
- src/app/portal/components/audios/audios.component.ts
https://tools.hmcts.net/jira/browse/DMP-3956
> DMP-3956 Bulk download, validation for delete, download

- src/app/core/services/error/error-message.service.ts
N/A
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
- this endpoint is polled every 30s so ignore any errors
> Ignore errors when fetching transcriber counts

- cypress/e2e/functional/admin-portal/courthouses-spec.cy.js
- cypress/e2e/functional/admin-portal/users-spec.cy.js
- src/app/admin/components/courthouses/courthouses.component.ts
- src/app/admin/components/users/user-search-results/user-search-results.component.html
- src/app/admin/components/users/user-search-results/user-search-results.component.spec.ts
- src/app/admin/components/users/user-search-results/user-search-results.component.ts
- src/app/admin/components/users/users.component.html
- src/app/admin/components/users/users.component.ts
- src/styles.scss
- yarn.lock
Fixes for govuk width container override, search retainer on admin users/courthouse forms, tests added
> Angular 19 fixes

- cypress/e2e/functional/admin-portal/groups-spec.cy.js
- src/app/admin/components/groups/groups.component.ts
Fix for retaining search on admin groups
> Admin group search retain results, inputs

- cypress/e2e/functional/request-audio-spec.cy.js
- src/app/core/components/common/data-table/data-table.component.ts
- src/app/core/constants/datetime-keys.ts
- src/app/portal/components/hearing/events-and-audio/events-and-audio.component.spec.ts
- src/app/portal/components/hearing/events-and-audio/events-and-audio.component.ts
- src/app/portal/services/case/case.service.ts
https://tools.hmcts.net/jira/browse/DMP-4318
https://tools.hmcts.net/jira/browse/DMP-4644
Fix for sorting hearings on case screen, audio/events on hearing screen, descending date column sort fixes
> DMP-4318/4644 Sorting fixes

- cypress/e2e/functional/request-audio-spec.cy.js
- darts-api-stub/roles.js
- darts-api-stub/users.js
- src/app/core/models/user/role-name.type.ts
- src/app/core/services/user/user.service.ts
- src/app/portal/components/hearing/hearing.component.spec.ts
- src/app/portal/components/hearing/request-playback-audio/request-playback-audio.component.html
- src/app/portal/components/hearing/request-playback-audio/request-playback-audio.component.spec.ts
- src/app/portal/components/hearing/request-playback-audio/request-playback-audio.component.ts
https://tools.hmcts.net/jira/browse/DMP-4604
> DMP-4604 RCJ_APPEALS can download audio

- darts-api-stub/admin/security-groups/security-groups.js
- src/app/admin/components/groups/groups.component.spec.ts
- src/app/admin/components/groups/groups.component.ts
https://tools.hmcts.net/jira/browse/DMP-4628
> DMP-4628 groups display state fix

- src/app/core/services/error/error-message.service.spec.ts
- src/app/core/services/error/error-message.service.ts
Add 503/404 to ignore list for transcriber-counts
> Add 503/404 to ignore list for transcriber-counts

- src/app/portal/components/transcriptions/transcriptions.component.html
- src/app/portal/components/transcriptions/transcriptions.component.spec.ts
https://tools.hmcts.net/jira/browse/DMP-4652
Remove super user & super admin from accessing approve/reject transcriptions
> DMP-4652 Change for transcriptions permissions

- src/app/admin/services/admin-search/admin-search.service.spec.ts
- src/app/admin/services/admin-search/admin-search.service.ts
- src/app/portal/services/case-search/case-search.service.spec.ts
- src/app/portal/services/case-search/case-search.service.ts
N/A
To get insight into the search criteria used to help any performance investigations.
> Adding app insights custom events for case searches

- server/controllers/api.ts
- src/app/admin/services/admin-search/admin-search.service.ts
> Adding some logging to HTTP proxy middleware

- package.json
- server/middleware/session.ts
- yarn.lock
Update dependency connect-redis to v8
> Update dependency connect-redis to v8

- cypress/e2e/functional/admin-portal/transcript-requests-spec.cy.js
- cypress/e2e/functional/admin-portal/transformed-media-spec.cy.js
- cypress/e2e/functional/case-search-spec.cy.js
- src/app/admin/components/transformed-media/search-transformed-media-form/search-transformed-media-form.component.html
- src/app/core/components/common/courthouse/courthouse.component.ts
- src/app/portal/components/search/case-search-form/case-search-form.component.html
https://tools.hmcts.net/jira/browse/DMP-4669
Courthouse component to reset on clearing search forms
Impacts portal search, transcripts, media seaerch.
> DMP-4669 Courthouse reset fix and ft

- cypress/e2e/functional/admin-portal/group-record-spec.cy.js
- cypress/e2e/functional/admin-portal/groups-spec.cy.js
- darts-api-stub/admin/security-groups/security-groups.js
- src/app/admin/components/groups/group-courthouses/group-courthouses.component.html
- src/app/admin/components/groups/group-courthouses/group-courthouses.component.scss
- src/app/admin/components/groups/group-courthouses/group-courthouses.component.ts
- src/app/admin/components/groups/group-record/group-record.component.html
https://tools.hmcts.net/jira/browse/DMP-4457
> DMP-4457 global access checks for group records

- darts-api-stub/audios/index.js
- darts-api-stub/cases/case.js
- darts-api-stub/hearings/hearings.js
- src/app/portal/components/hearing/events-and-audio/events-and-audio.component.html
Can be tested on local stub http://localhost:3000/case/16/hearing/16
https://tools.hmcts.net/jira/browse/DMP-4734
> DMP-4734 Fixing events and audio sorting bug

- src/app/portal/components/search/search.component.html
https://tools.hmcts.net/jira/browse/DMP-4746
> DMP-4746 hide case results while searching

- server/middleware/is-authenticated.ts
[DMP-4758](https://tools.hmcts.net/jira/browse/DMP-4758)
> Allowing keep alive test requests without authentication

- src/app/admin/components/users/user-groups/user-groups/user-groups.component.html
- src/app/admin/services/transcription-admin/transcription-admin.service.spec.ts
- src/app/admin/services/transcription-admin/transcription-admin.service.ts
https://tools.hmcts.net/jira/browse/DMP-4770
Removing hyperlink for super users
> DMP-4770 Super user permissions for group tab on user record

- darts-api-stub/admin/transcriptions/transcription-documents.js
- darts-api-stub/transcriptions/transcriptions.js
- src/app/admin/components/transcripts/view-transcription-document/transcript-file-basic-detail/transcript-file-basic-detail.component.spec.ts
- src/app/admin/components/transcripts/view-transcription-document/transcript-file-basic-detail/transcript-file-basic-detail.component.ts
- src/app/portal/components/transcriptions/assign-transcript/assign-transcript.component.ts
- src/app/portal/models/transcriptions/transcription-details.type.ts
https://tools.hmcts.net/jira/browse/DMP-4804
- only show links to hearing if the ID is included in the response
- it's possible that migrated data might not contain the IDs and this prevents linking to `/undefined`
> DMP-4804 Fixing missing hearing link in admin transcript doc screen

- cypress/e2e/functional/admin-portal/event-details-spec.cy.js
- cypress/e2e/functional/admin-portal/search-spec.cy.js
- darts-api-stub/admin/events/events.js
- src/app/admin/admin.routes.ts
- src/app/admin/components/events/advanced-event-details/advanced-event-details.component.html
- src/app/admin/components/events/advanced-event-details/advanced-event-details.component.scss
- src/app/admin/components/events/advanced-event-details/advanced-event-details.component.spec.ts
- src/app/admin/components/events/advanced-event-details/advanced-event-details.component.ts
- src/app/admin/components/events/basic-event-details/basic-event-details.component.html
- src/app/admin/components/events/show-versions/show-versions.component.html
- src/app/admin/components/events/show-versions/show-versions.component.scss
- src/app/admin/components/events/show-versions/show-versions.component.spec.ts
- src/app/admin/components/events/show-versions/show-versions.component.ts
- src/app/admin/components/events/view-event/view-event.component.html
- src/app/admin/components/events/view-event/view-event.component.ts
- src/app/admin/facades/events/events-facade.service.spec.ts
- src/app/admin/facades/events/events-facade.service.ts
- src/app/admin/models/events/event-data.interface.ts
- src/app/admin/models/events/event-versions.interface.ts
- src/app/admin/models/events/event-versions.ts
- src/app/admin/models/events/event.ts
- src/app/admin/services/events/events.service.spec.ts
- src/app/admin/services/events/events.service.ts
- src/app/core/components/common/data-table/data-table.component.ts
https://tools.hmcts.net/jira/browse/DMP-3311
https://tools.hmcts.net/jira/browse/DMP-3861
> DMP-3311/3861 show versions for event screen

- cypress/e2e/functional/admin-portal/transformed-media-spec.cy.js
- src/app/admin/components/transformed-media/search-transformed-media/search-transformed-media.component.html
- src/app/admin/components/transformed-media/search-transformed-media/search-transformed-media.component.spec.ts
- src/app/admin/components/transformed-media/search-transformed-media/search-transformed-media.component.ts
- src/app/admin/components/transformed-media/transformed-media-search-results/transformed-media-search-results.component.html
- src/app/admin/components/transformed-media/transformed-media-search-results/transformed-media-search-results.component.scss
- src/app/admin/components/transformed-media/transformed-media-search-results/transformed-media-search-results.component.spec.ts
- src/app/admin/components/transformed-media/transformed-media-search-results/transformed-media-search-results.component.ts
https://tools.hmcts.net/jira/browse/DMP-4178
> DMP-4178 Delete transformed media

- cypress/e2e/functional/admin-portal/file-deletion-spec.cy.js
- src/app/admin/components/file-deletion/file-deletion.component.html
https://tools.hmcts.net/jira/browse/DMP-4230 AC2
> DMP-4230 Audio file deletion message update

- src/app/core/validators/before-time.validator.ts
- src/app/portal/components/hearing/request-playback-audio/request-playback-audio.component.ts
https://tools.hmcts.net/jira/browse/DMP-4777
> DMP-4777 bug fix for before time validator on request audio

- charts/darts-portal/Chart.yaml
> Helm chart upgrade

- src/app/portal/components/hearing/request-playback-audio/request-playback-audio.component.ts
https://tools.hmcts.net/jira/browse/DMP-4781
> DMP-4781 Bug fix for invalid time on request audio

- src/app/core/validators/before-time.validator.spec.ts
- src/app/core/validators/before-time.validator.ts
- src/app/portal/components/hearing/request-playback-audio/request-playback-audio.component.spec.ts
- src/app/portal/components/hearing/request-playback-audio/request-playback-audio.component.ts
- src/app/portal/components/hearing/request-transcript/request-times/request-times.component.ts
Ensure in request audio that before end time validation message persists upon request type changes
Logic slightly amended in request transcript validation to enable before time message
> DMP-4777 Bug fix for before time validation in request audio & transcript

- cypress/e2e/functional/admin-portal/event-details-spec.cy.js
- src/app/admin/components/events/show-versions/show-versions.component.html
- src/app/admin/components/events/show-versions/show-versions.component.spec.ts
- src/app/admin/facades/events/events-facade.service.spec.ts
- src/app/admin/facades/events/events-facade.service.ts
- src/app/admin/models/events/event-data.interface.ts
https://tools.hmcts.net/jira/browse/DMP-4841
- displaying "Not set" when undefined
- adding type interface for event version
- adjusting some types and tests to use this new type interface
> DMP-4841 Correcting event version screen to show event ID at the top

- darts-api-stub/admin/events/events.js
- src/app/admin/models/search/admin-event-search-result-data.interface.ts
- src/app/admin/services/admin-search/admin-search.service.ts
https://tools.hmcts.net/jira/browse/DMP-4874
Property in event search admin changed unknowingly
> DMP-4874 - Bug - Event anonymised update

- src/app/admin/components/case/case-file/case-file.component.html
- src/app/admin/components/case/case-file/case-file.component.spec.ts
https://tools.hmcts.net/jira/browse/DMP-4180
Condition now matches user portal case file, 'View or change' link is only visible if case is **not** anonymised
> DMP-4180 Retain link condition

- config/default.json
- server/controllers/api.ts
- server/controllers/authentication.ts
- server/middleware/is-authenticated.ts
- server/routes.ts
- server/types/classes/securityToken.ts
- server/utils/authentication-utils.ts
- server/utils/index.ts
- server/utils/urls.ts
https://tools.hmcts.net/jira/browse/DMP-4450
App insight logs;
No break in session occurred when testing
> DMP-4450 Refresh token changes

- src/app/admin/components/case/case.component.html
- src/app/admin/components/case/case.component.spec.ts
https://tools.hmcts.net/jira/browse/DMP-3236
Only show additional case details tab if data is anonymised
> DMP-3236 admin case file screen no tabs if expired

- config/custom-environment-variables.json
- config/default.json
- cypress/e2e/functional/case-search-spec.cy.js
- darts-api-stub/cases/case.js
- server/app-config.ts
- src/app/core/services/app-config/app-config.service.spec.ts
- src/app/core/services/app-config/app-config.service.ts
- src/app/core/services/dynatrace/dynatrace.service.spec.ts
- src/app/core/services/error/error-message.service.ts
- src/app/portal/components/search/search-error/search-error.component.html
- src/app/portal/components/search/search-error/search-error.component.spec.ts
- src/app/portal/components/search/search-error/search-error.component.ts
https://tools.hmcts.net/jira/browse/DMP-4827
> DMP-4827 Adding specific error message for case search 504 timeout response

- cypress/e2e/functional/admin-portal/audio-file-details-spec.cy.js
- darts-api-stub/admin/medias/medias.js
- src/app/admin/admin.routes.ts
- src/app/admin/components/audio-file/advanced-audio-file-details/advanced-audio-file-details.component.html
- src/app/admin/components/audio-file/advanced-audio-file-details/advanced-audio-file-details.component.scss
- src/app/admin/components/audio-file/advanced-audio-file-details/advanced-audio-file-details.component.spec.ts
- src/app/admin/components/audio-file/advanced-audio-file-details/advanced-audio-file-details.component.ts
- src/app/admin/components/audio-file/audio-file.component.html
- src/app/admin/components/audio-file/audio-file.component.ts
- src/app/admin/components/audio-file/show-versions/show-versions.component.html
- src/app/admin/components/audio-file/show-versions/show-versions.component.spec.ts
- src/app/admin/components/audio-file/show-versions/show-versions.component.ts
- src/app/admin/components/file-deletion/audio-file-results/audio-file-results.component.html
- src/app/admin/models/transformed-media/audio-version-data.interface.ts
- src/app/admin/models/transformed-media/audio-version.ts
- src/app/admin/models/transformed-media/audio-versions-data.interface.ts
- src/app/admin/models/transformed-media/audio-versions.ts
- src/app/admin/services/transformed-media/transformed-media.service.spec.ts
- src/app/admin/services/transformed-media/transformed-media.service.ts
https://tools.hmcts.net/jira/browse/DMP-3306
Show all versions screen for audio file
> DMP-3306 Audio file versions

- src/app/admin/components/search/search-form/search-form.component.ts
- src/app/portal/components/search/search-error/search-error.component.ts
https://tools.hmcts.net/jira/browse/DMP-4839
> DMP-4839 Bug fix for courthouse input overriding

- darts-api-stub/admin/cases/cases.js
- src/app/admin/components/case/case-file/case-file.component.html
- src/app/admin/components/case/case-file/case-file.component.spec.ts
https://tools.hmcts.net/jira/browse/DMP-3236
> DMP-3236 fix hide case details if anonymised

- src/app/core/components/common/courthouse/courthouse.component.ts
https://tools.hmcts.net/jira/browse/DMP-4778
> DMP-4778 fix for courthouse form

- darts-api-stub/admin/cases/cases.js
- darts-api-stub/admin/events/events.js
- darts-api-stub/admin/hearings/hearings.js
- darts-api-stub/admin/medias/medias.js
- darts-api-stub/admin/retention-policies/retention-policies.js
- darts-api-stub/cases/case.js
- darts-api-stub/retentions/retention.js
- darts-api-stub/transcriptions/transcriptions.js
- src/app/core/services/error/error-message.service.spec.ts
- src/app/core/services/error/error-message.service.ts
- src/app/portal/components/transcriptions/transcriptions.component.spec.ts
- src/app/portal/components/transcriptions/transcriptions.component.ts
https://tools.hmcts.net/jira/browse/DMP-4791
- mostly the specific error code is not checked
- the error `type`, such as `CASE_101` is more commonly used
> DMP-4791 Ensuring 422 errors are handled the same as 400 errors

- cypress/e2e/functional/admin-portal/transformed-media-spec.cy.js
- src/app/admin/components/transformed-media/search-transformed-media/search-transformed-media.component.html
- src/app/admin/components/transformed-media/search-transformed-media/search-transformed-media.component.ts
Minor fixes
- sort on descending media id on delete transformed media CYA page
- Confirm --> Yes - delete button text change
- Media ID now linked in CYA page table
https://tools.hmcts.net/jira/browse/DMP-4178
> DMP-4178 sort on desc media id cya page, delete text change, media id link

- cypress/e2e/functional/admin-portal/transcript-requests-spec.cy.js
- src/app/admin/components/case/case-file/case-file.component.html
- src/app/admin/components/common/associated-cases-table/associated-cases-table.component.html
- src/app/admin/components/common/associated-hearings-table/associated-hearings-table.component.html
- src/app/admin/components/file-deletion/transcripts-for-deletion/transcripts-for-deletion.component.html
- src/app/admin/components/hearing/hearing-file/hearing-file.component.html
- src/app/admin/components/search/hearing-search-results/hearing-search-results.component.html
- src/app/admin/components/transcripts/search-completed-transcripts-results/search-completed-transcripts-results.component.html
- src/app/admin/components/transcripts/search-transcripts-results/search-transcripts-results.component.html
- src/app/admin/components/transformed-media/search-transformed-media/search-transformed-media.component.html
- src/app/admin/components/transformed-media/transformed-media-search-results/transformed-media-search-results.component.html
- src/app/admin/components/transformed-media/view-transformed-media/view-transformed-media.component.html
- src/app/admin/components/users/user-transcripts/user-transcripts.component.html
- src/app/core/components/common/details-table/details-table.component.html
- src/app/portal/components/audios/audio-view/audio-view.component.html
- src/app/portal/components/audios/audios.component.html
- src/app/portal/components/case/case-file/case-file.component.html
- src/app/portal/components/case/case-retention-date/case-retention-date.component.html
- src/app/portal/components/case/case.component.html
- src/app/portal/components/hearing/add-annotation/add-annotation.component.html
- src/app/portal/components/hearing/hearing.component.html
- src/app/portal/components/hearing/order-confirmation/order-confirmation.component.html
- src/app/portal/components/hearing/request-transcript/request-transcript.component.html
- src/app/portal/components/search/case-search-results/case-search-results.component.html
- src/app/portal/components/transcriptions/transcription-requests/transcription-requests.component.html
- src/app/portal/components/transcriptions/transcriptions.component.html
- src/app/portal/components/transcriptions/view-transcript/case-hearing-transcript/case-hearing-transcript.component.html
- src/app/portal/components/transcriptions/view-transcript/rejected-transcript/rejected-transcript.component.html
- src/app/portal/components/your-work/your-work.component.html
- src/styles.scss
https://tools.hmcts.net/jira/browse/DMP-4869
- adding `whitespace-pre` class and using in all required places
> DMP-4869 Ensuring whitespace in case numbers is persisted

- src/app/core/components/common/details-table/details-table.component.html
N/A
This is causing some failures in the regression testing suite.
> Reinstating whitespace requried for action links

- src/app/portal/components/case/case.component.html
- src/app/portal/components/case/case.component.spec.ts
- src/app/portal/components/case/case.component.ts
https://tools.hmcts.net/jira/browse/DMP-4897
> DMP-4897 Load case events on tab load

- src/app/core/components/common/datepicker/datepicker.component.html
https://tools.hmcts.net/jira/browse/DMP-4948
- removing keyup event
- it's not required and was causing the cursor to focus at the end of the value if the date value was amended
> DMP-4948 Fixing date picker manual entry issue

- cypress/e2e/functional/admin-portal/audio-file-details-spec.cy.js
- cypress/e2e/functional/admin-portal/transformed-media-spec.cy.js
- darts-api-stub/admin/medias/medias.js
- src/app/admin/admin.routes.ts
- src/app/admin/components/audio-file/basic-audio-file-details/basic-audio-file-details.component.html
- src/app/admin/components/audio-file/basic-audio-file-details/basic-audio-file-details.component.ts
- src/app/admin/components/audio-file/set-current-version/set-current-version.component.html
- src/app/admin/components/audio-file/set-current-version/set-current-version.component.spec.ts
- src/app/admin/components/audio-file/set-current-version/set-current-version.component.ts
- src/app/admin/components/audio-file/show-versions/show-versions.component.html
- src/app/admin/components/audio-file/show-versions/show-versions.component.scss
- src/app/admin/components/audio-file/show-versions/show-versions.component.spec.ts
- src/app/admin/components/audio-file/show-versions/show-versions.component.ts
- src/app/admin/components/transformed-media/view-transformed-media/view-transformed-media.component.html
- src/app/admin/components/transformed-media/view-transformed-media/view-transformed-media.component.ts
- src/app/admin/services/transformed-media/transformed-media.service.spec.ts
- src/app/admin/services/transformed-media/transformed-media.service.ts
- src/app/core/components/common/data-table/data-table.component.html
- src/app/core/components/common/data-table/data-table.component.spec.ts
- src/app/core/components/common/data-table/data-table.component.ts
- src/app/core/pipes/file-size.pipe.spec.ts
- src/app/core/pipes/file-size.pipe.ts
https://tools.hmcts.net/jira/browse/DMP-4181
Introduced a single row select mode to the data-table component as part of this ticket
> DMP-4181 Set current new version changes

- cypress/e2e/functional/request-audio-spec.cy.js
- src/app/portal/components/hearing/events-and-audio/events-and-audio.component.spec.ts
- src/app/portal/components/hearing/events-and-audio/events-and-audio.component.ts
https://tools.hmcts.net/jira/browse/DMP-4924
> DMP-4924 events and audio changed to asc order

- server/index.ts
https://tools.hmcts.net/jira/browse/DMP-4937
Trying adding a wait after closing the server. The wait time matches the k8s liveness probe period seconds.
> DMP-4937 Graceful shutdown fixes 2

- server/middleware/is-authenticated.ts
- server/routes.ts
https://tools.hmcts.net/jira/browse/DMP-4988
- the authentication check middleware was not catching the error correctly
- fixed this to ensure 401 response is given
> DMP-4988 Fixing error page after session timeout

- darts-api-stub/admin/cases/cases.js
- darts-api-stub/admin/events/events.js
- darts-api-stub/admin/hearings/hearings.js
- darts-api-stub/admin/medias/medias.js
- src/app/admin/components/search/search.component.html
- src/app/admin/components/search/search.component.spec.ts
- src/app/admin/services/admin-search/admin-search.service.spec.ts
- src/app/admin/services/admin-search/admin-search.service.ts
https://tools.hmcts.net/jira/browse/DMP-4845
> DMP-4845 Added no criteria error handling to admin search

- src/app/admin/components/search/search-form/search-form.component.spec.ts
- src/app/admin/components/search/search-form/search-form.component.ts
- src/app/admin/components/search/search.component.html
- src/app/admin/components/search/search.component.spec.ts
- src/app/admin/components/search/search.component.ts
https://tools.hmcts.net/jira/browse/DMP-4845
> DMP-4845 AC2 date range span check

- src/app/admin/components/search/search.component.ts
https://tools.hmcts.net/jira/browse/DMP-4845
Bug fix for AC2
> DMP-4845 Date range error message bug fix

- cypress/e2e/functional/admin-portal/transcript-requests-spec.cy.js
- src/app/admin/services/transcription-admin/transcription-admin.service.spec.ts
- src/app/admin/services/transcription-admin/transcription-admin.service.ts
https://tools.hmcts.net/jira/browse/DMP-4891
> DMP-4891 rename assigned to column header

- src/app/portal/components/search/case-search-form/case-search-form.component.spec.ts
- src/app/portal/components/search/case-search-form/case-search-form.component.ts
- src/app/portal/services/case/case.service.ts
N/A
- using the default values when resetting because the FormControl doesn't specify an initial value for use in a reset
> Fixing courthouses on Case search reset

- cypress/e2e/functional/admin-portal/search-spec.cy.js
- src/app/admin/components/search/search-form/search-form.component.spec.ts
- src/app/admin/components/search/search-form/search-form.component.ts
- src/app/admin/components/search/search.component.html
- src/app/admin/components/search/search.component.spec.ts
- src/app/admin/components/search/search.component.ts
- src/app/admin/services/admin-search/admin-search.service.ts
- src/app/admin/services/courthouse-forms/courthouse-form.service.spec.ts
- src/app/admin/services/courthouse-forms/courthouse-form.service.ts
- src/app/core/utils/date-range.utils.ts
- src/app/portal/components/search/case-search-form/case-search-form.component.spec.ts
- src/app/portal/components/search/case-search-form/case-search-form.component.ts
https://tools.hmcts.net/jira/browse/DMP-5015
> DMP-5015 Admin search - change tab on logic error

- src/app/core/services/auth/auth.service.ts
- src/app/core/services/error/error-message.service.ts
https://tools.hmcts.net/jira/browse/DMP-4937
- ignoring 50X errors for `/auth/is-authenticated` and `/user/refresh-profile`
- these endpoints are checked every time the route is changed so ignoring a transient 502/504 does no harm
> DMP-4927 Prevent error when getting 50X on refresh profile and auth check

- charts/darts-portal/Chart.yaml
- charts/darts-portal/values.yaml
- server/index.ts
- server/server.ts
- server/types/global.d.ts
https://tools.hmcts.net/jira/browse/DMP-4937
- on SIGTERM set global `isTerminating` boolean
- add a check for this to the readiness check
- wait 10s before closing server to allow the readiness check to fail
- removing wait after server close, it's not required
> DMP-4937 Shutdown tweaks

- charts/darts-portal/Chart.yaml
- charts/darts-portal/values.yaml
- server/index.ts
https://tools.hmcts.net/jira/browse/DMP-4937
> DMP-4937 Increasing wait because the readiness failure threshold is set at 3

- cypress/e2e/functional/admin-portal/audio-file-details-spec.cy.js
- src/app/admin/components/audio-file/advanced-audio-file-details/advanced-audio-file-details.component.scss
- src/app/admin/components/audio-file/set-current-version/set-current-version.component.html
- src/app/admin/components/audio-file/show-versions/show-versions.component.ts
- src/app/core/components/common/data-table/data-table.component.html
https://tools.hmcts.net/jira/browse/DMP-5020
> DMP-5020 accessibility fix for th single checkbox select

- src/app/admin/components/groups/group-courthouses/group-courthouses.component.html
- src/app/admin/components/groups/group-courthouses/group-courthouses.component.spec.ts
- src/app/admin/components/groups/group-courthouses/group-courthouses.component.ts
- src/app/admin/components/groups/group-record/group-record.component.html
- src/app/admin/components/groups/group-record/group-record.component.spec.ts
- src/app/admin/components/groups/group-record/group-record.component.ts
- src/app/core/components/common/govuk-banner/govuk-banner.component.ts
- src/app/core/services/scroll/scroll.service.ts
>[Jira](https://tools.hmcts.net/jira/browse/DMP-4907)
This Git diff includes updates to the `GroupCourthousesComponent` and `GroupRecordComponent` in an Angular application. The changes primarily focus on improving the way courthouses are selected and managed, enhancing the component's functionalities and tests.
- **Selection Source Update**: The source for the courthouse selection was changed from `allCourthouses` to `allNotSelectedCourthouses()` to ensure only unselected courthouses are displayed.
- **Signal Implementation**: Introduced the use of a signal for `allNotSelectedCourthouses` to manage state reactively.
- **Initialization**: Implemented `ngOnInit` to initialize the courthouse selection when the component loads.
- **Method Enhancements**: Updated methods for adding and …
> DMP-4907: ENHANCEMENT: Add a confirmation banner at top of screen when adding courthouse to group

- cypress/e2e/functional/admin-portal/transcript-requests-spec.cy.js
- package.json
- src/app/admin/components/transcripts/view-transcription-document/transcript-file-basic-detail/transcript-file-basic-detail.component.html
- src/app/admin/components/transcripts/view-transcription-document/transcript-file-basic-detail/transcript-file-basic-detail.component.spec.ts
- yarn.lock
https://tools.hmcts.net/jira/browse/DMP-5052
"Requested date" and "Approved on" are now showing times
> DMP-5052 Adding times to requested/approved on transcript file screen

- src/app/admin/components/audio-file/show-versions/show-versions.component.html
- src/app/admin/components/audio-file/show-versions/show-versions.component.spec.ts
- src/app/admin/components/audio-file/show-versions/show-versions.component.ts
- src/app/admin/components/events/show-versions/show-versions.component.html
- src/app/admin/components/events/show-versions/show-versions.component.spec.ts
- src/app/admin/components/events/show-versions/show-versions.component.ts
- src/app/admin/facades/events/events-facade.service.spec.ts
- src/app/admin/facades/events/events-facade.service.ts
- src/app/admin/models/events/event-versions.ts
- src/app/admin/models/transformed-media/audio-versions.ts
- src/app/admin/services/events/events.service.spec.ts
- src/app/admin/services/events/events.service.ts
- src/app/admin/services/transformed-media/transformed-media.service.spec.ts
- src/app/admin/services/transformed-media/transformed-media.service.ts
https://tools.hmcts.net/jira/browse/DMP-4181
https://tools.hmcts.net/jira/browse/DMP-4887
> DMP-4181 DMP-4887 handle no current versions on audio and event version screen

- src/app/admin/components/transformed-media/transformed-media-search-results/transformed-media-search-results.component.html
- src/app/admin/components/transformed-media/transformed-media-search-results/transformed-media-search-results.component.spec.ts
https://tools.hmcts.net/jira/browse/DMP-5030
> DMP-5030 Hide transformed media delete button when no results exist

- cypress/e2e/functional/admin-portal/audio-file-details-spec.cy.js
- cypress/e2e/functional/admin-portal/transcript-requests-spec.cy.js
- src/app/admin/components/case/case-file/case-file.component.html
- src/app/admin/components/file-deletion/audio-file-delete/audio-file-delete.component.html
- src/app/admin/components/file-deletion/audio-file-results/audio-file-results.component.html
- src/app/admin/components/file-deletion/transcripts-for-deletion/transcripts-for-deletion.component.html
- src/app/admin/components/hearing/hearing-file/hearing-file.component.html
- src/app/admin/components/transformed-media/associated-audio-table/associated-audio-table.component.html
- src/app/core/components/common/expired-banner/expired-banner.component.html
- src/app/portal/components/audios/audio-view/audio-view.component.html
- src/app/portal/components/case/case-file/case-file.component.html
- src/app/portal/components/hearing/hearing-file/hearing-file.component.html
- src/app/portal/components/hearing/hearing.component.html
- src/app/portal/components/hearing/order-confirmation/order-confirmation.component.html
- src/app/portal/components/hearing/request-transcript/request-transcript.component.html
https://tools.hmcts.net/jira/browse/DMP-4814
> DMP-4814 date format change from d to dd

- src/app/portal/components/transcriptions/assign-transcript/assign-transcript.component.ts
- src/app/portal/components/your-work/upload-transcript/upload-transcript.component.html
https://tools.hmcts.net/jira/browse/DMP-5059
- only for migrated data
- navigate to case file screen instead
> DMP-5059 Fixing get audio navigation for transcriptions with no hearing

- src/app/admin/components/search/hearing-search-results/hearing-search-results.component.html
- src/app/admin/components/transcripts/search-completed-transcripts-results/search-completed-transcripts-results.component.html
- src/app/admin/components/transcripts/search-completed-transcripts-results/search-completed-transcripts-results.component.spec.ts
- src/app/admin/components/transcripts/search-completed-transcripts-results/search-completed-transcripts-results.component.ts
- src/app/admin/components/transcripts/search-transcripts-results/search-transcripts-results.component.html
- src/app/admin/components/transcripts/search-transcripts-results/search-transcripts-results.component.ts
- src/app/admin/components/transformed-media/transformed-media-search-results/transformed-media-search-results.component.html
- src/app/admin/components/transformed-media/transformed-media-search-results/transformed-media-search-results.component.ts
- src/app/admin/components/transformed-media/view-transformed-media/view-transformed-media.component.html
- src/app/admin/models/transcription/transcription-data.interface.ts
- src/app/admin/models/transcription/transcription-document-search-result.ts
- src/app/admin/models/transcription/transcription.ts
- src/app/admin/services/transcription-admin/transcription-admin.service.spec.ts
- src/app/admin/services/transcription-admin/transcription-admin.service.ts
https://tools.hmcts.net/jira/browse/DMP-4965
Awaiting on endpoint updates to include hearing_id on transcript/transcript document search results.
> DMP-4965 Added hearing id links where possible

- src/app/portal/components/hearing/add-annotation/add-annotation.component.html
https://tools.hmcts.net/jira/browse/DMP-4814
> DMP-4814 remove spelling mistake

- package.json
- yarn.lock
N/A
- v5 is giving errors initialising the date pickers
> Using MoJ frontend v4

- cypress/e2e/functional/admin-portal/group-record-spec.cy.js
- src/app/admin/admin.routes.ts
- src/app/admin/components/groups/group-courthouses/group-courthouses.component.html
- src/app/admin/components/groups/group-courthouses/group-courthouses.component.ts
- src/app/admin/components/groups/group-record/group-record.component.html
- src/app/admin/components/groups/group-record/group-record.component.spec.ts
- src/app/admin/components/groups/group-record/group-record.component.ts
- src/app/admin/components/groups/group-users/group-users.component.html
- src/app/admin/components/groups/group-users/group-users.component.ts
- src/app/admin/components/groups/groups.component.html
- src/app/admin/components/groups/groups.component.spec.ts
- src/app/admin/components/groups/groups.component.ts
- src/app/core/components/layout/header/admin-navigation/admin-navigation.component.html
- src/app/core/services/user/user.service.ts
https://tools.hmcts.net/jira/browse/DMP-5064
> DMP-5064 Super user permissions for group page admin

- src/app/app.routes.spec.ts
- src/app/core/guards/auth/auth.guard.spec.ts
- src/app/core/guards/auth/auth.guard.ts
- src/app/core/services/user/user.service.spec.ts
- src/app/core/services/user/user.service.ts
N/A
I was seeing an issue with a user that belongs to a non-global access group associated with the `SUPER_ADMIN` role. This allowed the user access to admin routes, which is not correct.
This improvement fixes this issue, by always checking for global access on `allowedRoles` for admin routes. More tests have been added to cover these scenarios.
> Improvements to auth guard for admin routes

- cypress/e2e/functional/case-file-spec.cy.js
- darts-api-stub/cases/case.js
- src/app/core/components/common/see-more-list/see-more-list.component.html
- src/app/core/components/common/see-more-list/see-more-list.component.spec.ts
- src/app/core/components/common/see-more-list/see-more-list.component.ts
- src/app/portal/components/case/case-file/case-file.component.html
- src/app/portal/components/case/case-file/case-file.component.scss
- src/app/portal/components/case/case-file/case-file.component.ts
https://tools.hmcts.net/jira/browse/DMP-3970
See [/case/5](http://localhost:3000/case/5) for judges dropdown
> DMP-3970 judge case file screen

- src/app/admin/admin.routes.ts
- src/app/admin/services/transcription-admin/transcription-admin.service.spec.ts
- src/app/admin/services/transcription-admin/transcription-admin.service.ts
https://tools.hmcts.net/jira/browse/DMP-5079
- removing the "Change status" link from the transcription request screen
- remove super user access to the transcript `/change-status` URL
> DMP-5079 Preventing superuser changing the status of a transcript request

- src/app/admin/services/courthouses/courthouse.service.spec.ts
- src/app/admin/services/courthouses/courthouses.service.ts
https://tools.hmcts.net/jira/browse/DMP-4982
- sort the courthouses by display name when fetched from the API
- removing the sort during mapping as it's now redundant
- refactoring courthouse service tests for better assertions
> DMP-4982 Fixing courthouse sort order on group courthouse screen

- src/app/admin/components/courthouses/courthouse-record/courthouse-record.component.html
- src/app/admin/components/courthouses/courthouse-record/courthouse-record.component.spec.ts
- src/app/admin/components/courthouses/courthouse-record/courthouse-record.component.ts
https://tools.hmcts.net/jira/browse/DMP-4981
> DMP-4981 handle back links in courthouse record

- src/app/portal/components/hearing/events-and-audio/events-and-audio.component.html
- src/app/portal/components/hearing/events-and-audio/events-and-audio.component.spec.ts
- src/app/portal/components/hearing/events-and-audio/events-and-audio.component.ts
- src/app/portal/components/hearing/hearing.component.html
- src/app/portal/components/hearing/hearing.component.ts
- src/app/portal/components/hearing/request-playback-audio/request-playback-audio.component.spec.ts
- src/app/portal/components/hearing/request-playback-audio/request-playback-audio.component.ts
https://tools.hmcts.net/jira/browse/DMP-5033
> DMP-5033 Reset form selections on order confirmation

- src/app/admin/components/case/case.component.html
- src/app/admin/components/case/case.component.ts
- src/app/portal/components/search/case-search-results/case-search-results.component.html
- src/app/portal/components/search/case-search-results/case-search-results.component.spec.ts
- src/app/portal/components/search/case-search-results/case-search-results.component.ts
https://tools.hmcts.net/jira/browse/DMP-5062
> DMP-5062 Added active tab service for case file admin

- src/app/portal/components/hearing/request-playback-audio/request-playback-audio.component.ts
https://tools.hmcts.net/jira/browse/DMP-5033
> DMP-5033 Resetting audio request "request type" correctly

- charts/darts-portal/Chart.yaml
- charts/darts-portal/values.yaml
- server/index.ts
- src/app/portal/components/search/case-search-form/case-search-form.component.spec.ts
- src/app/portal/components/search/case-search-form/case-search-form.component.ts
- src/app/portal/components/transcriptions/transcriptions.component.html
- src/app/portal/components/transcriptions/transcriptions.component.spec.ts
https://tools.hmcts.net/jira/browse/DMP-5088
Bug was due to case search date pickers not being picked up as form changes thus not allowing subsequent searches
This PR should also fix [DMP-5145](https://tools.hmcts.net/jira/browse/DMP-5145)
> DMP-5088 fix for date picker changes not allowing search

- cypress/e2e/functional/admin-portal/search-spec.cy.js
- cypress/e2e/functional/case-search-spec.cy.js
- src/app/admin/components/search/search-form/search-form.component.html
- src/app/admin/components/search/search-form/search-form.component.ts
- src/app/admin/constants/admin-search-form-error-messages.ts
- src/app/admin/constants/case-search-form-error-messages.ts
- src/app/portal/components/search/case-search-form/case-search-form.component.html
- src/app/portal/components/search/case-search-form/case-search-form.component.ts
https://tools.hmcts.net/jira/browse/DMP-5144
32 char limit check on case search and admin search
[Playwright changes ](https://github.com/hmcts/darts-automation-playwright/pull/152)
> DMP-5144 Introduce 32 length check for case id 

- src/app/core/components/common/delete/delete.component.html
- src/app/core/components/common/delete/delete.component.spec.ts
- src/app/core/components/common/delete/delete.component.ts
https://tools.hmcts.net/jira/browse/DMP-5139
> DMP-5139 Applied disabled logic on confirmation to delete component

- cypress/e2e/functional/admin-portal/user-record-spec.cy.js
- src/app/admin/components/users/user-groups/assign-groups/assign-groups.component.spec.ts
- src/app/admin/components/users/user-groups/assign-groups/assign-groups.component.ts
- src/app/admin/components/users/user-record/user-record.component.html
- src/app/admin/components/users/user-record/user-record.component.spec.ts
- src/app/admin/components/users/user-record/user-record.component.ts
https://tools.hmcts.net/jira/browse/DMP-4888
> DMP-4888 update assigned groups message to newly assigned count

- src/app/core/validators/group-name.validator.spec.ts
- src/app/core/validators/group-name.validator.ts
https://tools.hmcts.net/jira/browse/DMP-5043
- case insensitive validation
- trim whitespace
> DMP-5043 Improvements for validation of group name

- src/app/admin/components/courthouses/courthouse-record/courthouse-record.component.ts
- src/app/admin/components/system-configuration/event-mappings/add-update-event-mapping/add-update-event-mapping.component.spec.ts
- src/app/admin/components/system-configuration/event-mappings/add-update-event-mapping/add-update-event-mapping.component.ts
- yarn.lock
https://tools.hmcts.net/jira/browse/DMP-5081
> DMP-5081 Event mapping id and inactive checks

- src/styles.scss
https://tools.hmcts.net/jira/browse/DMP-5066
- fixed by allowed text wrapping on case numbers
- via the existing `whitespace-pre` class which specifically targets case numbers
- fixed on all tables showing case number- 
> DMP-5066 - Fixing long case numbers flowing into other table cells

- src/app/admin/components/audio-file/advanced-audio-file-details/advanced-audio-file-details.component.html
- src/app/admin/components/audio-file/advanced-audio-file-details/advanced-audio-file-details.component.spec.ts
- src/app/admin/components/audio-file/audio-file.component.spec.ts
- src/app/admin/components/audio-file/audio-file.component.ts
- src/app/admin/components/automated-tasks/view-automated-tasks/view-automated-tasks.component.spec.ts
- src/app/admin/components/automated-tasks/view-automated-tasks/view-automated-tasks.component.ts
- src/app/admin/components/transcripts/view-transcription-document/transcript-file-advanced-detail/transcript-file-advanced-detail.component.spec.ts
- src/app/admin/components/transcripts/view-transcription-document/transcript-file-advanced-detail/transcript-file-advanced-detail.component.ts
- src/app/admin/components/transcripts/view-transcription-document/view-transcription-document.component.spec.ts
- src/app/admin/components/transcripts/view-transcription-document/view-transcription-document.component.ts
- src/app/admin/facades/transcript/transcript-facade.service.spec.ts
- src/app/admin/facades/transcript/transcript-facade.service.ts
- src/app/admin/models/transcription/transcription-assignee.ts
- src/app/admin/models/transcription/transcription-document.ts
- src/app/admin/models/transcription/transcription-requestor.ts
- src/app/admin/models/transformed-media/admin-action.ts
- src/app/admin/models/transformed-media/audio-file.ts
- src/app/admin/services/transcription-admin/transcription-admin.service.spec.ts
- src/app/admin/services/transcription-admin/transcription-admin.service.ts
- src/app/admin/services/user-admin/user-admin.service.spec.ts
- src/app/admin/services/user-admin/user-admin.service.ts
- src/app/core/components/common/timeline/timeline.component.html
- src/app/core/components/common/timeline/timeline.component.spec.ts
- src/app/core/models/timeline/timeline.type.ts
- src/app/dev/dev.component.ts
https://tools.hmcts.net/jira/browse/DMP-5003
This requires DARTS API change https://github.com/hmcts/darts-api/pull/2965 to be merged first.
- amending API call to return system users
- fixing dev component
The following screens are fixed
- admin transcription screen - details - request by
- admin transcription screen - history - workflow user
- admin transcript file screen - uploaded by, last modified by, hidden by
- audio file screen
- automated task screen
> DMP-5003 Changes to hyperlink users only if they are non-system users

- cypress/e2e/functional/admin-portal/automated-tasks-spec.cy.js
- src/app/admin/components/automated-tasks/view-automated-tasks/view-automated-tasks.component.ts
https://tools.hmcts.net/jira/browse/DMP-5073
- Update `addUserDetailsToTask()` to ignore the order of users returned from `userAdminService.getUsersById()`
- Add tests for Created By and Modified By fields of Automated Tasks
> DMP-5073 Fixing Created By field when marking automated task as inactive

- cypress/e2e/functional/admin-portal/event-details-spec.cy.js
- darts-api-stub/admin/events/events.js
- src/app/admin/admin.routes.ts
- src/app/admin/components/audio-file/set-current-version/set-current-version.component.html
- src/app/admin/components/audio-file/show-versions/show-versions.component.html
- src/app/admin/components/events/set-current-version/set-current-version.component.html
- src/app/admin/components/events/set-current-version/set-current-version.component.spec.ts
- src/app/admin/components/events/set-current-version/set-current-version.component.ts
- src/app/admin/components/events/show-versions/show-versions.component.html
- src/app/admin/components/events/show-versions/show-versions.component.scss
- src/app/admin/components/events/show-versions/show-versions.component.spec.ts
- src/app/admin/components/events/show-versions/show-versions.component.ts
- src/app/admin/facades/events/events-facade.service.ts
- src/app/admin/models/events/event-version.ts
- src/app/admin/services/events/events.service.spec.ts
- src/app/admin/services/events/events.service.ts
https://tools.hmcts.net/jira/browse/DMP-4383
https://tools.hmcts.net/jira/browse/DMP-4313
> DMP-4383/4313 Set new version for events, double click submit prevention

- src/app/core/components/layout/header/header.component.html
- src/app/core/components/layout/header/header.component.spec.ts
- src/app/core/components/layout/header/header.component.ts
https://tools.hmcts.net/jira/browse/DMP-5109
https://tools.hmcts.net/jira/browse/DMP-5173
Prevents unnecessary request when loading admin portal
> DMP-5109/5173 defer loading of nav components

- yarn.lock
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
> Renovate angular-cli monorepo fix
